pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller.go
Puts "ensure CephCluster" code in its own function with the ability to add more
similar functions that ensure the existence of other resources.
Updates a CephCluster resource if its Spec does not match the desired state.
Stopped accessing r.reqLogger from Reconcile since it's possible for two
Reconciles to run concurrently. We set the name and namespace of the resource
being reconciled on the logger as attributes, so we don't want two Reconciles
fighting over that.
=> refactors Reconcile to support Update and prepare for more resource types

must-gather/collection-scripts/gather_ceph_resources
This commit adds support to collect the json output of ceph commands that can be used by json parsers to validate the results against validation rules.
=> enhance: Adds support to collect the json output of ceph commands

pkg/controller/storagecluster/reconcile.go
With https://github.com/openshift/ocs-operator/pull/21 merged,
the comment in front of newCephCluster() is now outdated. Update it.
=> Update a comment

deploy/crds/ocs_v1alpha1_storagecluster_cr.yaml, deploy/deploy-with-olm.yaml, deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/ocs-operator/0.0.1/rookcephfilesystems.crd.yaml, pkg/controller/storagecluster/reconcile.go
This PR updates the CSV and OLM deployment required to get rook-ceph to start a
CephCluster successfully.
There will be one additional PR on top of this, which brings in support for
running mons with PVs.
=> Updates to CSV and OLM deployment

deploy/crds/ocs_v1alpha1_storagecluster_cr.yaml, deploy/deploy-with-olm.yaml, deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/ocs-operator/0.0.1/rookcephfilesystems.crd.yaml, pkg/controller/storagecluster/reconcile.go
This commit configures the CephClusters created by the controller, to use PVs
for the mon pods.
It adds a VolumeClaimTemplate for the mons. The VolumeClaimTemplate is based on
the DataPVCTemplate of the first StorageDeviceSet configured in the
StorageCluster, and is created only if one StorageDeviceSet is present.
This builds on top of #30, and should be merged after it.
=> Use PVs for Mons

deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/ocs-operator/0.0.1/storageclusterinitialization.crd.yaml
This PR adds StorageClusterInitialization CRD to the CSV. It also updates the
alm-examples to include examples for all CRs managed by the ocs-operator.
=> Add StorageClusterInitialization to CSV

Makefile
This allows `make ocs-operator` to succeed when running within
$GOPATH/src.
=> Set 'GO111MODULE=on' when building ocs-operator

deploy/deploy-with-olm.yaml, deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml
- Adds local-storage-operator as dependency of ocs-operator
- Updates deploy-with-olm.yaml to include local-storage-operator
-----
Few things to note,
1. `local-storage-operator` needs to be a part of `olm-catalog` for dependency to be resolved automatically.
2. `deploy-with-olm.yaml` deploys the catalogSource and operatorGroup for `local-storage-operator` along with `ocs-operator`.
3. To be able to test this, we need a new build of `bundle` at `quay.io/ocs-dev/ocs-registry`
=> updates CSV : Deploy Local-Storage-Operator

Makefile
In my previous PR I accidentally put an underscore in front of the `OUTPUT_DIR` directory variable path which meant `make clean` wasn't cleaning up the directory that had the actual build artifacts in it.
=> Fix makefile path location variable

deploy/crds/ocs_v1alpha1_storageclusterinitialization_crd.yaml, pkg/apis/ocs/v1alpha1/storagecluster_types.go, pkg/apis/ocs/v1alpha1/zz_generated.openapi.go
The openapi generation was not done after the introduction of StorageClusterInitialization.
=> api: Update generated files

deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, pkg/controller/storagecluster/reconcile.go
- updates CSV to change rook-ceph operator deployment
enables nodeAffinity and toleration env var for rook agents
- updates CephCluster CR
adds nodeAffinity, toleration, podAntiAffinity to all services
=> adds Placement Configuration for rook-ceph agents and services

deploy/role.yaml
fixes this error in the ocs-operator caused by the ceph cluster informer not having the 'watch' RBAC permission. 
```
E0823 17:55:09.056177       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.CephCluster: unknown (get cephclusters.ceph.rook.io)
E0823 17:55:10.060386       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.CephCluster: unknown (get cephclusters.ceph.rook.io)
E0823 17:55:11.063933       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.CephCluster: unknown (get cephclusters.ceph.rook.io)
E0823 17:55:12.068141       1 reflector.go:251] …
```
=> Adds 'watch' RBAC for ceph cluster objects

deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, pkg/controller/storagecluster/reconcile.go
This PR,
- Reverts #51 - This was added new placement configuration which used an
invalid label, leading the rook failing to correctly deploy a CephCluster
- Pins version of the rook/ceph image to a known working version
- Updates permission for the ocs-operator in CSV.
=> Unbreak ocs-operator

deploy/deploy-with-olm.yaml
#42 was pointing it to another image for testing. Forgot to get it changed back before merging.
=> deploy: Point ocs-dev registry image

deploy/olm-catalog/ocs-operator/0.0.1/role_binding_metrics.yaml, deploy/olm-catalog/ocs-operator/0.0.1/role_binding_monitor.yaml, deploy/olm-catalog/ocs-operator/0.0.1/role_metrics.yaml, deploy/olm-catalog/ocs-operator/0.0.1/role_monitor.yaml
- CSV includes rbac for monitoring components
- Bundle includes rbac for cross-namespace rolebinding
OLM doesn't support cross-namespace rolebinding (via CSV).
This is a must-have for OCS to be monitored via OCP Monitoring.
To achieve this, it is necessary that we add these extra rbac
manifests into the bundle and deploy it as a part of operator
bundle deployment.
=> updated CSV & Bundle to enable OCS Monitoring

deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, deploy/role.yaml
- this change allows ocs-operator to perform all kinds of actions(CRUD)
on rook-ceph resources
- this also enables cluster expansion via CephCluster CR update
=> updates permission of ocs-operator serviceaccount

Makefile, README.md, deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, hack/generate-latest-csv.sh, tools/csv-merger/csv-merger.go
This change pins the latest CSV to a specific set of container images and adds a single make target `make gen-latest-csv` to regenerate changes. 
Running `make gen-latest-csv' will rebuild the CSV and cause changes in the source tree to occur if anything is altered. In the openshift/release project (where we have our CI) I've also included a [test](https://github.com/openshift/release/pull/4893) to verify the CSV is up to date. This prevents someone from making a change to the CSV generation logic without updating the CSV manifests themselves.
=> Improve Latest CSV Generation Workflow. 

deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, hack/generate-latest-csv.sh
The rook/ceph images with SHA do no get pulled in OCP.
Also, image SHA don't work with podman.
=> csv: Use image versions inplace of SHA

pkg/controller/storagecluster/reconcile.go
Rook only supports a single mgr, so the anti-affinity will effectively not be
needed anyway.
Continuation of #76 
=> Remove Rook-Ceph mgr anti-affinity

test/crd_validation_test.go
storagecontainerinitialization CR/CRD added to master, but were not added to CRD validation tests. Fixing that.
=> adding storageclusterinitialization CR/CRD to existing validation tests

hack/cluster-deploy.sh, openshift-ci/Dockerfile.deploy
The Openshift CI e2e job is failing to deploy the ocs-operator. I need info about the pods to diagnose what's happening. 
I also altered one of the Openshift CI Dockerfiles to use ubi7 instead of ubi8. This is to be consistent with the containers defined in the Openshift CI release config.
=> Openshift e2e CI debug

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
This reverts commit e7be566c5f2d50f990287c2365c9e75e2227c5f4.
This breaks deployments where we don't have zones or have too few zones.
So this needs more thought. Reverting this change so that testing is
unblocked.
=> Revert "Change failure domain to zone for all cephv1.PoolSpecs"

pkg/controller/storagecluster/reconcile.go
This PR sets the podAntiAffinity topologyKey to 'kubernetes.io/hostname'
in the placement config of StorageClassDeviceSet.
=> storagecluster: Set topologyKey for podAntiAffinity

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
StorageClusterInitialization had a bunch of Update related bugs. It was trying to update objects with empty metadata which caused it to fail. This fixes all the update issues by assigning proper values.
=> Storage cluster initialization fixes

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
- updated the func to preserve metadata during updates. using new
objectstore object to do the update rather than overriding the
existing one. This prevents the updates from failing.
=> updated ensureCephObjectStore func in StorageClusterInitialization

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
- updated the func to preserve metadata during updates. using new
objectstoreuser object to do the update rather than overriding the
existing one. This prevents the updates from failing.
=> updated ensureCephObjectStoreUser func in StorageClusterInitialization

must-gather/collection-scripts/gather_ceph_resources
This commit removes info collection for cephnfs CR in must-gather as cephnfs will not be a part of OCS.
=> refactor(must-gather): remove info collections for cephnfs

hack/generate-latest-csv.sh
The hack/generate-latest-csv.sh script now accepts container image values from
envvars.
=> csv: Allow setting images with envvars

go.mod, pkg/controller/storagecluster/reconcile.go
This commit fixes custom placement provided in storageCluster not getting applied to cephCluster.
=> fix: custom placement not getting applied to CephCluster

Makefile, build/Dockerfile, hack/lint.sh, hack/verify-generated.sh, hack/verify-latest-csv.sh
This adds make targets for all the tests Openshift CI prow executes.
I removed the usage of the operator-sdk from the ocs-operater build process (it is still however used for the code generation make target). This allows us to have separate make targets for building the binary and building the container image. There's no impact to the dev flow. 'make ocs-operator' still results in the same container image being built along with the binary.
=> Add make targets for common prow tests

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
- RequiredDuringScheduling AntiAffinity does not allow MDS
pods to be deployed on same node when count of MDS pods is
more than count of available nodes. Changing it to Preferred
with weight of 100 will make scheduler try its best to distribute
these pods.
=> Changes Required Pod AntiAffinity to Preferred for MDS

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
- RequiredDuringScheduling AntiAffinity of rgw pods does not allow
more rgw pods to be deployed than the number of nodes. Changing
it to PreferredDuringScheduling will enable us to do so. Weight of
100 ensure that scheduler tries its best to spread the pods across
topologyKey.
=> Changes RequiredDuringScheduling AntiAffinity to Preferred

pkg/controller/storagecluster/reconcile.go
A misplaced return in the `newCephCluster` function, was preventing PVC
templates being set for mons in the generated CephCluster
=> storagecluster: Remove misplaced return

Makefile, README.md, hack/common.sh, hack/functest.sh, hack/red-hat-storage-ocs-ci-tests.sh, vendor/modules.txt
This introduces the ability to run a subset of the [ocs-ci](https://github.com/red-hat-storage/ocs-ci) test suite against an ocs-operator cluster.
I also include some README.md text around this test suite. Once this PR is merged with the `make red-hat-storage-ocs-ci` make target, I can add a prow job to execute the ocs-ci tests in parallel to the developer ginkgo `functests/*` test suite.
=> 'make red-hat-storage-ocs-ci' for running downstream ocs-ci tests

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
The "pool" parameter of the CephFS storage class, was being set to the
block pool used by the RBD storage class. Removing the "pool" param,
makes the CephFS storage class use the default data pools created for
the CephFilesystem.
Fixes #128.
=> storageclusterinit: Do not set "pool" param for CephFS SC

hack/lint.sh, hack/red-hat-storage-ocs-ci-tests.sh, openshift-ci/Dockerfile.tools
In order to execute the red-hat-storage/ocs-ci test suite in prow, we need a custom build root container for openshift ci that contains python.
Changes
* Introduces openshift ci tools Docker file (prow update using this will be posted once this is merged)
* Fixes ocs-ci source caching (prevents re-downloading source locally if it already exists)
* Fixes issue with `golint` appearing to pass if the golint binary isn't present.
=> Openshift ci build tools for red-hat-storage/ocs-ci execution

hack/source-manifests.sh
This commit adds support to generate CSVs in Darwin environments. Sed command in Linux accepts different arguments for inplace replacement than Darwin's which makes existing generation scripts incompatible with Darwin environments.
=> enhance: Adds support to generate CSVs in MacOS

openshift-ci/Dockerfile.tools
The openshift-ci build-root container wasn't working in CI because the GOPATH was only accessible to root. Openshift-ci is running this container as a non-root pod, which prevented builds from working.
I changed the permissions on the GOPATH directory tree now so that all users have access.
If you want to this build-root container yourself locally, run the following
```
docker build -f openshift-ci/Dockerfile.tools -t ocs-build-tools:latest
docker run --rm -v $(pwd):/go/src/github.com/openshift/ocs-operator -it ocs-build-tools:latest
make build
```
We can use this container as a basis for dockerized make targets in the future.
=> Fix GOPATH dir permissions for build root container

Makefile
This commit adds go arch flags for building ocs-operator. This will be helpful when the ocs-operator is getting compiled from environments other than linux.
=> enhance: Adds go arch flags for building ocs-operator.

openshift-ci/Dockerfile.tools
Openshift release executes the tools container with a randomized uid
that defaults to the root group. The tools container did not have
the proper group permissions set on the GOPATH directory which
causes builds to fail.
Related to: https://github.com/openshift/release/pull/5178
=> Fixes openshift-ci tools container group GOPATH dir permissions

pkg/apis/ocs/v1/storagecluster_types.go
Since portable OSDs create problems in combination with failureDomain=host,
and failureDomain=host is currently the only way we are setting failureDomain,
this patch disables OSD portability.
This is an alternative proposal to #172. PR #150 will revert this.
=> Temporarily set StorageClassDeviceSet.portable to false

hack/common.sh, hack/red-hat-storage-ocs-ci-tests.sh, openshift-ci/Dockerfile.tools
The latest attempt to run `make red-hat-storage-ocs-ci` Openshift CI in prow revealed an issue with the randomized uid Openshift CI uses when executing the e2e test. ocs-ci expects an entry in /etc/passwd to exist for the user, but since the user is random there is no entry.
To address this, this PR dynamically updates the /etc/passwd file when we detect Openshift CI is executing ocs-ci tests.  I also made the ocs-ci related ENV VARS dynamic so I can alter those variables in the prow config in order to test out different ocs-ci source versions. 
**Changes** 
* adds /etc/passwd permissions to Dockerfile.tools
* makes ocs-ci environment variables dynamic
=> Add openshift ci build root container /etc/passwd permissions

hack/source-manifests.sh
This allows us to have visibility into what the container's dumping CSV contents are actually dumping which will help when debugging errors. 
Addresses comment by @b-ranto [here](https://github.com/openshift/ocs-operator/pull/180#discussion_r330888592)
=> Dump stdout of source containers when executing source-manifests.sh for CSV gen

functests/setup_teardown.go, hack/cluster-clean.sh, hack/common.sh, pkg/deploy-manager/subscription.go, tools/cluster-deploy/cluster-deploy.go
The setup time in `make cluster-deploy` has been improved by waiting to post the ocs subscription until after the catalog source is available. This improves the response time for how quickly the olm process the subscription.
The `make cluster-clean` script now completely removes everything related to `make cluster-up` by clearing the cephcluster finalizers and forcing all resources to be terminated.
=> Improve `make cluster-deploy` and `make cluster-clean`

hack/generate-unified-csv.sh, tools/csv-merger/csv-merger.go
The skip range feature is described here,  https://github.com/operator-framework/operator-lifecycle-manager/blob/98c24d9/doc/design/how-to-update-operators.md#skiprange
We need the ability to set the skipRange option on the CSV during csv generation in order to update across multiple patch level releases.
=> Add skip-range option to csv generation

pkg/deploy-manager/storagecluster.go
We've see ocs-ci failing occasionally due to issues related to unexpected pods and pvcs being left around after tests execute. 
Two sources of these errors have been identified and they are related to `make cluster-deploy` not ensuring some resources are online before marking the deployment as being completed. The result is that some additional objects come online during the ocs-ci test suite run, which causes the ocs-ci test suite to complain about unexpected objects being left over after tests.
To address this, the PR does the following. 
- Ensure noobaa core comes online during cluster-deploy
- Ensure canary pods come online during cluster-deploy
=> Stabilization fixes for `make red-hat-storage-ocs-ci`

must-gather/collection-scripts/gather_noobaa_resources
This commit fixes bash syntax error in noobaa gather script.
=> fix(must-gather): fix syntax error for noobaa gather script

hack/cluster-clean.sh
updated  hack/cluster-clean.sh not to delete PVs, but only PVCs when ` make ocs-operator` is executed
=> updated  hack/cluster-clean.sh not to delete PVs, but only PVCs

must-gather/collection-scripts/gather_ceph_resources
This commit adds a safe replace function for sed operations which can be used for for replacing keywords from files safely.
=> fix(must-gather): Adds a safe replace function for sed

must-gather/collection-scripts/gather_ceph_resources
This commit adds a safe replace function for sed operations which can be used for for replacing keywords from files safely.
Backport of PR https://github.com/openshift/ocs-operator/pull/228.
=> Bug 1757863: most must_gather_commands files with output of ceph commands are empty 

must-gather/Dockerfile, must-gather/collection-scripts/gather_ceph_resources
-> This PR changes the sed delimiter to \001 which is less probable to occur in the ceph config.
-> This PR changes base image version of ocs-must-gather to 4.2.0 as 4.2 image is not coming with the must-gather 4.2 cli which breaks upstream build.
=> enhance(must-gather): This PR changes sed delimiter and also the must-gather base image to 4.2.0

pkg/deploy-manager/storagecluster.go
This is meant to unblock CI on our m4.xlarge aws machines.
=> Set small mem request for osds in our ci storagecluster

deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, hack/latest-csv-checksum.md5, tools/csv-merger/csv-merger.go
This will allow the operator to be installed only in a
single namespace as MultiNamespace is also disabled.
=> disables InstallMode: AllNamespaces

must-gather/Dockerfile, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_noobaa_resources
Signed-off-by: ashishranjan738 <aranjan@redhat.com>
This commit refactors the gather scripts to `oc adm inspect` command for
collecting the resources as `openshift-must-gather inspect` is getting depricated.
=> refactor(must-gather): Make use oc adm inspect

hack/dump-debug-info.sh
Makes it easier to debug the issue when failures are noobaa related.
=> Dumping noobaa objects to debug info

pkg/controller/storagecluster/initialization_reconciler.go
The Store was being set to StorageCluster.Name instead of the name of
the CephObjectStore that is created.
Signed-off-by: Kaushal M <kshlmster@gmail.com>
=> Bug 1767408: storagecluster: Set correct Store for CephObjectStoreUser

pkg/controller/storagecluster/initialization_reconciler.go
By omission, only the data pool(s) had received the configured failure
domain. This patch adds the same failure domain to the metadata pool.
=> storagecluster: give the cephfs metadata pool the right failureDomain

pkg/controller/storagecluster/initialization_reconciler.go
=> Bug 1763070: give cephfs metadata pool the right failure domain

pkg/controller/defaults/resources.go, pkg/controller/storagecluster/reconcile.go
This change increases the memory limit for OSDs to 8GiB
and sets the memory usage cgroup limit for OSDs to 0.5.
Co-authored-by: Jose A. Rivera <jarrpa@redhat.com>
Signed-off-by: Elise Gafford <egafford@redhat.com>
=> Set OSD memory limits and add config map

pkg/controller/defaults/resources.go, pkg/controller/storagecluster/reconcile.go
This change increases the memory limit for OSDs to 8GiB
and sets the memory usage cgroup limit for OSDs to 0.5.
Co-authored-by: Jose A. Rivera <jarrpa@redhat.com>
Signed-off-by: Elise Gafford <egafford@redhat.com>
=> Bug 1765550: Set OSD memory limits and add config map

deploy/deploy-with-olm.yaml, pkg/deploy-manager/subscription.go
We don't need to setup local-storage-operator as it should
be already a part of OperatorHub and ocs-operator will pull it as a dependency.
Signed-off-by: Petr Balogh <pbalogh@redhat.com>
=> Remove local-storage from deploy-with-olm.yaml

hack/dump-debug-info.sh
The ocs-must-gather logs and files will be collected whenever a e2e test
job fails (functest/red-hat-storage-ocs-ci). They will be added to the
artifacts of the prow job and be accessible from the job status page.
=> tests: Capture ocs-must-gather on e2e failures

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
This hopefully helps fix the failures in long running, idle clusters.
=> storagecluster: Append "-rook-ceph" to name of created CephCluster

must-gather/collection-scripts/gather_ceph_resources
This commit add support to skip NotReady nodes for collecting prepare volume pod logs as those logs will not be available when node is NotReady state.
Backport of PR https://github.com/openshift/ocs-operator/pull/280
=> Bug 1770199: must-gather fails to collect OCS logs when a node is down

must-gather/collection-scripts/gather_ceph_resources
This commit add support to skip NotReady nodes for collecting prepare volume pod logs as those logs will not be available when node is NotReady state.
=> enhance(must-gather): Adds logic to skip NotReady Nodes

hack/dump-debug-info.sh, must-gather/Dockerfile, must-gather/collection-scripts/gather_ceph_resources, must-gather/templates/ceph.conf.template, must-gather/templates/keyring.template, must-gather/templates/pod.template
This backports PRs #257, #278, and #294 to the release-4.2 branch.
We need these to unbreak CI.
=> Bug 1771402: backport must-gather fixes

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
This change ensures that if a cluster has already been assigned the
rack failure domain in previous reconcile loops, it will continue
to use that failure domain.
Signed-off-by: Elise Gafford <egafford@redhat.com>
=> Bug 1772196: Preserve rack FailureDomain if previously assigned

pkg/controller/storagecluster/reconcile.go
This commit fixes the panic of the ocs-operator when running in an vmware based ocp cluster. The operator crashes because its not able to assign a valid rack to the nodes as nodes in vmware based ocp cluster doesn't have any valid topology keys (https://github.com/openshift/ocs-operator/blob/master/pkg/controller/storagecluster/reconcile.go#L46-L50). So the current work around is to assign a rack with min number of nodes to the new node if the operator is not able to find a valid rack based on the topology key checks(https://github.com/openshift/ocs-operator/blob/master/pkg/controller/storagecluster/reconcile.go#L498-L530).
=> fix(ocs-operator): Fixes panic of ocs-operator when running vmware

pkg/controller/storagecluster/reconcile.go
This commit fixes the panic of the ocs-operator when running in an vmware based ocp cluster. The operator crashes because its not able to assign a valid rack to the nodes as nodes in vmware based ocp cluster doesn't have any valid topology keys (https://github.com/openshift/ocs-operator/blob/master/pkg/controller/storagecluster/reconcile.go#L46-L50).So the current work around is to assign a rack with min number of nodes to the new node if the operator is not able to find a valid rack based on the topology key checks(https://github.com/openshift/ocs-operator/blob/master/pkg/controller/storagecluster/reconcile.go#L498-L530).
=> Bug 1769596: Fixes panic of ocs-operator when running vmware

pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/initialization_reconciler_test.go
The StorageClass resources are non-namespaced resources, and had their
ownerRefs set to the StorageCluster resource which is a namespaced
resource in the openshift-storage namespace. Having this sort of
cross-namespace ownerRefs, could cause the other children of the
StorageCluster to be inadverdently deleted by the GC. Ref [1][1].
Removing the ownerRefs on the StorageClass objects avoids this.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1691546
=> storagecluster: Do not set ownerRefs for StorageClasses

pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/initialization_reconciler_test.go
The StorageClass resources are non-namespaced resources, and had their
ownerRefs set to the StorageCluster resource which is a namespaced
resource in the openshift-storage namespace. Having this sort of
cross-namespace ownerRefs, could cause the other children of the
StorageCluster to be inadverdently deleted by the GC. Ref [1][1].
Removing the ownerRefs on the StorageClass objects avoids this.
Backport of #314.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1691546
=> Bug 1755623: storagecluster: Do not set ownerRefs for StorageClasses

functests/cluster_upgrade_test.go, go.mod, go.sum
- Upgrade Tests is marked as pending to ignore the tests safely.
This is to unblock CI tests which are failing at Upgrade.
=> makes UpgradeTests as Pending

must-gather/collection-scripts/gather
This commit modifies must-gather to remove collection of empty files and directories from the dump collected.
BackPort of PR: https://github.com/openshift/ocs-operator/pull/322
=> Bug 1766646: must-gather: some current.log files remains empty

deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, hack/latest-csv-checksum.md5, tools/csv-merger/csv-merger.go
Mark all but StorageCluster, BackingStore, and BucketClass cards internal. These three should be exposed to the user/admin.
Backports #293 and #313 .
=> Bug 1774927: backing store and bucket class cards shouldn't be internal

must-gather/collection-scripts/gather_ceph_resources
This commit fixes must-gather collection scripts to collect CLBO pod logs which were earlier getting missed.
=> fix(must-gather): updates collection script to collect CLBO pod logs

must-gather/collection-scripts/gather_ceph_resources
This commit fixes must-gather collection scripts to collect CLBO pod logs which were earlier getting missed.
backport of #324
=> Bug 1770941: updates collection script to collect CLBO pod logs

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_noobaa_resources
This commit adds timeouts to `oc` invokes which makes sure that must-gather is not stuck due to network failure and improves logging of the must-gather.
=> enhance(must-gather): adds timeout and improves logging

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_noobaa_resources
This commit adds timeouts to `oc` invokes which makes sure that must-gather is not stuck due to network failure and improves logging of the must-gather.
BackPort of PR #327
=> Bug 1775567: must-gather stuck at "Collecting operator pod logs"

pkg/controller/defaults/resources.go
This change changes the resources for the 'rgw' pod from 1 CPU / 2Gi memory to 2 CPUs / 4Gi memory.
solves https://github.com/openshift/ocs-operator/issues/334
=> Add more resources to RGW #334

go.mod, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_noobaa_resources
This commit updates must-gather to redirect unwanted logs must-gather script to a gather-debug.logs file. This reduces the verbosity of must-gather and preserves debugging logs of ocs-must-gather.
Fixes https://github.com/openshift/ocs-operator/issues/330
=> enhance(must-gather): updates scripts to collect logs in a debug.log

hack/functest.sh
Since the must-gather func-test is already called from the go test code we
don't need a seperate call for it from the functest.sh file.
=> fix(functest): fixes duplicate call for must-gather functest.

hack/source-manifests.sh
This fixes the broken make file commands, like 'gen-latest-csv',
'source-manifests' etc
Fixes: https://github.com/openshift/ocs-operator/issues/377
=> Fixing the source-manifests.sh script

hack/generate-latest-csv.sh
Minor change to make 'generate-latest-csv' script align with other 'make' scripts and avoids the usage of a new variable. Helps in building custom OCS Operator images.
Signed-off-by: Arun Kumar Mohan <arun.iiird@gmail.com>
=> Align 'generate-latest-csv' script with existing env variables

functests/setup_teardown.go, go.mod, go.sum, pkg/deploy-manager/common.go, pkg/deploy-manager/config.go, pkg/deploy-manager/storagecluster.go
This commit fixes teardown failure in CI by adding an additional step to clean up storageCluster before deleting the namespace.
=> fix: tear down failure in CI

pkg/deploy-manager/common.go
This commit increases the timeout for cluster teardown because pods are taking more than 200 seconds to terminate which causes teardown to get a timeout.
=> functest: increases the timeout for cluster teardown

pkg/controller/storagecluster/reconcile.go
"rook-config-override" ConfigMap after changes,
```yaml
data:
config: |
[global]
mon_osd_full_ratio = .85
mon_osd_nearfull_ratio = .75
[osd]
osd_memory_target_cgroup_limit_ratio = 0.5
```
```bash
sh-4.2# ceph osd dump | grep full
full_ratio 0.85
nearfull_ratio 0.75
```
=> Bug 1775432- sets mon_osd_full_ratio=.85 & mon_osd_nearfull_ratio =.75

pkg/controller/defaults/placements.go, pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/initialization_reconciler_test.go, pkg/controller/storagecluster/reconcile.go
More than one mon or mds pods are randomly coming up on the same Availability Zone. 
This PR adds `topologyKey: failure-domain.beta.kubernetes.io/zone` podAntiAffinity to Mon and MDS placement spec.
=> BZ-1788492: Adding pod anti affinity for zones on mon and mds pods

pkg/controller/storagecluster/reconcile.go
In PR https://github.com/openshift/ocs-operator/pull/413
'mon_osd_full_ratio' & 'mon_osd_nearfull_ratio' were changed to '.85' and '.75' respectively.
But, mon_osd_backfillfull_ratio is still set to default '.9'.
In Ceph 4.x, OSD_OUT_OF_ORDER_FULL error will be shown in cluster if the following criteria are not met.
"nearfull < backfillfull, backfillfull < full, and full < failsafe_full"
Signed-off-by: Ashish Singh <assingh@redhat.com>
=> set mon_osd_backfillfull_ratio=.8

must-gather/Dockerfile, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources
This commit updates the must-gather docker file to use origin-cli image
as base image. This also allows us to remove temporary fixes for
collecting logs of non-running pods as this is fixed in latest version of 
oc client.
=> Updates the must-gather Docker file to use origin-cli image

must-gather/collection-scripts/gather
This commit adds a temporary fix for collection storagecluster CR as
collection via inspect client is not working.
=> Adds temporary fix for collection storagecluster

pkg/controller/storagecluster/initialization_reconciler.go
Currently, due to a floating point imprecision in ceph, we get a
"HEALTH_WARN 1 subtrees have overcommitted pool target_size_ratio"
after deplyoing with the TargetSizeRatio of .5 (0.5 + 0.5 > 1.0..).
This will be fixed in future Ceph versions
(https://github.com/ceph/ceph/pull/33035).
In order to avoid the warning until we have the updated Ceph,
this patch lowers the ratio to 0.49.
https://bugzilla.redhat.com/show_bug.cgi?id=1807950
=> Reduce TargetSizeRatio from .5 to .49 to avoid HEALTH_WARN

functests/common.go, functests/data_validation_test.go
Changed common.go file to add the pod Busybox specs into the file. 
~ ~ ~
[ The main purpose of adding pod specs in common.go  : 
Writing a test case in which a busybox pod will be deployed, PVC will be created. Once pod and pvc are created, the file will be generated in the busybox pod, after copying the generated file to the mount point, md5 of both the files will be calculated. Cross checking md5 will be helpful to know if the data populated is corrupted or not.]
=> Adding Testcase to check accuracy of the data

pkg/controller/storagecluster/initialization_reconciler.go
AllowVolumeExpansion is set to False to disable expansion of OCS backed Volumes.
This is not supported currently. User created OCS backed StorageClass will not inherit this change.
=> disable volume expansion for OCS PV

pkg/controller/storagecluster/initialization_reconciler.go
AllowVolumeExpansion is set to False to disable expansion of OCS backed Volumes
This is not supported currently. User created OCS backed StorageClass will not
inherit this change.
=> Bug 1810011: PV resize should be blocked in OCS 4.3

must-gather/OWNERS
This commit adds crombus as the owner of the must-gather.
=> Adds crombus to the owner file.

hack/common.sh
correcting IMAGE_RUN_CMD to use IMAGE_BUILD_CMD. This allows
flexibility in using any build tool (e.g docker, podman).
=> remove hardcoded IMAGE_RUN_CMD in common.sh

openshift-ci/Dockerfile.registry.build
removes reference to registry.svc.ci.openshift.org which requires
CI to push it's image to external image registry. Instead, we use
default route to openshift image registry exposed in the CI cluster.
It does not require pushing image to external registry.
=> dockerfile: removes hardcoded image registry link

go.sum, pkg/controller/defaults/defaults.go
Disabling because consensus seems to be that MONs should not be scaled this way, and we are still determining what factors should drive the count.
=> Disable automatic mon resizing.

pkg/controller/storagecluster/reconcile.go
This is the new CephCluster CR that needs to be injected:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
name: openshift-storage-external->>namespace can be changed according to the requirement
namespace: openshift-storage-external
spec:
external:
enable: true
crashCollector:
disable: true
```
=> Changes in the Ceph Cluster CR for external cluster

pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/platform_detection.go
https://bugzilla.redhat.com/show_bug.cgi?id=1825994
=> Add new platform GCP and AZURE

Makefile
removing the CSV check from ocs-operator-ci test target
to remove dev overhead of maintaining CSV even for
unrelated changes.
=> removes CSV check from CI test target

openshift-ci/Dockerfile.tools
go1.13.3 with GO111MODULE=on is required for builds & tests
to be successful in CI
=> updates build-tools to install go1.13.3

must-gather/collection-scripts/gather
In must-gather logs, file-names containing the output of 'oc' commands have space char, which makes analyzing difficult through shell prompt. 
Use underscore (_) char in oc command output file-names, similar to what we have for the ceph commands.
Fixes BZ #1828714
Signed-off-by: Ashish Singh <assingh@redhat.com>
=> Use _ (underscore) instead of space char in oc command output filenames

pkg/controller/ocsinitialization/ocsinitialization_controller.go
The operator SCCs should be verified at every reconcile, not just
created once.
=> Always reconcile operator SCCs

hack/common.sh
You can still override the command using IMAGE_BUILD_CMD environment variable.
If it's not set, it tries to look for the docker command.
If it's not available, it'll try to use podman.
Tested 'make' on Fedora 32, without Docker.
Signed-off-by: Yaniv Kaul <ykaul@redhat.com>
=> If Docker is not found, use podman to build the containers.

pkg/deploy-manager/storagecluster.go
This is to fill the required fields expected by rook to create
OSDs on PVC.
Temporary fix until we have a new Rook release that contains the fix.
=> [hotfix CI] pass the pvc name as expected by rook to StorageCluster

pkg/controller/storagecluster/reconcile.go
This PR prevents running osd from being marked out if running osd id is
provided to the osd removal job template.
=> Avoid running osd being marked out

functests/setup_teardown.go, hack/dump-debug-info.sh, hack/functest.sh
OCP must-gather is much needed for debugging issues related to Install/Upgrade.
=> adds OCP must-gather to tests

deploy/crds/ocs.openshift.io_ocsinitializations_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/olm-catalog/ocs-operator/manifests/ocsinitialization.crd.yaml, hack/latest-csv-checksum.md5, pkg/apis/ocs/v1/ocsinitialization_types.go, pkg/controller/ocsinitialization/ocsinitialization_controller.go, pkg/controller/ocsinitialization/ocsinitialization_controller_test.go
Creating a rook-ceph-operator-config ConfigMap with default
operator configs which is picked up by rook. We do not
update this ConfigMap and is left upto the admin. To reset
to defaults, configmap must be deleted and reconcile must
be retriggered by deleting ocsinit object.
=> creates default rook-ceph-operator-config ConfigMap

pkg/controller/defaults/resources.go, pkg/controller/storagecluster/noobaa_system_reconciler.go, pkg/deploy-manager/storagecluster.go
A NooBaa CR can describe memory and CPU resource management (requests/limits) for deployed NooBaa endpoints.
This PR exposes these options in the StorageCluster CR and add reconcile code to update the NooBaa CR accordingly  
Fixes #403
=> Expose noobaa endpoint resource management to OCS operator

pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/initialization_reconciler_test.go
When deploying an external Rook-Ceph cluster, the OCS-operator does not
deploy an CephObjectStore CR, this means the StorageClass parameter
`objectStoreName` becomes invalid. We must remove it otherwise, the user
creation on OBC will fail.
=> fix: OBC StorageClass for external cluster

pkg/controller/storagecluster/initialization_reconciler.go
These params in SC are required when we want to expand RBD or CephFS volumes.
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
=> Add controller-expand-secret and namespace to SC

go.mod, go.sum, vendor/modules.txt
The openshift/api project deleted their tags at some point, because of
which we get the following error for go commands:
```
go:
github.com/openshift/api@v3.9.1-0.20190924102528-32369d4db2ad+incompatible:
invalid pseudo-version: preceding tag (v3.9.0) not found
```
There is at least one more project which is referencing the tag(Noobaa)
which makes it harder to change the require line right now. Therefore, I
have modified the requirement through a replace line.
For more information refer to
https://github.com/openshift/api/issues/456
=> go.mod: replace non-existent tag

Makefile
Whenever go.mod is changed, it is required that deps-update is run.
Change the Makefile to make it automatic.
=> Makefile: run deps-update when go.mod changes

Makefile
The `all` target is not executed when only `make` is invoked because of the include and call directives before it. This moves the all target above the includes so that it is the first target.
=> Makefile: let `make` do the same as `make all`

Makefile
The PHONY list was missing a backslash escaping a newline,
thereby not making all intended targets phony...
=> Makefile: fix typo in PHONY list

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/uninstall_reconciler.go
At the time of installation, storageclasses are created for ceph-rbd and cephfs. We remove the same in the uninstall stage.
Failure to delete them is not considered fatal and does not block the uninstallation.
=> Delete the storageclasses during uninstall

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/uninstall_reconciler.go
This PR removes the default node affinity labels from the worker nodes when the StorageCluster is deleted.
If the StorageCluster spec provided a list of node selector labels or expressions, we don't remove them because a subset of them might be used by the user for other services    too.
=> StorageCluster: delete the default node selector labels during uninstall

pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/initialization_reconciler_test.go, pkg/controller/storagecluster/platform_detection.go
when these cloud provider are used then default backing store should be used instead of rgw.
=> Disable CephObjectStore when the cloud provider is Azure and gcp.

pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/reconcile.go
Moved the logic related to ```CephCluster``` to a new file in the same package.
Signed-off-by: Anubhav Deep <adeep@redhat.com>
=> Refactor: Moving the logic for modifying/creating CephCluster

pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/noobaa_system_reconciler.go, pkg/controller/storagecluster/noobaa_system_reconciler_test.go
When doing indepenent mode, we must instruct Noobaa where to find the
external Ceph rgw endpointhen we fetch the externalClusterDetailsSecret
Secret, we extract the Rgw StorageClass as well as its parameters.
Currently, we only have a single parameter called "endpoint", which is
used to configure OBC.
Now we also expose that endpoint as a label on the Nooba CR so Noobaa
can determine whether the endpoint is external or not.
=> independent mode: expose rgw endpoint as a label

pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/noobaa_system_reconciler_test.go
Since labels value cannot contain any `:` when Noobaa reads it when an
error like:
```
Error while reconciling: NooBaa.noobaa.io "noobaa" is invalid:
metadata.labels: Invalid value: "10.70.56.202:8080":
a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.',
and must start and end with an alphanumeric character
(e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```
So let's encode the endpoint and decode it later with Nooba.
=> encore rgw endpoint for external mode

pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/noobaa_system_reconciler.go, pkg/controller/storagecluster/noobaa_system_reconciler_test.go
=> Bug 1847875: [release-4.5] independent mode: expose rgw endpoint as a label

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/uninstall_reconciler.go
This is a cherry-pick of #558 .
To be merged after
#575 and #574
=> Bug 1849105: [release-4.5] StorageCluster: delete the default node selector labels during uninstall

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/uninstall_reconciler.go
This is a cherry-pick of #560 
To be merged after
#575 
#574 
#576
=> Bug 1849105: [release-4.5] StorageCluster: remove node taints during uninstall

pkg/controller/ocsinitialization/sccs.go
Changing the priority leads to unexpected behaviour - so partially reverting
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1851697
CI Failure issue: https://bugzilla.redhat.com/show_bug.cgi?id=1850148
Signed-off-by: jackyalbo jalbo@redhat.com
=> Reverting Noobaa's SCC priority

pkg/controller/storagecluster/initialization_reconciler.go
Backport PR for commit [6e22082](https://github.com/openshift/ocs-operator/pull/590/commits/6e22082cff3cf7b364f9653191c0fb4794d5e5c6)
Backport of PR #590 
=> Bug 1846085: [release-4.5] Updates don't work on StorageClass

pkg/controller/storagecluster/reconcile.go
This change will remove the host associated with the failed osd from the
crush map. When node removal process is done and all OSDs have been
removed from that host, the empty host will be removed from crush map.
The user will be notified that the error while removing host should be
ignored if there are other OSDs present on the same host
=> Bug 1840539: [release 4.5] Remove the host from the crush map

pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/noobaa_system_reconciler_test.go
Instead, let's use plain but replace the colon with an underscore.
Otherwise setting the label will fail with:
```
message: 'Error while reconciling: NooBaa.noobaa.io "noobaa" is invalid: metadata.labels:
Invalid value: "MTAuMS44LjQxOjgwODA=": a valid label must be an empty string
or consist of alphanumeric characters, ''-'', ''_'' or ''.'', and must start
and end with an alphanumeric character (e.g. ''MyValue'',  or ''my_value'',  or
''12345'', regex used for validation is ''(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'')'
reason: ReconcileFailed
```
Fixes the issue caused by: #580 
Corresponding Noobaa PR: https://github.com/noobaa/noobaa-operator/pull/360
=> do not encode rgw label endpoint

pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/placement.go, pkg/controller/storagecluster/placement_test.go, pkg/controller/storagecluster/storagecluster_controller_test.go
The value of StorageCluster.Spec.LabelSelector was not being properly
appended to the generated Placements of the OCS components.
Specifically, adding a new NodeSelectorTerm results in a selector term that
is ORed with any other terms, whereas adding a new
NodeSelectorRequirement to an existing NodeSelectorTerm would result in
an AND of all requirements in that term. This commit makes it so the
LabelSelector field is ANDed with any other existing node selectors in
the Placement, properly omitting a selector if an empty LabelSelector is
specified.
=> Properly append LabelSelector

pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/placement.go, pkg/controller/storagecluster/placement_test.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
This backports PR #618 (and as prerequisite also the innocuous pr #567).
This is needed to fix a nil pointer dereference segfault in `newStorageClassDeviceSets` when an empty LabelSelector was provided in the StorageCluster CR.
See https://bugzilla.redhat.com/show_bug.cgi?id=1854651
=> Bug 1854651: [release 4.5] backport pr 618 - fix segfault

pkg/controller/util/status.go
The MapExternalCephClusterNegativeConditions erroneously interpreted the
CephClusterConnected state as bad and set Degraded state because of the
default case. Removing the default case to let all not explicitly
mentioned status fall through.
https://bugzilla.redhat.com/show_bug.cgi?id=1848387
=> external cluster: Fix propagation of connected status

pkg/controller/storagecluster/reconcile.go
PR #563 sneaked in some whitespace changes and both messed up the commits a bit and removed too many white spaces (removed intentation and not only superfluous trailing spaces). 
This makes backporting of patches in this area difficult.
This PR first undoes the changes (on top of PR #589) and then adds only the intended trailing whitespace patch separately on top. So if we need to backport more patches in this area in the future, we can just pick the top patch first and have clean cherry-picks.
=> Undo and cleanly redo whitespace changes included in #563

hack/build-must-gather.sh, hack/build-operator-index.sh, hack/build-operator.sh, hack/common.sh, hack/ensure-operator-sdk.sh, hack/generate-appregistry.sh, hack/generate-k8s-openapi.sh, hack/generate-latest-csv.sh, hack/operator-sdk-common.sh, hack/red-hat-storage-ocs-ci-tests.sh, hack/shellcheck-test.sh, hack/source-manifests.sh, hack/verify-operator-bundle.sh, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources
I was recently wondering why I am spotting obvious shellcheck errors in scripts but didn't see CI / test failures. Now looking into the shellcheck-test script, I realized that the return code from shellcheck was not properly interpreted, and all errors went without notice.
This PR fixes this and allows the shellcheck-test to fail. In order to be able to push this, the PR first fixes all shellcheck errors in scripts that have accumulated (12 scripts are fixed). Additionally, the hack/common.sh script is not skipped any more, but just disables the unused variable test.
Finally, a few additional aspects of the shellcheck-test script are improved: the dependency on GOPATH is removed (which is not required to be set for our module based code), so that one can run this without GOPATH set. And …
=> Shellcheck cleanup - make shellcheck actually run and fail

hack/source-manifests.sh
shellcheck fix was incorrect for "$gen_args" here.
=> source-manifests: fix csv generation

must-gather/collection-scripts/gather
Quoting the command was resulting in:
Error: unknown command "get csv -n openshift-storage" for "oc"
disabled this because we want word splitting here:
```
SC2086: Double quote to prevent globbing and word splitting.
```
Looks like rebase is not necessary (4.5 branch): https://github.com/openshift/ocs-operator/blob/release-4.5/must-gather/collection-scripts/gather#L53
=> Fix incorrect quoting of must-gather commands

pkg/controller/ocsinitialization/ocsinitialization_controller.go
A recent Rook refactor renamed the keys that are used for ceph operations, which was an internal implementation detail except for the toolbox which consumes these keys.
Signed-off-by: Travis Nielsen <tnielsen@redhat.com>
=> Bug 1860034: Toolbox updated to point to the renamed secret keys

must-gather/collection-scripts/gather_ceph_resources
SC2129: Consider using { cmd1; cmd2; } >> file instead of individual
redirects.
Just disable this for this instance.
This must have been uncovered by using a newer shellcheck version.
=> must-gather: fix newly uncovered shellcheck error

deploy/olm-catalog/ocs-operator/manifests/backingstore.crd.yaml, deploy/olm-catalog/ocs-operator/manifests/noobaa.crd.yaml
runs `make gen-latest-csv` to updated BackingStore and NooBaa CRDs
with the latest v2.3.0 api spec of NooBaa Operator.
+ removes `secret` from required (as seen in https://github.com/noobaa/noobaa-operator/blob/2.3/deploy/crds/noobaa.io_backingstores_crd.yaml#L206-L209)
+ adds `CleanupPolicy` (as seen in https://github.com/noobaa/noobaa-operator/blob/2.3/deploy/crds/noobaa.io_noobaas_crd.yaml#L628-L635)
=> updates BackingStore and NooBaa CRDs

Makefile, deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml, hack/latest-csv-checksum.md5
Updates some of the changes done by https://github.com/openshift/ocs-operator/pull/509/commits/cc7b4ca30a2b73493d3966299aa97956f94d52c0
v0.2.5 adds support for `x-kubernetes-int-or-string` type as needed by `resource.limit`.
=> use controller-gen v0.2.5 to fix validations for int-or-string types

pkg/controller/storagecluster/reconcile.go
Added || true to the end of the command. If the command ceph osd crush rm
gives output with error message, the script will abort
and the job would fail. This change ensures that the script doesn't
abort and the job runs without a failure.
=> Added the pattern to the end of the command

pkg/controller/storagecluster/cephcluster_test.go
Instead of explicitly writing each test case within a function, it is reorganized to follow a table driven approach. The refactoring is done for `cephClusterCreate, cephClusterUpdate,cephClusterWithNoConditions, cephClusterWithNegativeConditions`
=> Refactored cephcluster_tests.go

pkg/controller/ocsinitialization/ocsinitialization_controller.go
as the CSI log level is set to `0` by default no debug and info logs will be printed it will be
hard to debug csi. This commit sets the csi log level as "5".
=> Add csi log level to rook-ceph-operator-config configmap

pkg/controller/storagecluster/reconcile.go
Added || true to the end of the command. If the command ceph osd crush rm
gives output with error message, the script will abort
and the job would fail. This change ensures that the script doesn't
abort and the job runs without a failure.
=> Bug 1840539: [release 4.5] Added the pattern to the end of the command

pkg/controller/storagecluster/noobaa_system_reconciler.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/uninstall_reconciler.go
Until now, the cephCluster was being deleted simultaneously with the
storageCluster as the storageCluster has the owner refernce for the
cephCluster.
With this commit, we perform the deletion of the cephCluster in order.
=> StorageCluster: perform delete of cephCluster

deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/generate-latest-csv.sh
The service account names were being generated incorrectly in v1.4.0. Now the service account names are generated correctly in the latest tag.
=> Update to newer rook/ceph:v1.4 tag to pick up csv fix

pkg/controller/storagecluster/cephblockpools_test.go, pkg/controller/storagecluster/cephfilesystem_test.go, pkg/controller/storagecluster/cephobjectstores_test.go, pkg/controller/storagecluster/cephobjectstoreusers_test.go, pkg/controller/storagecluster/external_resources_test.go, pkg/controller/storagecluster/initialization_reconciler_test.go, pkg/controller/storagecluster/storageclasses_test.go
Splits the file into several test files for each resource (cephblockpools, cephfs etc..)
Depends on https://github.com/openshift/ocs-operator/pull/592/
Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>
=> Refactor: initialization_reconciler_test.go

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/topology.go
Taking out the node topology, racks and failure domain logic to a
separate file. Thus cleaning up some more clutter from 'reconcile.go'
file.
=> Separating node topology, racks and failure domains logic

build/Dockerfile.build, hack/build-container.sh
Uses multi-stage build to minimize image size.
ubi8/go-toolset is used as builder image to build ocs-operator
and copy it into final image with ubi8/ubi-minimal as base.
Final image will be around 170MB in comparison to previous 2GB+.
=> enhances containerized build

cmd/manager/main.go
+ the logger was misconfigured due to which stacktrace was
thrown for Warning Level logs in Production and
Error Level in Development environment.
This also reduces the frequency of logs to log first 3 similar
messages and every 10th message after that.
+ adding development boolean flag to ocs-operator.
Defaults to "false". Running ocs-operator with
"--development" flag logs error for development
purposes i.e. stacktrace is given for logs starting
at Warning level.
=> Fix logger instantiation

deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
adding API whitelist to populate internal-objects.
This allows us to hide any API that we do not want to expose
to user without having to append individual APIs to the
internal objects list. Instead we add APIs that we want to
expose and the rest is automatically hidden.
=> Whitelist instead of Blacklist to hide internal objects

pkg/controller/storagecluster/reconcile.go
Remove unwanted logs that gets generated in OCS operator, which makes looking into the logs a bit difficult.
=> Remove excess logs from OCS operator

pkg/controller/storagecluster/reconcile.go
Rook and Noobaa are now both defaulting to wait for removal of existing
PVCs and OBCs before deleting their operands. In cases where the admin
wants to enforce a forced cleanup, this label on the StorageCluster
should be set.
uninstall-mode.ocs.openshift.io="yes-really-uninstall-even-if-in-use"
Co-authored-by: Nitin Goyal <nigoyal@redhat.com>
=> StorageCluster: add uninstall mode

pkg/controller/storagecluster/reconcile.go
The default policy for uninstall mode is set to graceful and the default for the cleanup policy is set to delete.
These annotations are set only if the annotations are not already set on the StorageCluster. If set, even as an empty string, we don't make any changes.
=> StorageCluster: set uninstall defaults

pkg/controller/storagecluster/external_resources_test.go, pkg/controller/storagecluster/generate.go
In external mode we are already adding 'external' keyword with
storagecluster, so need to add it again with cephobjectstore name.
=> Fix CephObjectStore name exceeding 64 char length

pkg/controller/storagecluster/reconcile.go
We were not updating storagecluster before because of which changes were
not reflecting in the object. Update the storagecluster with
annotations.
Co-authored-by: Raghavendra Talur <raghavendra.talur@gmail.com>
=> StorageCluster: Update the storagecluster uninstall annotations

must-gather/collection-scripts/gather_clusterscoped_resources, must-gather/collection-scripts/gather_namespaced_resources
Recently, a couple of shellcheck errors were introduced in new must-gather scripts.
They currently go unnoticed in the PR-CI since the openshift ci seems to be unable to download stuff from the internet in the test runs (in this case, we want to download shellcheck..)
This fixes the existing shellcheck errors while figuring out ways to enable shellcheck in the ci, so that folks can run `make ocs-operator-ci` locally again...
=> Fix shellcheck errors

pkg/controller/storagecluster/external_resources.go, pkg/controller/storagecluster/external_resources_test.go, pkg/controller/storagecluster/noobaa_system_reconciler_test.go
Added an extra check to verify RGW endpoint passed,
in External cluster mode, is reachable or not.
=> Add a check to verify RGW endpoint is reachable or not

pkg/controller/storagecluster/reconcile.go
Set default Uninstall Annotations when found any unrecognized value
which does not match (UninstallModeGraceful and UninstallModeForced)
or (CleanupPolicyDelete and CleanupPolicyRetain)
Co-authored-by: Raghavendra Talur <raghavendra.talur@gmail.com>
=> StorageCluster: set default UninstallAnnotations

pkg/apis/ocs/v1/storagecluster_types.go, pkg/apis/ocs/v1/zz_generated.deepcopy.go, pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/storagecluster_controller_test.go
When Network was not specified in the storagecluster CR, the cluster
creation failed as it was checking for some value that was not defined.
Signed-off-by: rohan47 <rohgupta@redhat.com>
=> Fixed cluster failure when Netwok is not specified.

deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, pkg/apis/ocs/v1/storagecluster_types.go, pkg/controller/storagecluster/external_resources.go, pkg/controller/storagecluster/external_resources_test.go
Reconciling external cluster resources by adding a checksum on external secret data.
Whenever external secret data is changed a new checksum is generated, which is then compared with the previously generated checksum. Since they don't match, `ensure` function proceeds forward, thus updating the resources.
=> Reconcile external resources

Makefile, functests/common.go, functests/data_validation_test.go, functests/pvc_creation_test.go, functests/setup_teardown.go, hack/cluster-clean.sh, hack/common.sh, hack/dump-debug-info.sh, hack/functest.sh, openshift-ci/Dockerfile.registry.build, pkg/deploy-manager/common.go, pkg/deploy-manager/config.go, pkg/deploy-manager/subscription.go
There are several problems with the e2e-aws tests that have been preventing them from successfully running on PRs. This PR fixes all currently known problems. It includes some refactoring of the OCS uninstallation to deal with intermittent errors in the AfterSuite.
=> Fix and refactor failing e2e tests

pkg/controller/storagecluster/placement.go, pkg/controller/storagecluster/placement_test.go
Checking spec.placement length==0 is not required in case
a placement key is not found as there could be other keys
present. So it is enough to fallback to default irrespective
of length in cases where key is not found. Otherwise, it could
cause Nil Pointer Dereference error.
PodAntiAffinity can have many different combinations. This
commit takes it into account while determining placement for
certain components.
Fixes: Bug 1877582
=> fixed getPlacement() for custom placement configurations

deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml, pkg/apis/ocs/v1/storagecluster_types.go, pkg/apis/ocs/v1/zz_generated.deepcopy.go, pkg/controller/defaults/defaults.go, pkg/controller/defaults/placements.go, pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/cephcluster_test.go, pkg/controller/storagecluster/initialization_reconciler_test.go, pkg/controller/storagecluster/placement.go, pkg/controller/storagecluster/storagecluster_controller.go, pkg/controller/storagecluster/storagecluster_controller_test.go
**Description** 
This PR is about supporting Topology Spread Constraints (**Phase 1 changes**) that will allow OSDs to evenly distribute across the required topology domain.
Design : https://github.com/openshift/ocs-operator/pull/709
Signed-off-by: Kesavan Vellalore Thiruvenkadasamy kvellalo@redhat.com
=> Supporting OSD Topology Spread Constraints

pkg/controller/storagecluster/cephcluster.go
This PR is required to enable upgrades in external mode from 4.5 to 4.6 without any failure due to the requirement of monitoring info.
=> Bug 1881071:Made monitoring optional during external cluster initilization

pkg/controller/storagecluster/uninstall_reconciler.go
The logger requires that arguments be passed as key-value pairs.
=> StorageCluster: fix logging errors

build/Dockerfile, build/Dockerfile.build, hack/build-operator.sh, metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, openshift-ci/Dockerfile.deploy, pkg/controller/storagecluster/prometheus.go, pkg/controller/storagecluster/reconcile.go
This restores prometheus rules YAML deleted by  commit
5a4b96929585cd7ed9dd217dbe864884859c79f7 and uses it for deployment
instead of Go Structs. This helps in decoupling monitoring resources
from operator resources. Also, at later stage these files will be
generated dynamically and will be scalable.
**CI fix :** https://github.com/openshift/release/pull/11528
=> restores YAML manifests for Prometheus rules

must-gather/Dockerfile
Problem: Docker has a longstanding bug using globs in COPY directives
(i.e. COPY foo/dir/* /tmp/dir/ ).If the source files matched by the glob
include subdirectories, these subdirectories are not present in the destination.
Buildah - which is used to run builds in OCP 4.x - appears to utilise similar
logic when processing globs.
Solution: use of absolute path and use of simple dir structure.
=> must-gather: make Dockerfile compatible with docker and buildah

.gitignore, Makefile, hack/gen-promethues-rules.sh, metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/Makefile, metrics/mixin/README.md, metrics/mixin/alerts/alerts-external.libsonnet, metrics/mixin/alerts/alerts.libsonnet, metrics/mixin/alerts/services-external.libsonnet, metrics/mixin/alerts/services.libsonnet, metrics/mixin/build/external.jsonnet, metrics/mixin/build/internal.jsonnet, metrics/mixin/build/jsonnet/kube-prometheus-external.libsonnet, metrics/mixin/build/jsonnet/kube-prometheus.libsonnet, metrics/mixin/build/jsonnet/prometheus.libsonnet, metrics/mixin/build/jsonnetfile.json, metrics/mixin/build/jsonnetfile.lock.json, metrics/mixin/config.libsonnet, metrics/mixin/lib/alerts-external.jsonnet, metrics/mixin/lib/alerts.jsonnet, metrics/mixin/lib/rules.jsonnet, metrics/mixin/mixin-external.libsonnet, metrics/mixin/mixin.libsonnet, metrics/mixin/rules/rules.libsonnet
This PR adds a framework for generating OCS rules and alerts. 
This is a follow-up PR on #733, #737 and #739. This PR should clear up how OCS rules yamls are created and how they will be maintained in future.
Doc to install dependencies and use : metrics/mixin/README.md
=> Added the framework for the OCS rules and alerts

pkg/controller/storagecluster/reconcile.go
The storageCluster.status.failuredomain was empty causing
the cephblockpool.spec.failuredomain to be empty as well.
=> Set storagecluster.status.failuredomain

pkg/controller/storagecluster/uninstall_reconciler.go
deleteNodeTaint was getting called after deleteNodeAffinityKeyFromNodes
because of which deleteNodeTaint wont be able to find eligible nodes to
delete taint. Fix the same via changing the order of both calls
=> storagecluster: Fix order of func calls in deleteResources

pkg/controller/ocsinitialization/ocsinitialization_controller.go
Add a toleration to the rook-ceph-tools deployment to pods to run on OCS tainted nodes.
=> Allow the rook-ceph-tools pod to run on OCS tainted nodes.

must-gather/collection-scripts/gather_noobaa_resources, must-gather/templates/noobaa.template
Add noobaa cli to must-gather. gathering binary from noobaa operator pod. Running the noobaa commands by executing binary.
=>  must-gather: add noobaa cli to must-gather

must-gather/collection-scripts/gather
Skipping ceph collection when ocs is installed in external mode.
=> must-gather: skip ceph collection in external mode OCS

must-gather/collection-scripts/gather_ceph_resources
add command to check for ceph crash info
for every crash and collect core dump of
rook crash.
=> must-gather: add more info for ceph crash

pkg/controller/storagecluster/cephobjectstores.go
The purpose of the `target_size_ratio` is to configure the pool for some pre-optimization of pg placement when the autoscaler is active. If the `target-size-ratio` is set, then up to that threshold of capacity, the pre-optimization will be active. Above the threshold, it is changing the normal non-optimized mode.
This change sets the `target_size_ratio` for the RGW pool to `.49` like for the rbd pools and the cephfs data pool as recommended by ceph experts (starting with RHCS 4.1).
=> Add TargetSizeRatio of .49 to RGW data pool

must-gather/collection-scripts/gather_noobaa_resources
- Add creation of a `notificaiton.txt` file to the noobaa must-gather flow
- Add a notification for the situation where noobaa is deployed in the cluster but it is not managed by the storagecluster CR
=> noobaa must-gather - Add important notifications collection

pkg/controller/storagecluster/reconcile.go
Add ROOK_MON_ENDPOINTS, VolumeMounts, Volumes and other required fields in the OCS osd-purge job spec
to match the job spec with rook job https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/osd-purge.yaml
=> ceph: Add missing fields in osd purge job

pkg/controller/storagecluster/reconcile.go
A very minor change to enable `Snapshotter` feature in external cluster mode.
=> Enabling 'snapshotter' feature in external cluster mode

pkg/controller/storagecluster/reconcile.go
(cherry picked from commit 37fec692f039dad865a6e57f6decbc6fa85c37a6)
=> [release-4.6] Bug 1886308: Enabling 'snapshotter' feature in external cluster mode

pkg/controller/storagecluster/noobaa_system_reconciler.go, pkg/controller/storagecluster/uninstall_reconciler.go
Delete Noobaa resources only if they are being managed by
the OCS operator.
=> StorageCluster: Check MCG.Reconcile before deleting Noobaa resources

deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/role.yaml, pkg/controller/add_persistentvolume.go, pkg/controller/persistentvolume/persistentvolume_controller.go, pkg/controller/persistentvolume/persistentvolume_controller_test.go, pkg/controller/persistentvolume/reconcile.go, pkg/controller/persistentvolume/reconcile_test.go, pkg/controller/storagecluster/storagecluster_controller.go, pkg/controller/util/predicates.go, pkg/controller/util/predicates_test.go
This PR introduces a new controller for managing the volume attributes of Ceph-CSI PersistentVolumes. As part of the implementation, is also introduces the use of Predicate from the Kubernetes controller-runtime. This allows the controller to filter resource events, only queuing those which match all predicate conditions.
Alongside this, this PR implements the use of Predicates with the StorageCluster controller as well, both as an enhancement and a means to verify the use of Predicates in the CI.
=> [RHSTOR-1428] Introduce new controller for updating PersistentVolumes

hack/go-build.sh
Fix Error version `GLIBC_2.32' not found (required by ocs-operator)
via building static binary.
The Error is seen when the dynamic binary is built on a OS where higher
clibs version is installed and ran on the OS where lower clibs version
is installed.
=> hack: build netgo osusergo in binary instead of using clibs

pkg/controller/storagecluster/external_resources.go, pkg/controller/storagecluster/noobaa_system_reconciler.go, pkg/controller/storagecluster/noobaa_system_reconciler_test.go
The hack was used to pass the address for an RGW endpoint in external mode before proper support introduced to noobaa operator
=> Remove rgw-endpoint label hack

deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
This commit updates the OCS Operator's capabilities level to 4, "Deep
Insights". Per the [Operator SDK documentation][1], we now fulfill the
following requirements:
- Operator exposing metrics about its health
- Operator exposes health and performance metrics about the Operand
- Operand sends useful alerts
- Custom Resources emit custom events
The following criteria was determined by the Operator SDK team to not be
required, and indeed may soon be removed:
- Operator leverages Operator Metering
Though we may not fully have metrics for all aspects of our operations,
simply having the level we currently do is sufficient to meet the
criteria.
[1]: https://sdk.operatorframework.io/docs/advanced-topics/operator-capabilities/operator-capabilities/#level-4---deep-insights
Signed-off-by: Jose A. …
=> Update operator capabilities to level 4

openshift-ci/Dockerfile.tools
Upgrading build tools to latest Fedora release.
Golang 1.15.2 has important security fixes.
=> Upgrade build tools to Fedora 33 and Golang 1.15.2

hack/verify-generated.sh
This typo causes issues when verify-generated.sh is
run and there are outdated changes.
=> fixes typo in verify-generated.sh

must-gather/collection-scripts/gather_ceph_resources
Use awk to find only Ready nodes as NotReady
nodes has Ready so there is no distinction.
=> must-gather: Use awk to find Ready nodes only

test/crd_validation_test.go
Skipping CRD validation test as we are moving to
newer CRD schema whereas the test uses older schema
and needs some investigation and updates before it
can be used again.
=> skips CRD Validation tests

tools/csv-merger/csv-merger.go
" --- " in CRD spec descriptions causes the YAML to be invalid.
We replace it but not "---" which is used as separator.
=> fix invalid YAML in generated CRD files

must-gather/collection-scripts/gather_ceph_resources
Fixed an issue where even when debug pods are not in ready state, the collection script continued to execute.
=> Must Gather: collection continues even when the debug pods are not ready.

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/build/jsonnetfile.lock.json, metrics/mixin/rules/rules.libsonnet
[//]: # (Please describe your changes in detail)
This PR adds recording rules for Telemetry of OCS CPU metrics.
[//]: # (If your changes affect the CR fields, a syntax for the CR change should be provided)
[//]: # (If a bug is fixed then the behavior change of before and after should be mentioned)
[//]: # (Be sure to run ocs-operator ci before pushing `make ocs-operator-ci`)
**Description of your changes:**
Following metric recording rules will be deployed with OCS and will then be queried by OCP telemeter for the required metric.
Metrics: 
1) Amount of cores on OCS storage nodes
Definition of OCS storage nodes: Nodes on which following Pods are present in 'openshift-storage' namespace : pod =~"(noobaa-core.*|noobaa-db.*|rook-ceph-(mon|osd|mgr|mds|rgw).*)
Rule : ocs:node_num_cpu:sum
Query …
=> Added OCS CPU telemetry metric rules

build/Dockerfile.registry, nsswitch.conf
updating Dockerfile.registry to be able to support operator
registry builds with CRDs using apiextensions/v1.
also adds nsswitch.conf to fix the issue with non-root
users not being able to write this config.
=> updates Dockerfile.registry for apiextensions/v1 support

deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/csv-templates/noobaa-csv.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml, pkg/apis/ocs/v1/storagecluster_types.go, pkg/apis/ocs/v1/zz_generated.deepcopy.go, pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go, test/crd_validation_test.go
**Description :**
- Rook has added support to configure a wal PVC for an OSD in https://github.com/rook/rook/pull/5580
- This PR is about enabling the same support via OCS
- It can be used by creating a new walPVCTemplate.
A template will look like this:
```
dataPVCTemplate:
spec:
storageClassName: local-block
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 500Gi
volumeMode: Block
walPVCTemplate:
spec:
storageClassName: local-block-wal
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 100Gi
volumeMode: Block
```
=> Support Wal pvc for a given OSD

hack/build-functest.sh
If ginkgo binary is not found on the system when running the functest,
we were installing ginkgo using go get. The downside to that is that it
updates the go.mod and go.sum file. It is not the intention.
Go has install command which helps us to only install the binary without
updating go.mod and go.sum. This commit updates the hack script to only
install ginkgo.
=> install ginkgo but don't edit the go.mod file

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/rules/rules.libsonnet
This is done to follow the convention OCP team follows as all the customers can see names of these rules.
=> Updated OCS telemeter rule name to match with OCP pattern

deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
minKubeVersion of 1.16.0 ensures that we don't attempt installing on lower versions which does not support apiextensions/v1.
=> Adding minKubeVersion to CSV

functests/config.go, functests/ocs/cluster_upgrade_test.go, functests/ocs/storagecluster_creation_test.go, functests/setup_teardown.go, pkg/deploy-manager/config.go, pkg/deploy-manager/storagecluster.go
This will be required for testing scenarios where we want to install StorageClusters that are not of default config.
This is in preparation to the arbiter feature.
=> functests: improvements to allow StorageCluster with different configurations

deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, pkg/apis/ocs/v1/storagecluster_types.go, pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
=> add new property TuneFastDeviceClass

pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/storagecluster_controller_test.go
Reviewing PR #864 made me consider the naming of functions and variables and the structure of functions. I found it confusing that it talked about throttling internally and converted this to tuning toggles for rook, while ocs-operator is not doing any throttling. Furthermore, having two lists of fast and slow device storage classes, but having the the detection function hardcode which provisioner to apply each list against did not seem very intuitive and robust to me.
This PR refactors the code to be (IMHO) more obvious and more prone to future expansions of known devices.
=> Refactor device tuning code

deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
A new property TuneFastDeviceClass was added to the Storage Cluster
spec in PR #864. This commit adds the generated changes for that.
=> update crd changes for TuneFastDeviceClass

pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/storagecluster_controller_test.go
=> cephcluster: tune devices according to the deviceType

pkg/controller/storagecluster/reconcile.go
Remove the metadata setting from storage cluster as it is benefiting nothing.
just check for invalid deviceType and throw error.
=> storagecluster: remove the deviceType from validateStorageDeviceSets

pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/storagecluster_controller_test.go
Problem:  crushDeviceClass annotations not being reflected in cephCR.
Important: So to verify that deviceClass for an osd is updated. Though it logical grouping. Won't effect the performance.
Solution: set annotation in cephCR.
=> cephcluster: add annotation for each deviceType in cephCR

pkg/controller/storagecluster/external_resources.go, pkg/controller/storagecluster/storageclasses.go, pkg/controller/storagecluster/storageclasses_test.go, pkg/controller/storagecluster/uninstall_reconciler.go, pkg/controller/storagecluster/uninstall_reconciler_test.go, pkg/controller/storagecluster/volumesnapshotterclasses.go
In order to create a minimal test halo for the release of version 4.6, minimal change to the handling of StorageClass and SnapshotClass suggested that we identify the Ceph storage type of each StorageClass or SnapshotClass by slice index for the purpose of looking up management options. This approach will often become somewhat brittle over time. To better support future changes, this patch set creates wrapping structs around StorageClasses and SnapshotClasses that bundle them with their deployment options.
=> Storageclass and snapshotclass refactor

deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml, pkg/apis/ocs/v1/storagecluster_types.go, pkg/controller/defaults/defaults.go, pkg/controller/storagecluster/cephobjectstores.go, pkg/controller/storagecluster/cephobjectstores_test.go
In many use cases, 1 is the most sensible number of RGW instances
to create in a StorageCluster, but it is necessary to allow the
user to create more. This change makes this value configurable
with a default of 1.
Signed-off-by: egafford <egafford@redhat.com>
=> Add configurable number of CephObjectStore gateway instances

CONTRIBUTING.md, DCO
This change adds a contribution guide to the OCS-operator project.
Signed-off-by: egafford <egafford@redhat.com>
=> Contribution Guide

must-gather/collection-scripts/gather
Now, must gather will only collect ceph logs when there will be a storage cluster deployed. Otherwise, it will skip it.
=> must-gather: gather ceph logs only when storageclusters is present

controllers/ocsinitialization/sccs.go
In order to support a fix to noobaa operator running db pod as a specific user
and not part of a changing uid range
Fix bug 1903573
Signed-off-by: jackyalbo <jalbo@redhat.com>
=> Changing NooBaa's SCC to RunAsAny instead of RunAsRange

controllers/storagecluster/cephcluster.go, controllers/storagecluster/platform_detection.go, controllers/storagecluster/storagecluster_controller_test.go
set tunefastdeviceclass according to plaftorm
which are not correctly detected by ceph.
modify tc according to the changes.
=> cephcluster: tune disks according to plaftorm

controllers/storagecluster/reconcile.go
When triggering the job for multiple OSDs removal, the template includes comma along with OSD IDs in the job name. This will cause the template to fail.
This commit will give the osd removal job constant and valid name.
=> Removes the OSD IDs from the osd removal job name

controllers/storagecluster/reconcile.go
This is a temporary workaround for a race condition with the Ceph PG
autoscaler. In cases where the autoscaler only detects our default RBD
and CephFS pools it will set the PG count for them to 128 instead of the
usual 32. In small clusters, this prevents the creation of additional
pools, e.g. for RGW. Setting mon_max_pg_per_osd to a higher value helps
account for the temporary state where few pools ar eusing a high number
of PGs.
=> Adjust mon_max_pg_per_osd for Rook-Ceph

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/ocsinitialization/sccs.go, controllers/persistentvolume/reconcile.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/cephobjectstores_test.go, controllers/storagecluster/cephobjectstoreusers.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/external_resources_test.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/topology.go, controllers/storagecluster/topology_test.go, controllers/storagecluster/uninstall_reconciler.go, controllers/storagecluster/uninstall_reconciler_test.go, controllers/storagecluster/volumesnapshotterclasses.go
refactor StorageClusterReconciler methods to use
StorageClusterReconciler logger and remove
logr.Logger type argument from methods.
=> Refactor: Remove redundant logger from StorageClusterReconciler methods

controllers/storagecluster/noobaa_system_reconciler.go
Add resource names in Noobaa's ensureDeleted func logging.
https://bugzilla.redhat.com/show_bug.cgi?id=1915737
backport of https://github.com/openshift/ocs-operator/pull/992
=> Bug 1915737: [release-4.7] storagecluster: Enhance Noobaa ensureDeleted logging

Makefile
The target update-generated was removed in the recent project structure
overhaul, but it was still listed PHONY and referenced in the
verify-generated script. It's useful to have this separate target, so
re-adding it instead of cleaning up.
=> Makefile: re-add target update-generated

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/rules/rules.libsonnet
The feature of gathering metrics for OCS telemetry is dropped due to better
alternatives available to achieve the same. Thus, reverting the addition of rules.
This PR needs to be backported to the 4.7 branches, as the rules will be unrequired there and will consume Prometheus bandwidth if not removed. 
=> Remove OCS CPU telemetry metric rules

controllers/storagecluster/reconcile.go
When triggering the job for multiple OSDs removal,
the template includes comma along with failed OSD IDs in the label.
This fix will make a label valid in format.
=> Job: Removes the OSD IDs from the label

controllers/storagecluster/cephcluster.go, controllers/storagecluster/topology.go
The existing code was only applicable for clusters that had failure
domains per replica set to one. In case of arbiter, we have replicas per
failure domain set to 2.
=> StorageCluster: fix logic to determine minimum nodes

must-gather/collection-scripts/gather_noobaa_resources
This PR will collect noobaa-db pod logs based on the Postgres label on it, this change comes after the new addition of postgres label on the noobaa db pod. It will collect the logs in the Noobaa folder as well.
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=1915644
=> must-gather: noobaa-db pod collection on postgres label

controllers/storagecluster/cephcluster.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/external_resources_test.go, controllers/storagecluster/storagecluster_controller.go
In external cluster mode, we provide (along with other details) both monitoring IP and Port. IP was being configured whereas Port value was neglected (ie; it was not propagated to CephCluster spec).
This PR is to make sure we pass `Port` as well to CephCluster spec.
PS: as the changes for accessing CephCluster external-monitoring-port is available only from rook-v1.5.3, this is dependent on PR https://github.com/openshift/ocs-operator/pull/965, which updates the rook version (to v1.5.3)
=> Make cephcluster monitoring port, in external cluster mode, configurable

controllers/storagecluster/cephcluster.go, controllers/storagecluster/topology.go
The existing code was only applicable for clusters that had failure
domains per replica set to one. In case of arbiter, we have replicas per
failure domain set to 2.
(cherry picked from commit 6836e24569a5f54a0b39661504f689321d2f9c35)
=> Bug 1914203: [release-4.7] StorageCluster: fix logic to determine minimum nodes

controllers/storagecluster/reconcile.go
Allow for creating more pools.
In e5292567c9eb7267ecaa530dd9d4bfd59368a647, we raised
the mon_max_pg_per_osd to 300 to prevent pool creations
from failing. It turns out that this wasn't quite enough.
Raising it to 600 now to allow for a few more rbd pools
to be created.
=> ceph: raise mon_max_pg_per_osd from 300 to 600

controllers/storagecluster/storagecluster_controller_test.go, controllers/storagecluster/topology_test.go
Add test cases which ensure that when insufficient zones/regions are
available, we assign racks automatically.
=> StorageCluster: add test cases for insufficient zones and regions

controllers/storagecluster/reconcile.go, controllers/util/events.go
Fix Error via changing event type
"E0210 23:17:48.027136       1 event.go:334] Unsupported event type: 'Error'"
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1913357#c8
=> storagecluster: Change event type from error to warning

controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/generate.go
Instead of hardcoding it, we get the value generated using a function.
=> StorageCluster: generate cephReplicatedSpec to abstract out arbiter values

controllers/storagecluster/readiness.go, controllers/storagecluster/reconcile.go, main.go
With the change to operator-sdk v1, the readiness probe changed from a simple file check to an HTTP get readiness probe.
In the process of accommodating this, the readiness logic in 4.7 changed slightly: [the ocs-operator would report ready even when the StorageCluster was in a progressing phase](https://bugzilla.redhat.com/show_bug.cgi?id=1927885).
Through reading the code and manually testing, I found this to be the 4.6 readiness behavior:
When ocs-operator first gets created: 1/1
When storagecluster creation is in progress: 0/1
When storagecluster creation completes: 1/1
When storagecluster deleted: 1/1
If the storagecluster is deleted while in progress: 0/1
When storagecluster creation is reinitiated: 0/1
After making the changes, I deployed on an AWS Openshift cluster and manually …
=> Bug 1927885: reverted readiness logic to match behavior of 4.6

controllers/storagecluster/cephcluster.go
We always want to rely on the internal defaults for minimum number of
nodes. They are 4 for arbiter cluster and 3 for non-arbiter cluster.
In cases where the storage device set has a value greater than the
default we make the assumption that the user wants that many nodes.
Co-authored-by: Michael Adam <obnox@redhat.com>
=> StorageCluster: fix the logic for the minimum number of nodes

api/v1/storagecluster_types.go, api/v1/topologymap.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/placement.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/topology.go, controllers/storagecluster/topology_test.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
In ocs-operator we have been using two deprecated  topology label prefixes `failure-domain.beta.kubernetes.io` and `failure-domain.kubernetes.io`. 
The recommended label to use is `topology.kubernetes.io`. In this PR, we add support for the new label while also adhering to the following rules:
1. In a new install use only the new label
2. In existing setups, switch to the new label only if all the nodes have a equivalence of the labels i.e if node1 has zone1 set on the old labels then the new label should also have zone1 as its value.
3. In existing setups, if the values for all three labels don't match then we continue to use the old labels.
4. We also start persisting the failure domain key and values in the StorageCluster Status. This will probably make it easy to make a forced switch …
=> Enable new topology labels from Kubernetes

controllers/storagecluster/readiness.go, controllers/storagecluster/reconcile.go, main.go
With the move to operator-sdk v1, the readiness probe changed from a simple file
check to an HTTP GET call. In the process of accommodating this, the readiness
logic in 4.7 changed slightly: the ocs-operator would report ready even when the
StorageCluster was in a progressing phase.
The expected readiness behavior is as follows:
- When ocs-operator first gets created: 1/1
- When storagecluster creation is in progress: 0/1
- When storagecluster creation completes: 1/1
- When storagecluster is deleted: 1/1
- If the storagecluster is deleted while in progress: 0/1
- When storagecluster creation is reinitiated: 0/1
Backport of #1067
=> Bug 1927885: [release-4.7] reverted readiness logic to match behavior of 4.6

api/v1/storagecluster_types.go, api/v1/topologymap.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/placement.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/topology.go, controllers/storagecluster/topology_test.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
In ocs-operator we have been using two deprecated  topology label prefixes `failure-domain.beta.kubernetes.io` and `failure-domain.kubernetes.io`. 
The recommended label to use is `topology.kubernetes.io`. In this PR, we add support for the new label while also adhering to the following rules:
1. In a new install use only the new label
2. In existing setups, switch to the new label only if all the nodes have a equivalence of the labels i.e if node1 has zone1 set on the old labels then the new label should also have zone1 as its value.
3. In existing setups, if the values for all three labels don't match then we continue to use the old labels.
4. We also start persisting the failure domain key and values in the StorageCluster Status. This will probably make it easy to make a forced switch …
=> Bug 1915807: [release-4.7] Enable new topology labels from Kubernetes

must-gather/collection-scripts/gather_ceph_resources
Problem: Must-gather continues to skip the ceph collection for every run.
solution: Adding --no-headers removes the` READY` keyword from the output which helps the condition to verify the state of pod without any intermittent issues hitting. The state being 1/1.
=> Must-gather: add no headers in skip ceph collection

controllers/defaults/placements.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
This PR provides the folowing changes
- To have effective OSD distribution, 
- Added changes to have a common key as topology spread label selector as it matches both prepare and OSD pod.
- Added hard constraints for prepare placement failure domain(zone/rack) in case of multiple topology spread constraints.  
- Restricts the movement of portable volumes between failure domain (rack) while node drain by imposing hard constraint in topology spread. 
=> StorageCluster:Fixed placement config for rack failure domain and modified labelselector

must-gather/collection-scripts/gather_ceph_resources
add bg process for ceph cmds. create
temp log file for ceph bg cmds and
cat them to gather-debug.log file.
=> Must-gather: add bg process for ceph cmds

Makefile, hack/build-master-appregistry.sh, hack/generate-master-appregistry.sh, openshift-ci/Dockerfile.registry.build.master, openshift-ci/Dockerfile.registry.master
At present, all OCS operator CI builds use fixed container versions
for each other OCS project. This will continue to be appropriate,
but a non-blocking CI job to notify us of compatibility issues
between the master branches of multiple OCS components would be
useful. This change introduces new scripts for the easy generation
of an OCS registry that will pull the most recent container image
from the master branch of each component project.
Notes on implementation:
- I chose to use the most recent published container image for each
project, rather than building from the most recent code for each,
in order to leave each project team fully responsible for their own
build process and able to change it without breaking any CI jobs.
This is a tradeoff, as teams may not update container images …
=> Add a master branch configuration for openshift-ci

pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/storagecluster_controller_test.go
The Azure Storage class does not have a "type" parameter.
Fixed to check for storageaccounttype instead.
=> Bug 1909793: Fix fasttune check for Azure storageclass

hack/source-manifests.sh
I noticed that the bundle was being pulled from the Go directory and not necassarilly the build repository.
=> Localizing build process.

controllers/storagecluster/quickstart_constants.go
Changes based on https://github.com/openshift/console-operator/pull/509#issuecomment-785383525, that addresses the ® symbol usage in Quickstarts.
=> Fix "OpenShift(R)" usage in Quickstarts

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/storagecluster_controller_test.go
The logic to determine the location affinity for the OSDs should be
based on the minimum DeviceSetReplica for a Storage Cluster
configuration and not on the replica count of the StorageDeviceSet.
TODO: The function to generate the StorageClassDevicesSets should be
refactored further. This is a short term fix to make it easy to
backport to other branches.
=> Fix the OSD placement logic when arbiter is enabled

controllers/defaults/placements.go, controllers/storagecluster/placement.go, controllers/storagecluster/placement_test.go, controllers/storagecluster/storagecluster_controller_test.go
use requiredDuringSchedulingIgnoredDuringExecution for podAntiAffinity for mons failure domain topology key to prevent two mons from starting in the same failure domain.
Tested on 4 node AWS cluster.
1. Intial placement of mons:
```
ip-10-0-154-79.ec2.internal --> us-east-1a
mon-b --> ip-10-0-155-80.ec2.internal --> us-east-1a
mon-a --> ip-10-0-161-91.ec2.internal --> us-east-1b
mon-c --> ip-10-0-199-137.ec2.internal --> us-east-1c
```
```
rook-ceph-mon-a-76b5745b8c-kw88k                                  2/2     Running     0          5m26s   10.128.2.23    ip-10-0-161-91.ec2.internal    <none>           <none>
rook-ceph-mon-b-b877796bc-nrm8c                                   2/2     Running     0          4m33s   10.129.2.19    ip-10-0-155-80.ec2.internal    <none>           <none> …
```
=> Bug 1788492: use stricter podAntiAffinity rules for mons in non-stretched cluster

controllers/storagecluster/cephcluster.go, controllers/storagecluster/kms_resources.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/uninstall_reconciler.go
KMS resources, such as ConfigMaps and SecretToken which were created at the time of StorageCluster creation, are lurking around even after we uninstall the StorageCluster.
This PR is to delete those resources at the time of StorageCluster uninstallation.
=> Delete kms resources while uninstalling StorageCluster

controllers/storagecluster/exporter.go
Create ServiceMonitor with default labels but do not reconcile
on label updates. This allows users to add custom labels to
ServiceMonitor which can be used by custom Prometheus instances
for monitoring.
=> unmanage labels for exporter ServiceMonitor

hack/source-manifests.sh
We cannot use quotes around the noobaa dump csv cmd (olm csv yaml)
because otherwise, these will be treated as a single argument instead of
three arguments and the csv generation fails.
Signed-off-by: Boris Ranto <branto@redhat.com>
=> hack/source-manifests: Do not use quotes

must-gather/collection-scripts/gather_ceph_resources
add --no-headers in rsyunc cmd, create array for pids
skip the log msg if pid array is empty and improvements
in code.
=> Must-gather: refactor the crash and volume collection

pkg/controller/storagecluster/exporter.go
Create ServiceMonitor with default labels but do not reconcile
on label updates. This allows users to add custom labels to
ServiceMonitor which can be used by custom Prometheus instances
for monitoring.
Backport of #1099
=> Bug 1936405: unmanage labels for exporter ServiceMonitor

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
mon C take time to come up on IBMCloudPlatform which timeouts and Mon d gets created. So increase the mon
failover timeout to 15 min for IBMCloudPlatformType to allow enough time
for mon c to come up.
Signed-off-by: rohan47 <rohgupta@redhat.com>
=> Increase mon failover timeout to 15 min for IBMCloudPlatformType

controllers/storagecluster/topology.go
Set the failure domain to host if flexible scaling is enabled
even if there are 3 or more zones.
=> Set failure domain to host if flexibleScaling is enabled

controllers/storagecluster/cephcluster.go, controllers/storagecluster/external_resources.go
A ceph cluster will contain an active 'mgr' (manager) and
(may have) multiple stand-by 'mgr'-s.
This change will allow OCS-Operator to accept multiple
(comma / space separated) endpoints/IP addresses, which
will be passed to external ceph-cluster spec.
This will help rook (which reads the ceph-cluster spec internally)
to change over to the next 'mgr' when the current active 'mgr' fails.
=> OCS-Operator now supports multiple external monitoring IPs

hack/source-manifests.sh
We cannot use quotes around the noobaa dump csv cmd (olm csv yaml)
because otherwise, these will be treated as a single argument instead of
three arguments and the csv generation fails.
The same goes for the noobaa crds.
Signed-off-by: Boris Ranto <branto@redhat.com>
(cherry picked from commit ddb49afd2c480a3bdede1b725a3b15c4df49038a)
=> Bug 1942354: [release-4.6]  hack/source-manifests: Do not use quotes

hack/generate-master-appregistry.sh, hack/generate-master-bundle.sh, hack/generate-master-csv.sh, openshift-ci/Dockerfile.bundle.master
This change allows ci-operator to generate a bundle for
OCS-operator which pulls from the master branches of the
component projects of OCS.
Signed-off-by: egafford <egafford@redhat.com>
=> Generate ci-operator bundle for master branches of all projects

controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go
Noobaa's root secret key, used for MCG encryption, should only  be
stored in to KMS server only if cluster wide encryption with StorageClass
encryption enabled.
Corrected the test cases accordingly.
=> Enable Noobaa KMS configuration only when the cluster-wide encryption is enabled

must-gather/collection-scripts/gather
now, the noobaa collection will only happen when the storagecluster will be present, otherwise, it would skip the noobaa collection
=> must-gather: skip noobaa collection when storagecluster is not present

controllers/storagecluster/reconcile.go
As of now if spec is not valid we are logging error and recording events
and status.phase is still in the ready or progressing state. which gives
wrong indication to the user. From now onward we are changing the phase
of the storagecluster to get the user attention.
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=1913357#c16
=> storagecluster: Change the phase when spec is not valid

hack/golangci_lint.sh, hack/shellcheck-test.sh
curl seems to be more standard these days.
E.g. on mac it's there by default.
=> Use curl instead of wget

hack/verify-latest-csv.sh
This was checking generated csv files from before the move
to the sdk-version before 1.0.
This patch adjusts to the new locations.
=> test: fix verify-latest-csv

controllers/storagecluster/reconcile.go
r.Client.Update() does not update the status which was not showing the
correct phase of the storagecluster. Fix the same via start using the
r.Client.Status().Update() call instead.
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=1913357
=> storagecluster: Fix Update in validateStorageClusterSpec

must-gather/collection-scripts/gather_ceph_resources
added echo messages in the gather debug log file.
=> must-gather: add logs in debug file that were skipped

controllers/ocsinitialization/ocsinitialization_controller_test.go
After updating the controller runtime in #1141 , there has been a change in the fake client behavior. This requires update to the tests to get back the original behavior.
=> Fix tests after fake client update

hack/common.sh
It seems the latest stable shellcheck update has uncovered another issue
SC2269: This variable is assigned to itself, so the assignment does nothing.
=> hack: fix new shellcheck issue SC2269

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephcluster.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
For cases where we want to associate OSD and pools with devices on
specific nodes with specific devices, we need a more fine-grained level
of device-type, which is passed on to rook as CRUSH-device-class.
As an example, consider cluster with ssd devices from two different
vendors, where user would want to have different pools, one for each
sub-device type. When combined with node-labeling and this patch, the
task becomes trivial.
=> Allow passing explicit DeviceClass

controllers/storagecluster/cephcluster.go
recent cases of mons db require more space then 10G. Increase the space
to 50G.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1944580
=> storagecluster: Increase mons db allocated space

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephcluster.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Allow passing explicit InitialWeight
Allow passing explicit CRUSH initial-weight upon OSD init, using
annotations mechanism (same as DeviceType/DeviceClass). This may be
useful for cases where user wants to have more fine-grained control on
the overall load of specific devices. As an example, consider the
(real-life) case of a PV which resides on a partition alongside OS
partition. In such case, user can reduce I/O to the OSD over this PV be
lowering its weight value.
Issue: https://issues.redhat.com/browse/KNIP-1616
=> Explicit osd weight

controllers/storagecluster/reconcile.go
Commit 3fc88d52 ("merge user provided labels with existing ones") passes
'Labels' as map of single entry, with empty string. This, in turn,
causes deployment failure on AWS cluster, with the following message:
failed to create metrics exporter service
openshift-storage/ocs-metrics-exporter. Service \"ocs-metrics-exporter\" is
invalid: [metadata.labels: Invalid value: \"\": name part must be non-empty
Fixed by setting empty Labels map for the default case of Spec.Monitoring
=> do not pass labels as map of single empty string

controllers/storagecluster/cephcluster.go
Add default PriorityClasses support in the cephcluster CRD.
Use "systemNodeCritical" for the Mgr, Mon, Osd and
"openshiftUserCritical" for the Mds
look at rook PR: https://github.com/rook/rook/pull/3206 for more details
=> storagecluster: Add PriorityClasses to the cephcluster definition

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/external_resources.go
Add default PriorityClasses support
Use "systemNodeCritical" for the Mgr, Mon, Osd and
"openshiftUserCritical" for the Mds and rgw
Signed-off-by: Nitin Goyal nigoyal@redhat.com
pending from https://github.com/openshift/ocs-operator/pull/1166
look at rook PR: rook/rook#3206 for more details
=> storagecluster: Add PriorityClasses support for all resources

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/external_resources.go
Add default PriorityClasses support in the cephcluster CRD.
Use "systemNodeCritical" for the Mgr, Mon, Osd and
"openshiftUserCritical" for the Mds, rgw
Signed-off-by: Nitin Goyal nigoyal@redhat.com
Master PR's https://github.com/openshift/ocs-operator/pull/1166, https://github.com/openshift/ocs-operator/pull/1169
=> Bug 1776876: [release-4.8] Add priority Class for the ceph resources

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephcluster.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Allow passing explicit primary-affinity upon OSD's deployment using
annotations mechanism (same as DeviceClass/InitialWeight). This may be
useful for cases where user wants to have more fine-grained control on
the overall (read) load of specific devices. Valid values are within
range [0, 1) (where 1 is the default).
As an example, consider the (real-life) case of a PV which resides on a
partition alongside OS partition. In such case, user can reduce I/O load
of this specific OSD by choosing explicit primary-affinity value.
Issue: https://issues.redhat.com/browse/KNIP-1616
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1924946
=> Allow passing explicit PrimaryAffinity

controllers/storagecluster/prometheus.go
This commit fixes ClusterObjectStoreState alert spec being empty due to
which the rule was not being listed in the Prometheus Rules and alert
was not working. The reason alert spec is empty is because the function
getPrometheusRuleSpecFrom is returning empty object as the rule file
decoding is creating an object that matches the type struct
monitoringv1.PrometheusRule{} which does not match with the type of the
variable ruleSpec which is monitoringv1.PrometheusRuleS
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=1948378
=> fix ClusterObjectStoreState Alert empty spec

controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller.go, controllers/util/events.go
The PR contains a new pkg `customevents` which will allow an operator to limit the events and stop spamming the APIServer.
cc @raghavendra-talur @rohantmp 
PS: I have added this as a new pkg because we need this at the rook layer also.
=> Add a pkg custom events and start using it for storage cluster

must-gather/collection-scripts/gather_noobaa_resources
added a workaround which fixes the issue where noobaa obc list command was not working. This is just a workaround and might be updated in the later releases.
=> must-gather: noobaa obc list command not working

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
newCephDaemonResources was taking custom resource requirements
for multiple daemons but only returning resource requirements
of ceph-mgr and mon.
This patch changes it to take all custom resource requirements
and merge it with the defaults. If key exists, it's value will
be overwritten and if it doesn't exist, it will be appended.
=> fix merge strategy for newCephDaemonResources

controllers/defaults/resources.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
This also updates the count of MGRs that are created for an arbiter
deployment to 2.
=> Storagecluster: generate mgr spec in a function

controllers/storagecluster/job_templates.go
Refer: https://bugzilla.redhat.com/show_bug.cgi?id=1966149
The osd removal job name on OCS4.7 and OCS4.8 is different.Thus this PR will set back the original name of the job
=> Re-Change job template name to its original one, 

must-gather/collection-scripts/gather
fixes a small issue where ceph collection was skipping even if storagecluster exists.
It got introduced after merging #1191 
=> must-gather: no ceph collection even when sc is present

controllers/storagecluster/reconcile.go
Bug 1966149 : [ Re-Change the job template name back to its original one]
Since 4.8 does not have https://github.com/openshift/ocs-operator/pull/1153 ,  we cannot backport https://github.com/openshift/ocs-operator/pull/1198 alone , to 4.8 
This PR re-changes the job name to its original one w.r.t to the current code in release-4.8 branch
Signed-off-by: Prajith Kesava Prasad <pkesavap@redhat.com>
=> Bug 1966149: [release-4.8] Re-Change the job template name back to its original one

controllers/storagecluster/external_resources.go
'Instances' field in GateWay spec needs to be atleast ONE.
External cluster creations are failing due to this with
following error in OCS Operator logs,
"error":"CephObjectStore.ceph.rook.io \"ocs-external-storagecluster-cephobjectstore\"
is invalid: spec.gateway.instances: Invalid value: 0: spec.gateway.instances in body
should be greater than or equal to 1"
=> GateWay spec's 'Instances' field should be minimum 1

controllers/storagecluster/topology.go, controllers/storagecluster/topology_test.go
Add a new rack for a node if there are no empty racks and none
of the nodes in the existing racks belong to the same zone as the new
node.
=> topology: fix crash in determinePlacementRack

controllers/storagecluster/job_templates.go
Reference https://bugzilla.redhat.com/show_bug.cgi?id=1962281
The status of "ocs-osd-removal-job pod" turns completed although removal
job failed to remove osds successfully.
In some cases user might enter wrong input to the FAILED_OSD_IDS
template parameter.
This commit updates the template description to notify the user to always
read the job logs to check whether osds successfully removed or not.
=> Update the ocs-osd-removal template description

controllers/storagecluster/external_resources.go
Thick-provision storage class is required along with RBD storageclass.
=> Adding 'thick-provision' storageclass to External cluster

controllers/storagecluster/reconcile.go
Reference https://bugzilla.redhat.com/show_bug.cgi?id=1962281
The status of "ocs-osd-removal-job pod" turns completed although removal
job failed to remove osds successfully.
In some cases user might enter wrong input to the FAILED_OSD_IDS
template parameter.
This commit updates the template description to notify the user to always
read the job logs to check whether osds successfully removed or not.
(cherry picked from commit 92df1c3044538ef6152650757c0efbf1e4ad3048)
=> Bug 1962281:  Update the ocs-osd-removal template description #1215

controllers/storagecluster/reconcile.go
The removal of a failed StorageCluster leaves the OCS operator in the
Not Ready state. We now set the readiness state on SC termination.
=> Set the operator readiness state to true on StorageCluster removal

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in, hack/common.sh, hack/generate-master-appregistry.sh, hack/generate-master-bundle.sh, version/version.go
This also resolves the fact that both `master` and `release-4.8` CI are pushing to `quay.io/ocs-dev/ocs-*:latest`.
=> Bump ocs-operator to v4.9.0

deploy/bundle/manifests/rook-monitor-mgr-role.yaml, deploy/bundle/manifests/rook-monitor-mgr-role_binding.yaml, rbac/rook-monitor-mgr-role.yaml, rbac/rook-monitor-mgr-role_binding.yaml
Stretch clusters have two mgrs, each with a sidecar for updating the services and service monitor if the active mgr changes in Ceph. The mgr pod needs access to update the service monitor.
In order for the monitoring RBAC to be picked up, it needs to be added to the OCS operator in this folder:
https://github.com/openshift/ocs-operator/tree/master/rbac
This corresponds to the RBAC that was added upstream in this PR: https://github.com/rook/rook/pull/8118
=> Add RBAC for creating service monitors from mgr sidecar

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/storagecluster_controller_test.go
There was a strange issue where the StorageCluster would report `Ready` even though it had an unhealthy CephCluster still pending. This was because when the operator detected a divergence that required an `Update()` in the CephCluster it would make the update and then `return nil` before checking the Status of the CephCluster in question.
This PR also refactors `TestEnsureCephCluster()` to make it easier to see the changes that were needed to reproduce the bug and validate the fix.
=> Don't report Ready when CephCluster has not reached ClusterStateCreated

go.mod
Go 1.16 is not available in upstream builder images.
Dockerfile needs to be updated once it is available.
=> deps: update Golang to 1.16

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_common_ceph_resources
Currently for External mode, the must-gather skips the whole ceph collection
and therefore some resources which are applicable for external mode are absent
in the logs. Those resources are
* cephobjectstores
* cephobjectstoreusers
* cephclusters
=> must-gather: collect ceph CR's logs when external cluster is deployed

controllers/storagecluster/external_resources.go
Whenever a 'ceph-rbd' SC name is found, we have to create both thin and
thick provision RBD StorageClasses and for both the SC-s' parameters has
to be modified according to the 'data' passed from the input secret.
=> Thick Provision SC Parameters has to be updated

Makefile, extras/DEBUG_EXPORTS.sh
`make run` to run operator locally and `source ./extras/DEBUG_EXPORTS.sh` to source required environment variables.
=> Updates DEBUG_EXPORTS.sh and adds new make target

main.go
adding zap flags to commandline flags allows users to configure
logging at runtime by passing the right flags. These flags are
then used to instantiate a logger which is then used for logging
messages.
`--zap-devel=true|false` for running in development mode
`--zap-encoder=json|console` for output format
`--zap-log-level=debug|info|error` for log level
```
Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn).
Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error).
```
```
NOTE: this is in preparation for enhanced logging
```
=> logger: add zap flags to commandline

must-gather/collection-scripts/gather_ceph_resources
jq command is now built with rook-ceph base image.
No need to download it while collecting must-gather.
Fixes: https://github.com/openshift/ocs-operator/issues/1187
=> must-gather: Don't download and install jq

hack/source-manifests.sh
Noobaa operator no longer accepts `olm csv yaml` command for dumping the
noobaa CSV. It is just `olm csv`, now. The new command still works in
older noobaa operators (4.8 at least), only the support for the yaml
suffix was dropped in 4.9.
Signed-off-by: Boris Ranto <branto@redhat.com>
=> hack/source-manifests: Update noobaa cmd

must-gather/OWNERS
add parthdhanjal and gobindadas
as the reviwers and approvers of
must-gather.
=> must-gather: update OWNERS file

controllers/storagecluster/reconcile.go
Adding "bdev_flock_retry = 20" to the [global] section
of the defaultRookConfigData var.
=> ceph: add retry to acquire flock

hack/common.sh, hack/go-build.sh
Synchronizes the `version.Version` to `$CSV_VERSION`'s value at build-time.
=> Update OCS operator version at build time

controllers/storagecluster/cephcluster.go
+ monitoring labels from StorageCluster spec is passed on to
CephCluster spec so that Rook can take care of injecting these
labels into the monitoring resources that it creates.
Follows up on #1129 .
=> pass monitoring labels to CephCluster

controllers/storagecluster/reconcile.go
Adding "mon_pg_warn_max_object_skew = 0" to
the [global] section of the defaultRookConfigData var.
=> ceph: disable many objects warning

controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/cephobjectstores_test.go, controllers/storagecluster/cephobjectstoreusers.go, controllers/storagecluster/cephobjectstoreusers_test.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/platform_detection.go, controllers/storagecluster/routes.go, controllers/storagecluster/routes_test.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storageclasses_test.go
Replace "avoid" with "skip" in functions and variables whenever
it better clarifies what the code is doing.
=> ocs: replace avoid with skip where possible

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/rules/rules.libsonnet
This PR fixes the typos in the ocs performance recording rules for the cluster latency.
Tested the rules on the cluster:
=> Fix ocs performance latency recording rules

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Backport of #1298
Signed-off-by: Kaustav Majumder kmajumder@redhat.com
=> Bug 1977329: [release-4.8] Allow DBStorageClass to be set from Storage Cluster CR for Noobaa

must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_clusterscoped_resources, must-gather/collection-scripts/gather_namespaced_resources
This PR adds the following changes.
1. separate mirroring info from snapshot info
2. adds mirror snapshot schedule list
3. checks if mirroring is enabled in CBP
4. collect logs for VR in all namespaces.
=> must-gather: collect logs for RegionalDR

deploy/bundle/manifests/exporter-role.yaml, deploy/bundle/manifests/exporter-role_binding.yaml, deploy/bundle/manifests/exporter-service-role.yaml, deploy/bundle/manifests/exporter-service-role_binding.yaml, deploy/bundle/manifests/noobaa-metrics-role.yaml, deploy/bundle/manifests/noobaa-metrics-role_binding.yaml, deploy/bundle/manifests/rook-metrics-role.yaml, deploy/bundle/manifests/rook-metrics-role_binding.yaml, deploy/bundle/manifests/rook-monitor-role.yaml, deploy/bundle/manifests/rook-monitor-role_binding.yaml, rbac/exporter-role.yaml, rbac/exporter-role_binding.yaml, rbac/exporter-service-role.yaml, rbac/exporter-service-role_binding.yaml, rbac/noobaa-metrics-role.yaml, rbac/noobaa-metrics-role_binding.yaml, rbac/rook-metrics-role.yaml, rbac/rook-metrics-role_binding.yaml, rbac/rook-monitor-role.yaml, rbac/rook-monitor-role_binding.yaml
Update rbac manifests to use the rbac.authorization.k8s.io/v1 API version
=> OCS: Upgrade rbac manifests to use api v1

CONTRIBUTING.md, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/noobaa_system_reconciler_test.go, controllers/storagecluster/placement_test.go, controllers/storagecluster/storagecluster_controller_test.go, controllers/storagecluster/topology_test.go
The global mock variables were being reused in may tests, due to which some tests were
failing to run individually, this commit reuses mock variables by creating a DeepCopy of global mock variables to prevent
modification of global mock variables.
There were multiple duplicate functions to create Fake Scheme for the tests,
this commit keeps only one createFakeScheme function for testing StorageCluster controller.
Above two changes are dependent on each other to make tests run individually and as a whole by `make unit-test` . 
=> Fixed usage of global mock variables in unit-tests

.ci-operator.yaml
See docs:
https://docs.ci.openshift.org/docs/architecture/ci-operator/#build-root-image
Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>
=> Use .ci-operator.yaml file for OpenShift CI builds

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/alerts-external.libsonnet, metrics/mixin/alerts/alerts.libsonnet, metrics/mixin/alerts/cluster-resource-quota.libsonnet, metrics/mixin/config.libsonnet
Depends on #1282  . This PR is required to alert users about the thresholds being reached set via the functionality in #1282 .
=> add ClusterResourceQuota prometheus alert for overprovisioning

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/alerts-external.libsonnet, metrics/mixin/alerts/alerts.libsonnet, metrics/mixin/alerts/obc.libsonnet, metrics/mixin/config.libsonnet
This PR adds Prometheus alerts to notify the users when the OBC usage goes beyond 80%  and 100% of the limit(bytes/objects) set in the OBC definition.
Depends on: #1268 
Signed-off-by: Anmol Sachan anmol13694@gmail.com
=> add OBC quota prometheus alerts

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Added "mcg-standalone" in the supported features l;ist of operator csv.
This is required so we can have control over the enablement of OCS features in OCP console
Implements https://issues.redhat.com/browse/RHSTOR-2129
Signed-off-by: Afreen Rahman <afrahman@redhat.com>
=> Update csv annotation with mcg-standalone feature

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/external_resources_test.go, controllers/storagecluster/storagecluster_controller.go
This PR make sure that when JSON input is changed, corresponding external cluster resources also get updated.
This is on top of PR:https://github.com/openshift/ocs-operator/pull/1286 .
=> Fix external resources updation when json input change

controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/external_resources_test.go, controllers/storagecluster/noobaa_system_reconciler_test.go, controllers/storagecluster/storagecluster_controller_test.go
A test flake where sometimes a test would fail due to a mock server not being present has plagued us for far too long. This PR refactors the `startServerAt()` function to properly start and stop a dummy listening server. It also updates the relevant test functions to use `t.Run()` to make sure we are not reusing mock servers between test cases.
=> Fix  server listen flake forever

must-gather/collection-scripts/gather_ceph_resources
While collecting ceph commands we see that due to limit in PIDs, we get a fork system call failed: Resource temporarily unavailable error, so adding a sleep for 2s if the PIDs limit exceed
Signed-off-by: Rewant Soni <resoni@redhat.com>
=> must-gather: wait for PIDs to be avaliable

controllers/storagecluster/placement.go, controllers/storagecluster/placement_test.go, functests/common.go
add check for PodAntiAffinity not nil before checking
underlying resources otherwise it will cause nil pointer
err. Also updating unit test to test this nil pointer
condition.
(cherry picked from commit 2c9b8417d729ce089dcb65ff83de741a5c8a0402)
=> Bug 2005970: [release-4.8] add check for PodAntiAffinity not nil

controllers/storagecluster/cephconfig.go
Reduce the mon_data_avail_warn to 15% to be on same threshold with OCP's garbage collector for images.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1964055
Signed-off-by: Ashish Singh <assingh@redhat.com>
=> Reduce the mon_data_avail_warn to 15%

hack/ensure-operator-sdk.sh, hack/ensure-opm.sh, hack/operator-sdk-common.sh
Build OCS on AWS/Graviton processor (ARM, aarch64). Need to update usage
of external tools:
1) Download proper operator-sdk for local arch, make sure that the
downloaded image is indeed exacutable on local host.
2) For aarch64 need to build opm on local machine as no image is
provided.
Align definition of OS & ARCH with installation instruction at:
https://sdk.operatorframework.io/docs/installation/
=> build: support AWS/Graviton (aarch64)

must-gather/collection-scripts/gather_ceph_resources
This commit corrects the `ceph fs subvolumegroup`
command.
ceph_command="ceph fs subvolumegroup ls ${fs%?}"
removes the last character of the output.
Hence, modified ${fs%?} to ${fs}
Bz: #2006053
=> cleanup: failure getting the subvolumegroup

controllers/ocsinitialization/sccs.go, go.mod, go.sum, vendor/github.com/ceph/ceph-csi/api/LICENSE, vendor/github.com/ceph/ceph-csi/api/deploy/ocp/doc.go, vendor/github.com/ceph/ceph-csi/api/deploy/ocp/scc.go, vendor/github.com/ceph/ceph-csi/api/deploy/ocp/scc.yaml, vendor/modules.txt
Remove the duplication of the SCC for the CephCSI component, use the
new Ceph-CSI API to get the SCC instead.
Signed-off-by: Niels de Vos <ndevos@redhat.com>
=> BUG 1938647: use SecurityContextConstraints API from Ceph-CSI

controllers/storagecluster/noobaa_system_reconciler.go
Adding `managedBy` label only when mcg is standalone. This is to prevent collision when mcg is deployed along with Ceph.
=> add managedBy label only for mcg-standalone

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Added UI for dedicated nodes with taints in 4.10 (https://github.com/openshift/console/pull/10323)
This PR is to enable that UI.
Signed-off-by: sanjalkatiyar <sanjaldhir@gmail.com>
=> Enable taint-nodes from the operator CSV

controllers/ocsinitialization/ocsinitialization_controller.go
Stop using tini on the toolbox job
Rook-Ceph has stopped using tini in the current devel code which will be
release with Rook 1.8 which will be the basis of the 4.10 branch.
So removing the tini entrypoint command to replace it with a simple bash
shell.
Run the toolbox with the rook user
Rook-Ceph now uses its own user to operate. The Operator runs as "rook"
and not "root" anymore so this should be reflected in the toolbox as
well.
Stop running the toolbox as privileged
The toolbox does not need to run privileged so let's remove this
capability.
=> misc fixes for rook-ceph toolbox

controllers/storagecluster/job_templates.go
Bash's job control needs a TTY to control a terminal, without it the
container fails to run. So adding a TTY to it.
=> add a tty to the toolbox

openshift-ci/Dockerfile.tools
=> ocs-ci: Update the build tools image to Fedora 34

controllers/ocsinitialization/sccs.go
Rook is now using CAP_MKNOD in its code to execute some containers so
adding the corresponding SCC.
=> add new required capability for rook

controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/cephobjectstores_test.go, controllers/storagecluster/uninstall_reconciler_test.go
Currently kms config options are passed to ceph cluster spec, but for
RGW this need to pass seperately and need to set secret engine as
`transit` than `kv`.
=> pass kms vault options for ceph object store spec

controllers/storagecluster/cephobjectstoreusers.go, controllers/storagecluster/uninstall_reconciler_test.go
As a prerequisite for object bucket metrics collector, it is expected to have a user named `prometheus-user` in the object store with certain permissions . Otherwise, it won't able to fetch the stat info from backend. This PR automates that creation
=> Automate prometheususer creation for ob metrics collector

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
OCP console will parse `features.ocs.openshift.io/disabled` annotation to disable features.
Disabling features of UI is required to aid migration of components from OCP to ODF repo. 
/assign @umangachapagain @jarrpa
=> Introduce annotation to disable features in console

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Id field is required to keep/save the UID of a storage consumer CR from
the provider cluster in the status. It will be used/passed while making
the API calls (offboarding, upscaling/downscaling) from the consumer
cluster after onboarding is successful.
cc @nb-ohad @sp98 @kesavanvt
=> api: Add Id in the ExternalStorageClusterStatus struct

must-gather/Centos-Base.repo
Removes the unused Centos.repo file.
=> must-gather: remove unused file

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
having default value fills in a value even in the non external mode CR
which leads to a confusion.
instead of using a default value for the traditional external mode we
will treat Spec.ExternalStorage.StorageProviderKind="" as the "rhcs" if
the ExternalStorage is enabled.
Fix: https://github.com/red-hat-storage/ocs-operator/issues/1436
=> api: remove default value of Spec.ExternalStorage.StorageProviderKind

controllers/storagecluster/provider_server.go
The errors are seen while updating the service.
Errors:
- spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP
can not be unset
- spec.ipFamilies[0]: Invalid value: []core.IPFamily(nil): primary
ipFamily can not be unset
Fix: https://github.com/red-hat-storage/ocs-operator/issues/1437
=> ocs-to-ocs: Fix error Service "ocs-provider-server" is invalid

must-gather/templates/pod.template
This commit changes the root privileges of helper
pod from root to user.
BZ: #1991462
=> helper pod runs with non-root privileges

controllers/storagecluster/external_resources_test.go
Adding extra field in storageClass "dataPool" when pool is
erasure coded pool in case of RBD.
Links:
1) storageClass https://github.com/rook/rook/blob/master/deploy/examples/csi/rbd/storageclass-ec.yaml#L45
2) Json Blob in case of EC RBD pool https://github.com/rook/rook/pull/9276#issuecomment-992107767
=> External: configure sc properties for external cluster EC RBD pool

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/generate.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storageclasses_test.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Add a new encrypted RBD storage class during cluster deployment, if the customer asked for PV encryption.
URL: https://issues.redhat.com/browse/RHSTOR-2269
=> Add encrypted RBD storage class during deployment

controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/cephconfig.go, controllers/storagecluster/cephconfig_test.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/cephobjectstoreusers.go, controllers/storagecluster/cephrbdmirrors.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/job_templates.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go, controllers/storagecluster/provider_server.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/routes.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storagequota.go, controllers/storagecluster/storagequota_test.go, controllers/storagecluster/topology.go, controllers/storagecluster/uninstall_reconciler.go, controllers/storagecluster/uninstall_reconciler_test.go, controllers/storagecluster/volumesnapshotterclasses.go
With the current resourceManager interface there is no way to
communicate the reconcile.Result back to the reconcilePhases as it only
returns the error.
change the interface signature to return the reconcile.Result as well
with the error.
Why?
The change is required for ocs to ocs where we want to communicate the
reconcile.Result to the reconcilePhases.
While making GPRC calls we will get different error codes and based on
those error codes we will decide whether we need to requeue or not if
requeue when to requeue and this can be done with reconcile.Result. With
the existing design, we can return only errors and reconcile will get
requeue. That's why we are changing the interface to return the
reconcile.Result also.
Usecase:
let's say a user will create a storageCluster CR with the wrong …
=> controllers: change resourceManager interface

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/kms_resources.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storageclasses_test.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Introducing new KMS features in 4.10:
1. Vault Kubernetes service account-based authentication: 
- The Kubernetes auth method can be used to authenticate with Vault using a Kubernetes Service Account Token.
Steps to enable Kubernetes to service account based auth is:
1. To configure vault:
https://github.com/rook/rook/blob/master/tests/scripts/deploy-validate-vault.sh#L173
```
ConfigMap: ocs-kms-connection-details
data:
KMS_PROVIDER: vault
KMS_SERVICE_NAME: // name for this config
VAULT_AUTH_KUBERNETES_ROLE: //required
VAULT_AUTH_METHOD: kubernetes
VAULT_CLIENT_CERT: //optional
VAULT_NAMESPACE: //optional
VAULT_CACERT: //optional
VAULT_TLS_SERVER_NAME: //optional
VAULT_CLIENT_KEY: //optional
VAULT_BACKEND_PATH: //optional
VAULT_ADDR: //required
```         
2. IBM HPCS: …
=> Adding vault service account and ibm key protect based KMS encryption support

hack/build-operator-index.sh
opm uses podman by default, with --container-tool it will use the given
one.
=> hack: Add --container-tool argument in opm command while building index

services/provider/client/client.go, services/provider/server/server.go
- Use `DialContext` instead of `Dial`. This helps to pass context with
timeout.
- Update NewGRPCConnection to create DialOption
- Remove `localhost` from server address
=> update mock provider api

must-gather/templates/pod.template
stop using tini in must gather helper pod template. This is the only
the place we are using tini.
=> must-gather: stop using tini in must gather helper pod

controllers/storagecluster/external_resources.go
after restarting a operator it was getting returned if there is no
change in the secret without saving the secret into the map and
cephcluster func is complaining that it can not found the secret in the
map. change the order of the if statement to always save the secret data
in the map.
=> controllers: always fetch the secret and store it in the map

controllers/ocsinitialization/ocsinitialization_controller.go
This commit updates the configmap rook-ceph-operator-config
to include CSI_ENABLE_CSIADDONS: "true" so that rook can deploy
ceph-csi with csi-addons sidecar
BZ: #2043028
=> enables csi-addons sidecar in configmap

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/noobaa_system_reconciler.go
For HPCS KMS, UI creates a `Secret` (containing `IBM_KP_SERVICE_API_KEY` & `IBM_KP_CUSTOMER_ROOT_KEY`) in `openshift-storage` namespace. Name of that `Secret` needs to be passed in:
```
cephCluster.Spec.Security.KeyManagementService.TokenSecretName
nooBaa.Spec.Security.KeyManagementService.TokenSecretName
```
BZ#2047201
Signed-off-by: SanjalKatiyar <sanjaldhir@gmail.com>
=> Add HPCS secret name to Ceph and NooBaa CR

services/provider/main.go, services/provider/server/consumer.go, services/provider/server/consumer_test.go, services/provider/server/server.go
This PR implements the gRPC provider api-server. 
Pending items that will be taken up an follow up PR:
=> ocs-to-ocs: Implement provider api server

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/external_ocs.go, controllers/storagecluster/reconcile.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
remove connectionString and create 2 new fields:
- OnboardingTicket
- ExternalServerAddress
=> api: split connection string into 2 new fields

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/external_ocs.go, controllers/storagecluster/provider_server.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
StorageProviderEndpoint will be used to save the endpoint info on the
provider cluster.
=> api: Add StorageProviderEndpoint field in the storageCluster status 

controllers/storagecluster/reconcile.go
Allow user-defined custom storgaeclass names in Overprovision
definition, so users can define quota for future storageclasses, which
are not available during deployment time.
Refs BZ-2024545
=> storagecluster: allow any storageclass for storagequota

controllers/storagecluster/job_templates.go, controllers/storagecluster/job_templates_test.go
adding option to expose `--force-osd-removal` `<true/false>`.
It will help when Ceph indicates the OSD is not safe-to-destroy.
=> expose option to force remove the OSD in osd removal template

controllers/storagecluster/provider_server.go, deploy/bundle/manifests/provider-role.yaml, rbac/provider-role.yaml
Nodes are cluster scoped resources and should not be listed within
the namespace.
=> controllers: Do not list node in the namespace

controllers/storageconsumer/storageconsumer_controller.go
Removed volumegroup path from osd caps in cephClientCephFSProvisioner
and cephClientCephFSNode. Added mds caps cephClientCephFSProvisioner.
=> StorageConsumer: fix caps for cephClientCephFSNode and cephClientCephFSProvisioner

controllers/storagecluster/external_resources.go
Storage Consumer should only call the `UpdateCapacity` grpc if the `Requested` and `Granted` capacity are different. 
=> update capacity only if requested and granted capacity are different

services/provider/server/server.go
OnboardingTicket expiryData is int64 which can't be unmarshalled from
string value.  This PR fixes the following issue with unmarshalling of the `onboardingTicket` struct
```
onboarding ticket is not valid. failed to unmarshal onboarding ticket message. json: cannot unmarshal string into Go struct field onboardingTicket.expirationDate of type int64"
```
=> fix onboardingTicket unmarshalling

deploy/bundle/manifests/provider-role.yaml, rbac/provider-role.yaml, services/provider/server/server.go
- adds rule to read `cephfilesystemsubvolumegroups` for provider api server deployment.
- adds rookCephv1 to provider api scheme to read `cephclient` and `cephfilesystemsubvolumegroups`
=> Update rbac to correctly read rook resources

services/provider/server/server.go
If the updateCapacity grpc call is successfull, that is, the
storageConsumer is updated succcessfully, then return requested
capacity back as the granted capacity
Note:  This is a temporary solution for 4.10.  Ideally, we should check if the cluster if the provider cluster has atleast x amount of storage available for updating the capacity for the storage consumer. 
=> Return granted capacity in UpdataCapacity grpc response

controllers/storagecluster/cephconfig.go
To make sure the OSD get 4G memory and not 2.5G
=> rook-ceph: change osd_memory_target value to 0.8

controllers/storagecluster/external_ocs.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/reconcile.go
* updateConsumerCapacity was logging an error returning nil if
RequestedCapacity is not equal to the GrantedCapacity. Instead
we should log an warning and should not return.
* controllers: rename isExternalOCSProvider to isOCSConsumerMode
=> ocs to ocs: small general fixes

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/alerts-external.libsonnet, metrics/mixin/alerts/alerts.libsonnet, metrics/mixin/rules/rules.libsonnet
In order to make the 'odf_system_iops_total_bytes' recording rule to
collect more granular metric data points, we are decreasing the
recording rule group's time interval to 30s (where default is 1m).
=> Decreasing the timeout of 'ODF_standardized_metrics.rules' group to 30s

controllers/storagecluster/external_resources.go, controllers/storagecluster/external_resources_test.go, controllers/storagecluster/storageclasses.go
PV resize of encrypted volume is not officially supported in ODF 4.10
Hence, setting allowVolumeExpansion parameter of storage class
to False. This PR reverts 8ee4f858563c016f59804aea357d6d00ac50ab11
and addresses https://github.com/red-hat-storage/ocs-operator/pull/1558/files#r813956062
Signed-off-by: Afreen Rahman <afrahman@redhat.com>
=> [review comment] Set allowVolumeExpansion to False for encrypted SC

controllers/storagecluster/storageclasses.go
PV resize of encrypted volume is not officially supported in ODF 4.10
Hence, setting allowVolumeExpansion parameter of storage class
to False.
Signed-off-by: Afreen Rahman <afrahman@redhat.com>
(cherry picked from commit ca720eee21892360cc61a910ef3e4ccb28a2520c)
=> Bug 2044288: [release-4.10] Set allowVolumeExpansion to False for encrypted SC

controllers/storagecluster/external_resources_test.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller_test.go, controllers/storagecluster/uninstall_reconciler.go, controllers/storagecluster/uninstall_reconciler_test.go
while onboarding we are not able to update the status of the
storagecluster and we loose the storagecosumer id, there is not a really
easy way to get the consumer id again. Returning exactly after updating
storagecluster will reduce the chances of onboarding to be failed.
Update will trigger a new reconcile itself so we don't even have to
requeue at all.
https://bugzilla.redhat.com/show_bug.cgi?id=2056634
=> controllers: exit reconcile loop immediately after updating the storagecluster annotations

controllers/storagecluster/uninstall_reconciler.go, controllers/storagecluster/uninstall_reconciler_test.go
To properly trigger the new uninstallation logic in Rook-Ceph for a
"graceful" uninstall, we need to mark the CephCluster for deletion
towards the start of the process. This is how we inform Rook-Ceph that a
cluster deletion is in progress.
=> uninstall: delete CephCluster at the start of uninstall

controllers/defaults/placements.go, controllers/storagecluster/cephrbdmirrors.go
This commit adds default OCS toleration rbd-mirror pod to allow it to be
run on nodes with OCS taints.
Fixes : https://bugzilla.redhat.com/show_bug.cgi?id=2057489
=> Add default toleration to rbd-mirror pod

services/provider/server/server.go, services/provider/server/server_test.go
OCS provider server checks for `healthChecker` annotation on the client
but the actual annotation is `healthchecker`. This PR changes
`healthChecker` to `healthchecker`.
=> validate correct cephUserType annotation

controllers/storagecluster/cephcluster.go
Verify the monitoring endpoints only once while cephcluster is created.
=> Reset external resource cache when monitoring endpoints are not reachable

services/provider/server/server.go, services/provider/server/server_test.go
due to recent change where we introduced shorter names
for cephClient it required to change healthchecker cephclient
also due to this, we were getting failure during onboard.
=> ocs-to-ocs: correct the name of healthchecker cephclient

controllers/storagecluster/uninstall_reconciler.go, controllers/storagecluster/uninstall_reconciler_test.go
The func verifyNoStorageConsumerExist is called at 2 places and one of
them is uninstall and the other one is not. Using uninstall keyword
create a confusion among the user.
https://bugzilla.redhat.com/show_bug.cgi?id=2062990
=> controllers: correct logging of verifyNoStorageConsumerExist func

controllers/storagecluster/uninstall_reconciler.go
The func verifyNoStorageConsumerExist is called at 2 places and one of
them is uninstall and the other one is not. Using uninstall keyword
create a confusion among the user.
(cherry picked from commit 94c993a86f0f8ded2b7096287c3adca263f92ba0)
Backport of https://github.com/red-hat-storage/ocs-operator/pull/1586
=> Bug 2062990:[release-4.10] controllers: correct logging of verifyNoStorageConsumerExist func

must-gather/collection-scripts/gather_namespaced_resources
This commit verifies if the openshift-dr-system namespace is
present or not before collecting the logs for Ramen artifacts.
=> Add check  to verify the presence of openshift-dr-system ns

must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_namespaced_resources
this coomit collect yamls and describe outputs of the
new CRs created for ODF to ODF Managed services in 4.10
=> must-gather: adds output for crds of managed services

controllers/storagecluster/reconcile.go
We were setting `Upgradable: false` in some cases but we
never set it to `Upgradable: true` for external mode
deployments. This caused further upgrades to be blocked.
This commit changes that behavior to set `Upgradable: true`
even for external mode deployments when none of the components
report an error.
(cherry picked from commit 4b9d1286bfd6023ca0a18d5b6db2bf783ad0963f)
Backport of #1597
=> Bug 2066997: [release-4.9] set upgrade conditions in external mode deployment

controllers/storagecluster/reconcile.go
We were setting `Upgradable: false` in some cases but we
never set it to `Upgradable: true` for external mode
deployments. This caused further upgrades to be blocked.
This commit changes that behavior to set `Upgradable: true`
even for external mode deployments when none of the components
report an error.
=> set upgrade conditions to true in external mode deployment

must-gather/collection-scripts/gather_ceph_resources
This commit resolves a small syntax error
due to which the ceph collection was showing error
=> cleanup: resolve syntax error

controllers/storagecluster/routes.go
The route for cephobjectstore does not define termination policy in TLS
config of the Spec and this PR defines one. With this change only
`https` endpoint of RGW will exposed via route.
=> add termination policy to TLS in cephobjectstore route

must-gather/collection-scripts/gather_clusterscoped_resources, must-gather/collection-scripts/gather_namespaced_resources
The volumesnapshot, volumesnapshotcontent and volumesnapshotclass
are all collected for openshift-storage namespace.
This commmit collects the volumesnpashot for all namespace and
volumesnapshotcontent and volumesnapshotclass being clusterscoped resources,
don't need to be collected in namespaced resource.
issue: #1620
=> must-gather: collect volumesnapshot of all namespaces

services/provider/server/server.go, services/provider/server/server_mock.go
Mock calls were required during initial phase for testing the server and
should not be part of the actual server implementation.
=> server: remove mock calls from the actual server

controllers/storagecluster/generate.go
fixed the issue of cluster resource quota names having double ocs
prefix.
Signed-off-by: riya-singhal31 <riyasinghalji@gmail.com>
=> fix cluster resource quota names containing double ocs prefix

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
This flag is used to disable UI components in Console.
Used to track migration of features from OCP to ODF.
Signed-off-by:  SanjalKatiyar <sanjaldhir@gmail.com>
=> Add an annotation to disable wizard flow in console

controllers/storagecluster/storageclasses.go, services/provider/server/server.go
update the image feature from layering to layering,exclusive-lock,object-map,fast-diff as this is required to enable the DR workflow on the rbd images created by this storageclass, and also it provides more crash consistent rbd snapshots.
PS: Minimum kernel version required to map images
created from this storageclass is 8.2+
=> update imagefeature in rbd storageclass

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, go.mod, go.sum, hack/common.sh, vendor/github.com/ceph/ceph-csi/api/deploy/ocp/scc.yaml, vendor/modules.txt
- update ceph-csi api to add nfs sa
This commit updates `github.com/ceph/ceph-csi/api`
so nfs sa is added to `rook-ceph-csi` scc.
Signed-off-by: Rakshith R <rar@redhat.com>
- use k8s.gcr.io for csi nfsplugin image
Use k8s.gcr.io like other kubernetes sidecar
image to pull the nfsplugin image.
Signed-off-by: Rakshith R <rar@redhat.com>
/cc @Madhu-1 @agarwal-mudit @nixpanic @BlaineEXE
=> Update ceph-csi/api and use k8s.gcr.io for csi nfsplugin image 

must-gather/collection-scripts/gather_ceph_resources
This commit adds code to empty the pids for further
resource collections as it is crossing the limits and
as the result rbd mirroring info is not being collected
=> must-gather: empty the pids as it is exceeding the limits

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, hack/common.sh
Ceph now pushes latest images to quay only.
This will ensure we are using the latest ceph
pacific image.
Signed-off-by: Rakshith R <rar@redhat.com>
/cc @agarwal-mudit @iamniting @Madhu-1
=> use `quay.io/ceph/ceph:v16` for ceph image

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Added flags are used to disable UI components in Console.
Used to track migration of features from OCP to ODF.
Signed-off-by: SanjalKatiyar <sanjaldhir@gmail.com>
=> Add an annotation to disable components flow in console

must-gather/collection-scripts/gather_ceph_resources
This commit separates the collection of rbd vol info and
rbd snap ls as the single file was unreadable and
difficult to debug.
=> must-gather: serialize collection of rbd_vol and snap info

must-gather/collection-scripts/gather_ceph_resources
This commit collects the rbd mirror info in different
files for clear debuging.
=> must-gather: collect mirroring resources in separate files

api/v1alpha1/storageclassclaim_types.go, config/crd/bases/ocs.openshift.io_storageclassclaims.yaml, deploy/bundle/manifests/storageclassclaim.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclassclaims.yaml
add phase and storagetype to the kubectl get operation as its helps to get an idea of what the claim is without checking the yaml output.
/assign @umangachapagain 
/assign @nb-ohad
=> add more details to kubectl get operation

deploy/bundle/manifests/provider-role.yaml, rbac/provider-role.yaml, services/provider/server/server.go, services/provider/server/server_test.go, services/provider/server/storageclaim.go
* Improve logging in storageclass claim to help to debug in error cases.
* The storageType should be of type string sharedfilesystem or blockpool when creating the storageclassclaim CR it's not always the string format of the auto generated RPC names.
* Added RBAC role for provider api-server for the storageclassclaim CR.
* The fsName is the key in the storageclass parameters matching the key to sending back in GetStorageClassClaimConfig to create the storageclass
* Get operation on the consumer will not have the TypeMeta objects set causing the problem of setting the ownerRef, use the helper function to set the ownerRef
/assign @umangachapagain 
/assign @nb-ohad 
/assign @iamniting
=> Fix bugs found in the testing

controllers/storagecluster/external_resources.go
In case of OCS to OCS, consumer OCS cluster has a default
CephFS based StorageClass. So, to allow PV creation using
this StorageClass CephFS CSI driver should also be enabled
by default.
This PR skips the toggle added in #701.
=> ocs-to-ocs: revert disabling cephfs csi driver

controllers/storageclassclaim/storageclassclaim_controller.go, deploy/bundle/manifests/provider-role.yaml, rbac/provider-role.yaml
=> ocs-to-ocs: fix: rbac and GVK
