hack/ticketgen/ticketcheck.sh, hack/ticketgen/ticketgen.sh
Some platforms do not default to using SHA256 for digests, instead
using MD5. On one of those platforms, a token will fail verification
at the provider since it explicitly verifies using SHA256.
=> Make use of SHA256 digests explicit

services/provider/server/server.go
Currently the server was overriding the mon endpoints cm
with only 1 mon-IP,
Updated it to add all the 3 mon IPs
Signed-off-by: parth-gr <paarora@redhat.com>
=> update rook-ceph-mon endpoints cm

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Removed a flag which is disabling UI components in Console.
Used to track migration of features from OCP to ODF.
Signed-off-by: SanjalKatiyar <sanjaldhir@gmail.com>
=> Remove annotation to enable add-capacity for csv

metrics/internal/collectors/rbd-mirror.go
+ Check length after splitting string to ensure we have the expected data and we don't end up with IndexOutOfBound error.
+ Remove primary/non-primary check on image to ensure we don't miss negative states.
=> metrics-exporter: add checks to prevent crash

metrics/internal/cache/rbd-mirror.go
When debug log is enabled in rbd mirror daemon, rbd cli
commands dump a lot of non json output along with the
expected json. This causes json parsing to fail and disrupts
metrics collection.
This commit adds  "--debug-rbd 0" to ignore debug logs and get
valid json for metrics generation.
=> metrics-exporter: ignore rbd daemon debug logs

metrics/internal/cache/rbd-mirror.go, metrics/internal/collectors/registry.go
rbd-mirror collector requires credentials from Ceph to collect data.
If Ceph is not available, rbd-mirror metrics will not be available.
We fetch credentials from Rook when an add or resync event is
received on CephBlockPool object. This helps us avoid pre-fetching
credentials and keeps the credentials updated.
=> metrics: fetch creds during add & resync events

api/v1/storagecluster_types.go
The toolbox doesn't need to run privileged. Rook's upstream toolbox
spec hasn't had the privileged flag since Rook v1.1, which was the
basis for OCS 4.3. The privilged acces gives a warning message seen
in the OCS operator log file. So updating the newToolsDeployment
according to the upstream rook toolbox spec.
BugZilla link - https://bugzilla.redhat.com/show_bug.cgi?id=2027724
Upstream Rook ToolboxSpec - https://github.com/rook/rook/blob/master/deploy/examples/toolbox.yaml
=> Update newToolsDeployment according to upstream rook toolbox spec

controllers/storageclassclaim/storageclassclaim_controller.go, controllers/util/k8sutil.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, main.go, tools/csv-merger/csv-merger.go
Whenever a claim is created in namespaces other than `openshift-storage` namespace we are failing to list the storagecluster because we are trying to list the storagecluster on the namespace where the claim is created and also
we are creating the ceph resources on the namespace where the claim is created but we should not do it we should only create the claims in the namespace where operator is running.
=> fix namespace problem in storageclassclaim controller

controllers/storagecluster/external_resources.go, controllers/storagecluster/provider_server.go, controllers/storagecluster/provider_server_test.go
We were using service of type NodePort which is prune to failures
whenever a used node goes down or removed from a OCP cluster.
Start using the service of type LoadBalancer which creates a external IP
which can be used via consumers.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2060487
=> odf to odf: start using LoadBalancer type for ocs-provider-server svc

must-gather/collection-scripts/gather_ceph_resources
This commit chnages NODE_OUTPUT_DIR to
VOLUME_OUTPUT_DIR as the NODE_OUTPUT_DIR doesn't exists.
And we are creating VOLUME_OUTPUT_DIR to collect volume logs
=> cleanup: No NODE_OUTPUT_DIR to collect volume logs

controllers/storagecluster/external_resources.go
This commits handles the upgrade where ROOK_CSI_ENABLE_CEPHFS is set to false in 4.10 we need to change it back to true
to enable cephfs in 4.11
=> enable cephfs in consumer mode.

controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go
Flag 'sc.Spec.Encryption.Enable' is deprecated and now we use
'sc.Spec.Encryption.KeyManagementService.Enable'.
=> Fix KMS regression in MCG deployment

controllers/storageclassclaim/storageclassclaim_controller.go
Fail if `encryptionMethod`s are not the same for SC and SCC.
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>
=> Fix `encryptionMethod` condition

controllers/storagecluster/provider_server.go
In ODF v4.10.z the providerService is of type nodePort so the consumer
can give any worker nodeIP:31659 to connect with the provider. But in
ODF v4.11.z this service is changed to the service of the type of
loadBalancer where the consumers will need to update the
storageProviderEndpoint to hostname:50051. The consumers won't
be able to reach out to the provider unless the storageProviderEndpoint
is updated.
Create both the services to allow consumers still be connected and
change the storageProviderEndpoint as per their cadence.
=> odf to odf: keep the old nodeport provider service

config/rbac/role.yaml, controllers/storageclassclaim/storageclassclaim_controller.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in, services/provider/server/server.go, services/provider/server/server_test.go
When we storageclassclaim is created we are creating the storageclass object for it. Like storageclass, we need to create the volumesnapshotclass to support snapshot functionality.
cc @nb-ohad 
/hold still need testing
=> Add support to create volumesnapshotclass per storageclassclaim

controllers/storagecluster/cephconfig.go
Currently, the user has to set this value ceph config set global rbd_mirror_die_after_seconds 3600 via the toolbox,
and that is not a good way for the customer as they don't have toolbox access. So setting this value in the rook-config-override 
configmap.
Note- it will work on fresh clusters not on the upgraded cluster as someone needs to restart rook pods after this configuration is applied
BZ Link-
[https://bugzilla.redhat.com/show_bug.cgi?id=2093266](https://bugzilla.redhat.com/show_bug.cgi?id=2093266)
=> Enable rbd-mirror daemon restart config automatically

controllers/storagecluster/generate.go, controllers/storagecluster/volumesnapshotterclasses.go
For external restriced mode the csi-secrets name will
not be default, so updating the name accordingly in the
volume snapshot class so snapshots can work
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2091998
Signed-off-by: parth-gr <paarora@redhat.com>
=> ocs: Update Volume Snapshots secret name generation

must-gather/collection-scripts/gather_ceph_resources
**Description:**
Removed the hardcoded svg, and added command to fetch the list of
subvolumegroups for each filesystem and get the subvols, snapshots for
each of them
Fixes: #1596
Signed-off-by: nik-redhat <nladha@redhat.com>
=> must-gather: removes hardcoded subvolumegroup

api/v1alpha1/storageclassclaim_types.go, controllers/storageclassclaim/storageclassclaim_controller.go, controllers/storagecluster/external_ocs.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller.go, controllers/storagecluster/volumesnapshotterclasses.go
when upgrading from 4.10 to 4.11 default storageClassClaim(scc)
where not created. Now, in ensureCreated method we'll add a
check is scc is not created but sc is present without
annotation then we'll create the default scc.
=> odf-to-odf: create default scc when updgrading

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/platform_detection.go
CephObjectStore is disabled for all cloud platforms
Earlier, we were disabling it for IBMCloud only if COS was used as default backing store
However, with this change, we are disabling it for IBM Cloud platform irrespective of COS being used for backing store
=> disable cephObjectStore for IBMCloud

controllers/storageclassclaim/storageclassclaim_controller.go
when checking the existing storageclass the parameter
mentioned was wrong instead of this `existing.Parameters["encryptionMethod"]` it will be `existing.Parameters["encryptionKMSID"]`
https://github.com/rook/rook/blob/master/deploy/examples/csi/rbd/storageclass.yaml#L57
=> odf-to-odf: wrong parameter in storageclass

controllers/ocsinitialization/ocsinitialization_controller.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Going forward the configmap created by ocsinitialization will be
reserved purely for customer overrides (higher precedence), and
the csv will have the env vars for our defaults.
We had discussed this here in odf virtual teams space, 
[https://chat.google.com/room/AAAAREGEba8/JO7SyyGIA0k](https://chat.google.com/room/AAAAREGEba8/JO7SyyGIA0k)
Also the corresponding BZ link for the discussion that happened there.
[https://bugzilla.redhat.com/show_bug.cgi?id=1986016](https://bugzilla.redhat.com/show_bug.cgi?id=1986016)
=> Moving the defaults for rookceph operator from configmap to csv

must-gather/collection-scripts/gather_ceph_resources
It is needed to get "complete" field for primary mirror snapshots and
"last_copied_object_number" field for non-primary mirror snapshots.
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
=> must-gather: collect JSON output for "rbd snap ls --all" as well

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Refers- [RHSTOR-3627](https://issues.redhat.com/browse/RHSTOR-3627)
instead of just having one CSI_LOG_LEVEL, we are adding
one more control for sidecar logs. The default value, for
now, would be "1".
More implementation-related details are here-
[ceph/ceph-csi/pull/3264](https://github.com/ceph/ceph-csi/pull/3264)
[rook/rook/pull/10639](https://github.com/rook/rook/pull/10639)
=> Enable adjustable control for sidecar logs

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/external_resources_test.go
We recently merged [ocs-operator/pull/1648](https://github.com/red-hat-storage/ocs-operator/pull/1648), in which we moved the configurations from the CM to csv env. But we forgot to initialize the CM while it's being created, which may create unexpected behavior elsewhere.
And we also forgot to clean up the externalresources_test, which had tests for those variables which we moved.
=> Initialize the rookcephoperatorconfig CM while creation & cleanup externalresources test

.golangci.yaml, controllers/storageclassclaim/storageclassclaim_controller.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/generate.go, hack/golangci_lint.sh
This is to help debug problems when running in the OpenShift CI, but
also should be generally useful.
=> hack: make golangci-lint.sh more verbose

must-gather/collection-scripts/gather_namespaced_resources
The output of `oc get pods -owide` is collected
twice in must-gather.
1. As pods -owide
2. As all -owide
This commit removes collecting output of get pods
-owide separately
=> must-gather: removes duplicate pods -owide output

controllers/storagecluster/external_resources.go
We do not want to disable CephFS CSI driver in consumer mode since
CephFS storageclass is available by default.
This is a fix for the problem that ROOK_CSI_ENABLE_CEPHFS is "false" after upgrading the provider cluster alone to ODF 4.11.0.
Fixes-
https://bugzilla.redhat.com/show_bug.cgi?id=2110274
https://bugzilla.redhat.com/show_bug.cgi?id=2107073
This is the manual backport of this PR-https://github.com/red-hat-storage/ocs-operator/pull/1710.
Which was a fix for https://bugzilla.redhat.com/show_bug.cgi?id=2096823. A manual backport was chosen as there was a chain of merge conflicts with automated cherry-pick.
=> Bug 2107073: [release-4.10] mark enableRookCSICephFS as true always in consumer cluster

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/ocsinitialization/ocsoperator_config.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Refers-https://issues.redhat.com/browse/RHSTOR-3269
**Add two new variables for Ceph-CSI to set as metadata on RBD & CephFS**
CSI_ENABLE_METADATA variable is set directly & CSI_CLUSTER_NAME
is set from a configmap named ocs-operator-config.
Both of them can be overridden by editing the CM
rook-ceph-operator-config to add these value & setting it to any
required value.
**Add new configmap ocs-ocsoperator-config for pure ocs-operator use**
This configmap is used only for configuration in the ocs-operator.
Customer changes should not be made on this. This Can be useful in
cases where we have to get something during the runtime and set
that somewhere.
=> Add two new variables for Ceph-CSI to set as metadata on RBD & CephFS

controllers/storagecluster/prometheus/localcephrules.yaml
The name kube_pv is misleading as the it only represents ODF PVs, thus
we need to rename them to make it easier to understand.
Story: https://issues.redhat.com/browse/RHSTOR-3472
=> rename kube_pv and add LVM pvs count

pkg/controller/storagecluster/reconcile.go
adding option to expose --force-osd-removal <true/false>.
It will help when Ceph indicates the OSD is not safe-to-destroy.
=> Bug 2119517: [release 4.6] expose option to force remove the OSD in osd

controllers/storagecluster/reconcile.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, hack/source-manifests.sh
adding option to expose `--force-osd-removal` `<true/false>`.
It will help when Ceph indicates the OSD is not safe-to-destroy.
=> Bug 2119516:[release-4.7]expose option to force remove the OSD in osd

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
We don't want to enable metadata for CSI driver by default.
If a customer wants to enable metadata they can edit the
rook-ceph-operator-config cm to set CSI_ENABLE_METADATA to true.
oc patch cm rook-ceph-operator-config -p $'data:\n "CSI_ENABLE_METADATA":  "true"'
=> Set CSI_ENABLE_METADATA by default false

controllers/storagecluster/reconcile.go, controllers/storagecluster/storageclasses.go
Resolve: https://bugzilla.redhat.com/show_bug.cgi?id=2004027
**Stop setting storagecluster to error phase just after creation**
While storageclasses are being created it's waiting till underlying
resources like cephBlockPool, cephFilesystem & NFS are created.
In this phase, we are returning an error which results in the phase of the
storagecluster to be in Error Phase creating confusion for the user.
So henceforth this particular error would be caught, A requeue
Reconcile result would be given and the storagecluster would be marked
as in the Progressing Phase.
=> Fix StorageCluster is in error state for few minutes after installing

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/kms_resources.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go
Adding new KMS (Thales), support added from UI, ceph-csi, rook and noobaa.
Signed-off-by: sanjalkatiyar <sanjaldhir@gmail.com>
=> Integration with Thales enterprise key management

config/default/manager_auth_proxy_patch.yaml, config/default/manager_webhook_patch.yaml, config/manager/manager.yaml, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in
run containers as allowPrivilegeEscalation:false
resolves- https://bugzilla.redhat.com/show_bug.cgi?id=2114847
drop all default capabilities for containers
resolves- https://bugzilla.redhat.com/show_bug.cgi?id=2114844
run pods as runAsNonRoot: true
resolves- https://bugzilla.redhat.com/show_bug.cgi?id=2114840
=> Security fixes: privilege escalation control, run as non root, drop capabilities

must-gather/collection-scripts/gather_ceph_resources
Add ceph log last commands to collect ceph cluster
logs to ease debugging from RADOS perspective. 
NOTE: Currently, the ceph log last command returns only
50 cluster log entries at max even if we specify 10000
(mon_log_max) log entries to be retrieved in the log
last command. This will be fixed with ceph PR#47873.
Signed-off-by: Prashant D <pdhange@redhat.com>
=> must-gather: add ceph log last commands

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/internal/collectors/object-bucket.go, metrics/mixin/rules/rules.libsonnet
this commit adds metrics for total number of objects in the rgw buckets
created by the user, also adds the number of object bucket.
Jira Issue: https://issues.redhat.com/browse/RHSTOR-3471
=> add metrics for total objects and bucket count

controllers/storagecluster/storageclasses.go
Was using the failureDomain as the poolName in the non-resilient pool storageclass. This is incorrect. The poolName should be the name of the pool which is the failureDomainValue.
This was mistakenly left from this PR https://github.com/red-hat-storage/ocs-operator/pull/1782.
=> Give correct name for poolName in the non-resilient pool storageclass

controllers/storagecluster/prometheus/localcephrules.yaml
Alerts, 'CephOSDVersionMismatch' and 'CephMonVersionMismatch' had a
minor issue in the query. Earlier we were counting a combination of
'namespace' and 'ceph_version', but in actual we should count
only by 'namespace' (for the second count) thus making sure we don't
have more than one ceph versions in a single namespace.
=> Fix 'CephOSDVersionMismatch' and 'CephMonVersionMismatch' alerts

config/rbac/role.yaml, controllers/storagecluster/reconcile.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in, main.go
This commit adds permissions for clusterserviceversions and adds it to the client scheme when the operator is started.
Also adds clusterv1alpha1 package to the client scheme
Signed-off-by: Vineet Badrinath <vineetbnath@gmail.com>
=> Bug 2125958: Add permissions to storagecluster reconciler

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/rules/rules.libsonnet
Remove the labels to reduce the cardinality for the odf_system_bucket_count and odf_system_objects_total metrics.
=> reduce cardinality for odf_system_bucket_count and odf_system_objects_total

controllers/storageclassclaim/storageclassclaim_controller.go
Found two bugs in the storageclassclaim controller for the storageprofile epic
* We cannot slice uuid.New directly, it will result in some invalid chars, we need to convert uuid to string and then slice it.
* The Pool name is always filesystemname-storageprofilename as rook creates the data pools with filesystemname-storageprofilename name.
=> fix bugs in storageclassclaim controller for storageprofile

Dockerfile, metrics/Dockerfile
=> Upgrade ocs metrics exporter & ocs operator to use golang 1.18 image

controllers/storageclassclaim/storageclassclaim_controller.go, main.go
When a storageclassclaim CR is created, a Reconcile is triggered. We are using controller runtime client does GET operation which reads from the runtime cache. When a blockpool or subvolumegroup is created, a new reconcile request will be in the queue until the existing Reconcile completes. Once the existing Reconcile completes, we will get Reconcile request for the resource in the queue and try to get the storageclassclaim object here. We have a chance to get the object from the runtime cache instead of fetching it from the apiserver. Because of it, we get stale resources created for subvolumegroup and blockpool.
As a workaround for the above problem, wait for  Cache to be synced during start of Reconcile.
=> WaitForCacheSync in storageclassclaim Reconcile

metrics/Dockerfile
=> use go1.18 for metrics exporter development builds

.github/workflows/ocs-operator-ci.yaml, .golangci.yaml, Makefile, api/v1alpha1/groupversion_info.go, controllers/ocsinitialization/ocsinitialization_controller.go, controllers/ocsinitialization/ocsinitialization_controller_test.go, controllers/storageclassclaim/storageclassclaim_controller.go, controllers/storagecluster/external_resources_test.go, controllers/storagecluster/placement.go, controllers/storagecluster/provider_server.go, controllers/storagecluster/storagecluster_controller.go, controllers/storagecluster/storagecluster_controller_test.go, controllers/storagecluster/uninstall_reconciler.go, controllers/storagecluster/uninstall_reconciler_test.go, functests/common.go, hack/golangci_lint.sh, hack/verify-operator-bundle.sh, metrics/internal/collectors/object-bucket_test.go, metrics/internal/exporter/registry.go, pkg/deploy-manager/common.go, pkg/deploy-manager/config.go, test/crd_validation_test.go, tools/cluster-deploy/cluster-deploy.go, tools/csv-merger/csv-merger.go
...that merged too early in #1814 ;)
The golangci-lint changes were tricky, but basically it comes down to some weirdness in running it using Go 1.19 versus Go 1.18 for golangci-lint v1.49.0. Specifically, it was this change in 1.48.0 that was causing us so much pain: https://github.com/golangci/golangci-lint/pull/3002
In addition, the original configuration listed *both* `go-version` and `go-version-file` configuration options, and `go-version` was being taken as the preferred one. Unfortunately, our code still fails against Go 1.19 for some reason, so for the time being we're forcing the Action to target Go 1.18 across the job's config matrix. I kept the matrix at `["1.18","1.19"]` just so we don't have to change it later when we do start moving to 1.19. 
Signed-off-by: Jose A. Rivera …
=> Various fixes to initial GitHub Actions

controllers/defaults/placements.go, controllers/storagecluster/noobaa_system_reconciler.go
This PR adds a "noobaa-standalone" daemonplacement for MCG standalone deployment. This is required so that the user can set tolerations to the MCG pods in standalone mode as well via the storagecluster.
Associated BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2115613
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
=> add "noobaa-standalone" daemonplacement for MCG standalone deployment

metrics/internal/collectors/cluster-advance-feature-use.go
Add nil pointer check on ObjectStore collector to prevent crash when SecuritySpec is empty in CephObjectStore.
=> add nil pointer check to ObjectStore collector

controllers/storagecluster/cephconfig.go
Removed rbd_mirror_die_after_seconds from the rook configmap which got introduced in #1740 as this is fixed in ceph.
Ref BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2132366
/assign @idryomov 
/assing @ShyamsundarR 
/assing @malayparida2000
=> remove rbd mirror daemon restart config

pkg/deploy-manager/common.go
With ocp 4.12 secuirty contexts are strict requirements now. But we still need privileged containers like rook to run our operator. So we need to add labels to the namespace to bypass security context requirements during the e2e-test.
=> Add labels to the namespace to bypass security context requirements in e2e-test

config/samples/ocs_v1_storagecluster.yaml, controllers/storagecluster/cephcluster.go, controllers/storagecluster/storagecluster_controller_test.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in, docs/multus.md, pkg/deploy-manager/storagecluster.go, tools/csv-merger/csv-merger.go
[Change to use gp2-csi storageclass instead of gp2](https://github.com/red-hat-storage/ocs-operator/pull/1845/commits/65a2cd821bb930fd4909757d9042256d6ffa7faa) 
Starting with ocp 4.12 the gp2 storageclass is no longer available.
So we need to use gp2-csi storageclass instead.
=> Change to use gp2-csi storageclass instead of gp2 from 4.12 onwards

controllers/storagecluster/cephcluster.go
=> keep the gp2 SC to support the upgrades from OCP 4.11 to 4.12

.github/workflows/ocs-operator-ci.yaml
The code spell is failing due to the function name ShouldNot, used with ginkgo.
So adding it to ignore list.
=> Add ShouldNot to codespell ignore list as it's a function name in ginkgo

controllers/storagecluster/job_templates.go
we should not be using rook master tag in init container in product deployments
instead, we should be using rook version from env var.
=> Don't use rook master tag in Job

hack/install-noobaa-operator.sh
It will be necessary to install noobaa independently in order to remove the "noobaas.noobaa.io" requirement from the ocs-operator CSV. Noobaa-operator won't come along automatically with ocs-operator, but odf will include it in its dependencies.yaml and bring it along.
=> hack: create script to install noobaa-operator if does not exist for CI

deploy/bundle/manifests/exporter-role.yaml, metrics/deploy/rbac.yaml, metrics/internal/collectors/ocs-client.go, metrics/internal/collectors/registry.go, metrics/internal/collectors/storageconsumer.go, rbac/exporter-role.yaml
This PR creates a new metrics for  all the consumers connected to the   provider with additional metadata.
sample metric:
`ocs_storage_consumer_metadata{capacity="500",granted_capacity="500",state="Ready",storage_consumer_name="ocs-storageconsumer"} 1`
JIRA: [ODFMS-58](https://issues.redhat.com/browse/ODFMS-58)
Signed-off-by: Kaustav Majumder [kmajumde@redhat.com](mailto:kmajumde@redhat.com)
=> Added new metric for consumers connected to provider

controllers/defaults/defaults.go, controllers/storagecluster/cephcluster.go
Recently in upstream Rook we did make 2 mgrs the default, and it has been very stable so we need the OCS operator to make that the default as well.
Resolves-https://bugzilla.redhat.com/show_bug.cgi?id=2130266
=> Deploy two mgr pods in a cephcluster

controllers/storagecluster/external_resources.go, controllers/storagecluster/uninstall_reconciler.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2089446
delete rook-ceph-external-cluster-details Secret as a part of SS deletion.
Signed-off-by: sanjalkatiyar <sanjaldhir@gmail.com>
=> delete Secret for external RHCS

config/rbac/role.yaml, controllers/storagecluster/cephrbdmirrors.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller_test.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in, main.go
When mirroring is enabled it creates a enable job which runs the
required ceph config set commands to enable verbose logging.
When mirroring is disabled it creates a disable job which runs the
required ceph config rm commands to disable verbose logging and deletes
both the enable and disable jobs.
RBD team needs by default verbose logging when rbd-mirroing is enabled,
to debug issues properly. This would be reverted once RDR goes to GA.
Resolves-https://bugzilla.redhat.com/show_bug.cgi?id=2127186
=> Enable verbose logging when rbd mirroing is enabled for debugging

controllers/defaults/resources.go
Limit/request for the NooBaa Endpoint and Core pods is expected to be a fraction number, like 999m.
See
- https://bugzilla.redhat.com/show_bug.cgi?id=2123133
- https://github.com/noobaa/noobaa-operator/pull/830
Signed-off-by: Alexander Indenbaum <aindenba@redhat.com>
=> Update NooBaa core and endpoint default CPU resource values

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml
Ran `make gen-latest-prometheus-rules-yamls` to sync the changes in libsonnet files to metrics/deploy
(cherry picked from commit 50f09cbeb565fa7ea88ae89a7de04fffa02254a7)
=> Bug 2124280: [release-4.10] Sync all the libsonnet changes to metrics deploy files

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
disabling webhook for rook untill is officially supported
Backport of https://github.com/red-hat-storage/ocs-operator/pull/1895
=> Bug 2154165: disable webhook for rook

controllers/storagecluster/storageclasses.go
Normally the label on the nodes is of the form
kubernetes.io/hostname=<hostname> and the same is passed to ceph-csi
through rook-ceph-opeartor-config cm.
Hence, the domainLabel should be set as "hostname" instead of "host"
for topology constrained pools.
Resolves-https://bugzilla.redhat.com/show_bug.cgi?id=2155402
=> set domainLabel to "hostname" instead of "host" in topology constrained pool

controllers/storagecluster/prometheus.go, metrics/internal/collectors/object-bucket_test.go, test/crd_validation_test.go
io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code.
=> fix io/ioutil deprecation warning from golangci-lint run

hack/build-operator-bundle.sh
Fixes the Dockerfile path in the bundle build script which was broken after commit 50dcce2d5 (#1917 )
=> fix OCS Dockerfile path in bundle build script

controllers/storagecluster/exporter.go, controllers/storagecluster/prometheus.go
labels were not getting updated while updating the servicemonitor and prometheusrules. Only Spec is the one which was getting updated. With the fix labels will also get updated along with the spec.
=> update the labels while updating the servicemonitor and prometheusrules

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/ocsinitialization/ocsoperator_config.go, controllers/storagecluster/cephcluster.go, controllers/util/k8sutil.go, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
This commit enables read affinity for RBD volumes by setting the "CSI_ENABLE_READ_AFFINITY" environment variable to "true". If it is an external cluster, and the "CSI_ENABLE_READ_AFFINITY" variable is not present in rook-ceph-operator-config ConfigMap, only then it is set to false. This provides flexibility to use the configmap enable and modify this feature for external cluster.
refer: https://issues.redhat.com/browse/RHSTOR-4371
=> cephcluster: add support for read affinity for RBD volumes

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/ocs_operator_config.go, controllers/storagecluster/storagecluster_controller_test.go, deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Jira-https://issues.redhat.com/browse/RHSTOR-2516
For easier enablement of new features like in-transit encryption &
compression we need the ceph msgr v2 port. So we will use the msgrv2
port instead of the old v1 port by default.
The cephFS kernel mount option is set as a key in the ocsoperator
configmap. The value of the key is passed to rook as a env variable.
The default is "ms_mode=prefer-crc" and if in transit encryption is
enabled, the value is set to "ms_mode=secure". The rook operator
pod is restarted if the value of the key is changed.
=> Alwasy enable ceph msgrv2 port & pass kernel mount options to rook-ceph operator

config/rbac/exporter-role.yaml, deploy/csv-templates/ics-operator.csv.yaml.in, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, go.mod, metrics/deploy/prometheus-ocs-rules.yaml, metrics/deploy/rbac.yaml, metrics/internal/cache/ceph-blocklist.go, metrics/internal/cache/pv.go, metrics/internal/cache/rbd-mirror.go, metrics/internal/collectors/ceph-blocklist.go, metrics/internal/collectors/rbd-mirror.go, metrics/internal/collectors/registry.go, metrics/main.go, metrics/mixin/alerts/alerts.libsonnet, metrics/mixin/alerts/blocklist.libsonnet, metrics/mixin/config.libsonnet, metrics/mixin/rules/rules.libsonnet
In this PR, we are adding a new metric called ocs_rbd_client_blocklisted with the label node_name. This metric lists the nodes that are blocklisted in Ceph OSD blocklist ls.
The purpose of this metric is to check if the clients used for images being provisioned using rbd are blocklisted. If the kernel rbd client is blocklisted, the images can go into read-only mount. By monitoring this metric, we can identify which nodes are blocklisted and take appropriate actions to resolve the issue.
This PR aims to improve the monitoring and alerting capabilities of the Ceph cluster by adding this new metric.
Metrics example: 
```
ocs_rbd_client_blocksited{node_name="ip-10-0-138-1.ec2.internal"} 1
ocs_rbd_client_blocksited{node_name="ip-10-0-179-220.ec2.internal"} 0
```
Fixes: …
=> Add new metric for monitoring blocklisted RBD clients

controllers/storagecluster/reconcile.go, controllers/util/status.go
we are changing the conditions when cephcluster is in connecting state or error state and reflecting the ceph cluster state in the storagecluster conditions accordingly. But once ceph cluster is in connected state we are not changing the conditions at all. Which makes storagecluster conditions out of sync with the cephcluster when it is in connected state. updating the conditions when cephcluster is connected will reflect the actual state.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2172189
=> change the conditions when cephcluster is in connected state

controllers/storagecluster/ocs_operator_config.go
We are upgrading the ocs-operator configmap by adding a storage cluster as an controller, which breaks the upgrade because ocsinitialization is already a controller to it. Before we can add the storagecluster as an controller, we must first remove ocsinitialization as a controller from the owner references.
=> remove OCSInitialization controller ref from ocs-operator-config cm

controllers/storagecluster/job_templates.go
Previously once the template existed we were not reconciling it. This resulted in the template using very old rook-ceph images and not having the newly added parameters. We want the template to be updated to use new parameters, any new ceph commands, latest rook-ceph image, etc.
Fixes- https://bugzilla.redhat.com/show_bug.cgi?id=2143944
=> Reconcile the job templates so it is in sync with the latest changes

controllers/ocsinitialization/ocsinitialization_controller.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
This is an modified cherry-pick of #1648, where we are only backporting the CSI_LOG_LEVEL changes in the csv.
=> Bug 2176357: [release-4.9] Moving the defaults for rookceph operator from configmap to csv

services/provider/server/server.go, services/provider/server/server_test.go
To use ocs-client-operator with ODF, the subvolumegroup needs to be sent back in the GetStorageClassClaimConfig RPC call as the csi configmap needs to point to the right subvolumegroup for the user to use.
=> ms: add subvolumegroupname to GetStorageClassClaimConfig RPC

hack/build-functest.sh
openshift-ci is failing for quite a long time on the older branches due to the ginko v2.
We were installing the Ginko binary without the version, which was installing Ginko V2 and making it incompatible with our older code and Golang. Fix it by sticking it to the v1 version.
=> [release-4.11] Fix ginko errors in the openshift-ci

controllers/storagecluster/clusterclaims.go
Earlier the clusterClaim spec was not reconciled once created. This resulted in the clusterClaim spec value to be out of sync with the current odf version.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2182703
=> Reconcile the clusterClaim spec values to keep the values in sync

controllers/storagecluster/cephcluster.go, controllers/storagecluster/ocs_operator_config.go
For consumer/provider MS mode we cannot set global configuration at the csi level as a single consumer will be connected to the multiple provider clusters.
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2184068#c10
=> Don't require msgr2 port for provider/consumer clusters

controllers/storagecluster/cephcluster.go
If it's a provider or external/consumer cluster, don't require msgr2 and don't allow encryption or compression to be enabled even if the user has set it in the StorageCluster CR.
BZ-https://bugzilla.redhat.com/show_bug.cgi?id=2184892
=> For provider/consumer cluster don't require msgr2 & don't allow encryption or compression

controllers/storagecluster/storagecluster_controller.go
Fix the issue where OCSInitialization adds its own name to the storage cluster request queue when there is a change in it. Modify the code to enqueue the storage cluster name instead.
=> Correct storage cluster request queuing in OCSInitialization

controllers/storagecluster/cephcluster.go, controllers/storagecluster/ocs_operator_config.go
Refactor GetNetworkSpec to handle different network connection specs 
RequireMsgr2 will be set by default if it's not an external cluster
or a provider cluster, so v2 port will be the default port.
For a new cluster, The mons will have only the v2 port.
For an upgraded cluster mons will have both v1 and v2 ports. But csi
will use the v2 port for any new volume mounts.
For external cluster or provider cluster, v1 port will be used by
default. In this case for both new cluster and for an upgraded cluster
mons will have both v1 and v2 ports. But csi will use the v1 port. If
the user wants to use Encryption, compression or v2 port, they can
specify it in the network spec. In that case csi will switch to v2 port.
Pass appropriate options for  all the cases of Network Spec combination
We have …
=> Refactor GetNetworkSpec to handle different network connection & Pass appropriate options for all the cases of Network Spec

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
In local prometheus yaml file, we have 'openshift-storage' namespace embedded into the file. This change will make sure we have the current namespace in the YAML file.
As the function is general, it can be extended to do more sophisticated regex based replacements.
Tests added.
=> Change any embedded namespace to current one

controllers/storagecluster/storagecluster_controller.go
If the CRD is not present, it can prevent the ocs-operator from
starting which can cause problems for MS. Since MS is not going
to install the noobaa CSV anymore, it is better to only watch the
noobaa CRs if the SKIP_NOOBAA_CRD_WATCH is set to false.
MS will set SKIP_NOOBAA_CRD_WATCH env in the sub which will be
populated to the ocs-operator via OLM.
(cherry picked from commit 0f62acc68e0295d2a8c9f1c35b8fef64a99e60c1)
Manual backport of #1972
=> Bug 2185725:[release-4.12] do not watch noobaa CRs if SKIP_NOOBAA_CRD_WATCH is set to true

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/ocs_operator_config.go
In the case when for external mode upgrade happens from 4.12 to 4.13, getCephFSKernelMountOptions returns a blank value for external mode. It compares this with the current value of the key. But the configmap in this case also gives a blank value for the non-existent key. So it thinks the configmap is already in the correct state, skips adding the key to the cm. Which results in rook-ceph-operator pod being in CreateContainerConfigError state with the error message. So instead of the blank value, we return the ms_mode=legacy value which has the same effect as the blank value.
Reference-https://docs.ceph.com/en/latest/man/8/mount.ceph/#basic
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2188427
Add network spec to external cephcluster 
This was a big miss with all the previous …
=> Use ms_mode=legacy instead of blank value, add network spec to external mode ceph cluster, add unit tests

config/rbac/role.yaml, controllers/storagecluster/cephnfs.go, controllers/storagecluster/generate.go, controllers/storagecluster/reconcile.go, deploy/csv-templates/ics-operator.csv.yaml.in, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Create ServiceMonitor for nfs-metrics service (scrape NFS-ganesha's Prometheus metrics server endpoint).
NFS-Ganesha (as of V5-dev.2 [1]) supports Prometheus monitoring from within the NFS server itself. It provides metrics for both connected clients and active exports, via TCP port 9587.
Rook-ceph [2] uses NFS-Ganesha with metrics turned-on to enable NFS on top of cephfs.
This patch provides the missing binding piece between the NFS-Ganesha metrics the Prometheus scraping on ODF system.
Refs BZ-2190241
[1] https://github.com/nfs-ganesha/nfs-ganesha/commit/b6c59df5a0b8a3ae5b2a87446f8906cb321ee026
[2] https://github.com/rook/rook/commit/7b28f1de05b2c00731bee4f09a3a69c5acfc7607
=> nfs: servicemonitor for nfs-metrics

controllers/storagecluster/topology.go
As we construct the topologymap in each reconcile, the order of the label values are not consistent. This results in the nodetopologies to be updated frequently. This was causing reconcile to be cancelled in-between causing issues with rook-ceph-operator in stretched cluster.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2193220#c8
=> Sort values of topologymap labels to avoid frequent updates to CR

controllers/storagecluster/routes.go, controllers/storagecluster/routes_test.go
The BZ2139037 planned to expose differet routes for RGW service for TLS and non TLS ports. But current code uses the integer value for the ports. Since port in mentioned in RGW service for non-secure is different than one rgw internally uses in the pod. Hence the non-secure RGW route was not accessible. Also changed the termination policy to edge for the non-secure RGW route.
=> BZ2139037 : Use strings ports in service in routes

controllers/storagecluster/cephcluster.go, controllers/storagecluster/reconcile.go
Earlier the ensureOCSOperatorConfig func was being called while creation of the cephcluster, but in Noobaa standalone mode it was not being called, as a cephcluster is not created in that mode. So we have to ensure that the ensureOCSOperatorConfig is called irrespective of the modes. So we are moving it to the reconcile.go file and putting it at the end of reconcilePhases func.
=> Always call the ensureOCSOperatorConfig func irrespective of the mode

controllers/storagecluster/job_templates.go
Trying to update the whole template object doesn't work. So the template is not reconciled at all. We want the template to be updated to use new parameters, any new ceph commands, latest rook-ceph image, etc. So we need to update the parameters & objects separately to keep the template up-to-date.
This can be treated as an extension to https://github.com/red-hat-storage/ocs-operator/pull/1959
=> Always update the template parameters & objects to keep it up-to-date

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/ocs_operator_config.go, deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
When enabling non-resilient/replica-1 pools, it is necessary to
configure CSI by setting the CSI_ENABLE_TOPOLOGY variable to true and
specifying the value of the failure domain key using the
CSI_TOPOLOGY_DOMAIN_LABELS variable.
Previously, users had to manually modify the rook-ceph-operator-config
configmap. Now, the required values are passed automatically as ENV
variables via the CSV from the ocs-operator-config configmap.
=> Replica 1-Tech Preview- Pass appropriate value to rook via the csv for ceph non-resilient pools

controllers/storagecluster/ocs_operator_config.go
If Network.Connections is not null, we should check Connections.Encryption is not nill before checking Encryption.Enabled. This issue was found when we try to create a storage cluster with Network.Connections.Compression.Enabled set to true & Connections.Encryption is nil.
https://issues.redhat.com/browse/RHSTOR-4218
=> Check Connections.Encryption is not nil to avoid panic

controllers/storagecluster/storageclasses.go
CephCSI supports expansion for rbd encrypted PVCs. This pr sets allowVolumeExpansion to true in
the default encrypted rbd storageclass that
ocs-operator creates.
resolves: https://issues.redhat.com/browse/RHSTOR-4650
/cc @iamniting @agarwal-mudit @malayparida2000 @Madhu-1 @nixpanic
=> storagecluster: set allowVolumeExpansion to true for rbd enc sc

controllers/storagecluster/generate.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storagecluster_controller.go
We will watch for the virtualmachines.kubevirt.io crd. Then create a special ceph rbd storageclass for the virtualization
environment. This storageclass will have the rxbounce option to use a bounce buffer during I/O operation. This is mostly targeted to fix issues with windows VMs using ceph rbd. This storageclass has all the same options as the default ceph rbd storageclass with this extra rxbounce option.
=> Create a storageclass with rxbounce option if kubevirt crd is present

PROJECT, config/rbac/role.yaml, controllers/namespace/namespace_controller.go, controllers/namespace/namespace_controller_test.go, deploy/csv-templates/ics-operator.csv.yaml.in, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, main.go
Added a new namespace controller that adds a reclaimspace schedule annotation to all the namespaces starting with `openshift-*`, and restarts the csi-addons pod once done.
*NOTE:*
The controller doesn't restart the csi-addons pod if the value of reclaimspace annotation is updated to a different value manully. The pod needs to be restarted manually in that case.
=> Add namespace controller for ReclaimSpace

Makefile, hack/install-noobaa.sh, hack/install-ocs.sh
Both the scripts use operator-sdk run bundle command to directly install the operators from their bundles. The scripts also wait for the operator deployments to be ready before exiting.
=> Add make targets with hack shell scripts to install ocs & noobaa

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/generate.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storageclasses_test.go, deploy/csv-templates/crds/ics/ocs.openshift.io_storageclusters.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ics-operator/manifests/storagecluster.crd.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, functests/ocs/cluster_upgrade_test.go, pkg/deploy-manager/storagecluster.go
Added a new field named `StorageClassName` to the CephFilesystems,
CephBlockPools, CephNonResilientPools, CephObjectStores, NFS and Encryption
spec that takes the user defined name of the storage class created for
the respective type of resource.
And, `VirtualizationStorageClassName` for SC created for ceph block pools in
virtualization environment.
Added `MaxLength`, `Pattern` and duplicate values validation on the field.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2112929
=> Allow changing default storageclass names

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/provider_server.go, controllers/storagecluster/provider_server_test.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml
Update the storageCluster CR to set the type of service as nodePort or LoadBalancer
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2212773
Different cloud providers needs different annotations to be added in order to bring up the ocs provider server service in private network, hence we might need to create a load balancer externally, hence added a field in storageCluster CR to toggle between NodePort and LoadBalancer Service type
Ref: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
=> Toggle between OCS Provider Server Service Type

controllers/storagecluster/job_templates.go
Previously once the template existed we were not reconciling it. This resulted in the template using very old rook-ceph images and not having the newly added parameters. We want the template to be updated to use new parameters, any new ceph commands, latest rook-ceph image, etc. Trying to update the whole template object also doesn't work. So we need to update the parameters & objects separately to keep the template up-to-date.
/hold
=> Bug 2211592: [release-4.12] Always update the template parameters & objects to keep it up-to-date

controllers/storagecluster/job_templates.go
Previously once the template existed we were not reconciling it. This resulted in the template using very old rook-ceph images and not having the newly added parameters. We want the template to be updated to use new parameters, any new ceph commands, latest rook-ceph image, etc. Trying to update the whole template object also doesn't work. So we need to update the parameters & objects separately to keep the template up-to-date.
/hold
=> Bug 2211595: [release-4.10] Always update the template parameters & objects to keep it up-to-date

controllers/storagecluster/job_templates.go
Previously once the template existed we were not reconciling it. This resulted in the template using very old rook-ceph images and not having the newly added parameters. We want the template to be updated to use new parameters, any new ceph commands, latest rook-ceph image, etc. Trying to update the whole template object also doesn't work. So we need to update the parameters & objects separately to keep the template up-to-date.
/hold
=> Bug 2211594: [release-4.11] Always update the template parameters & objects to keep it up-to-date

controllers/storagecluster/cephcluster.go, controllers/storagecluster/topology.go, controllers/util/k8sutil.go, deploy/single-node-storagecluster.yaml
For development and demonstration purposes, StorageCluster can be deployed on a single node OpenShift cluster by setting environment variable "SINGLE_NODE" to true in ocs-operator pod.
Single node deployment for StorageCluster allows all pods to be deployed on a single node. This is not supported on a production cluster.
```
$ oc edit subscription ocs-operator
...
spec:
config:
env:
- name: SINGLE_NODE
value: "true"
...
```
=> enable single node cluster deployment

Dockerfile.bundle, Makefile, hack/build-operator-bundle.sh, hack/source-manifests.sh
Always call gen-latest-csv before building the bundle. Generate & Update the bundle Dockerfile each time. Simplify the hack/build-operator-bundle.sh script.
=> Improve the bundle build process for the operator

controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go
Enable encryption only when KMS is enabled along with ClusterWide encryption OR in standalone Noobaa cluster mode
Updated tests accordingly.
(cherry picked from commit 326a658f734d04a660f1fc4530138879d5d7b48d)
=> Bug 2209254: [release-4.11] Fix encryption enablement in Noobaa

Dockerfile, hack/build-functest.sh, hack/build-metrics-exporter.sh, hack/build-operator.sh, hack/common.sh, hack/generate-unified-csv.sh, hack/unit-test.sh, metrics/Dockerfile
Recently we updated the moduele path for ocs to v4 so we need to update the ldflags accordingly. Also ldflags is now a variable in the hack/common.sh file so we need not define it in every script.
=> Use new module path for ocs in ldflags

deploy/csv-templates/rook-csv.yaml.in, deploy/ocs-operator/manifests/cephcosidriver.crd.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/common.sh
An earlier version of the rook image did not have the cephcosidriver listed under owned in the csv, and the csv merging tool skipped it in the bundle.
=> update rook image

controllers/storagecluster/noobaa_system_reconciler.go
1. make sure noobaa autoscale configuration will added/updated to noobaa CR if noobaa CR missing the configuration
1. After upgrading to 4.14, MCG endpoint minCount and maxCount in ocs-storagecluster are ignored,
since 4.13 noobaa CR missing autoscaling configuration, after upgrade this configuration was still missing and this created issue
https://bugzilla.redhat.com/show_bug.cgi?id=2227607
1. install ODF in openshift 4.13 and upgrade it to 4.14
2. update noobaa endpoint maxCount to 2, wait for the second noobaa endpoint pod
=> Move autoscale into DesiredState method for upgrade

tools/csv-merger/csv-merger.go
Currently some of the images use the `Always` image pull policy. That isn't really necessary when the images are pulled by digest instead of by tag, and it introduces an additional network round trip to the image registry server that takes time and may fail. To avoid that this patch changes the `csv-merger` tool so that in addition to merging the CSVs it also changes the `imagePullPolicy` to `IfNotPresent` for images that are pulled by digest.
By default this doesn't produce any change in the merged CSV, because all the images are pulled by tag, but running the following:
```
$ export OCS_IMAGE=quay.io/ocs-dev/ocs-operator@sha256:b22c334a530dc194e758b0e9974376fe75ac1ea5044d079252aeb17081be8e0e
$ make gen-latest-csv
```
Will generate the following diff:
```diff
diff --git …
```
=> Use `IfNotPresent` pull policy for images pulled by digest

controllers/storagecluster/cephcluster.go
KMSServerConnectionAlert is not revoked even when the KMS connection is re-established. The alert is dependent on StorageCluster object's 'Status.KMSServerConnection.KMSServerConnectionError' field which is populated when KMS is unreachable. But we fail to reset the field when connection is re-established.
Fix is to reset this field when connection is fine.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2192852
=> Fix KMSServerConnectionAlert stays even when KMS connection is re-established

controllers/storagecluster/ocs_operator_config.go
Presently, the value for CSI_TOPOLOGY_DOMAIN_LABELS key is derived from the sc.Status.FailureDomainKey, which remains empty in the case of a standalone mcg setup. The comparison logic for updating the configmap relies on the value we intend to write versus the existing value. However, as both values are empty strings, the system identifies them as matching and thus refrains from updating the configmap. Despite this, it is crucial to update the configmap to include the key, even with an empty value, to ensure its presence.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2232344
=> Incorporate the CSI_TOPOLOGY_DOMAIN_LABELS key into the configmap

docs/design/disaster-recovery-optimization.md
This design doc contains information on how OCS operator can be used to update OSD store for new  ODF customers using Regional Disaster Recovery
=> design doc to use optimized OSD store

api/v1/storagecluster_types.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/storagecluster_controller_test.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml
If `ocs.openshift.io/clusterIsDisasterRecoveryTarget: true` annotation is available in the StorageCluster, then create `cephCluster` using `bluestore-rdr` backend store. 
If storageCluster is some how updated to remove this annotation, then ensure that
`bluestore-rdr` store type is not overridden
This PR also reverts the changes that exposed the OSD store in the storageCluster spec, that is #2116.
=> Use optimized osd store for new clusters

controllers/storagecluster/cephcluster.go
If mirroring is enabled, then use bluestore-rdr store and allow migration of OSDs running on bluestore to bluestore-rdr
We always enable `bluestore-rdr` and `yes-really-update-store`. Rook takes care of migrating the OSDs and pauses migration if cluster is unhealthy. We don't need to remove `yes-really-update-store` flag, because if all OSDs are already migrated, then it will be no-op.
=> support using bluestore-rdr for RDR customers

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/ocs_operator_config.go, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Earlier when enabling NFS the key needed to be passed manually to
rook via patching the rook-ceph-operator-config cm. Now the key is
passed automatically via env variable to the rook pod.
bz-https://bugzilla.redhat.com/show_bug.cgi?id=2233410
=> When NFS is enabled on the storagecluster pass ROOK_CSI_ENABLE_NFS: true

controllers/storagecluster/cephconfig.go
Resolves-https://bugzilla.redhat.com/show_bug.cgi?id=2218116
In some situations, such as vSphere VSAN, the drive media type is detected wrongly, for instance as HDD instead of SSD. For that, we have to force BlueStore to use settings designed for SSDs. We have 2 options for this.
1) bluestore_debug_enforce_settings = "ssd"
but it requires restart
OR
2) bluestore_prefer_deferred_size_hdd = 0
should work right away and no new deferred writes will be enqueued
We are choosing the second option as it does not require osd restart.
=> Avoid wrong detection of disk type, such as HDD instead of SSD on vSAN

controllers/namespace/namespace_controller_test.go, controllers/storagecluster/storagecluster_controller.go
Use the client.Client property of the reconciler object to make client calls instead of using the reconciler object directly.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2231076
=> Use client variable to make api calls to k8s cluster

controllers/storagecluster/external_resources.go, controllers/storagecluster/external_resources_test.go
fqdn is supported in with object store,
If the rgw-endpoint is passing the fqdn
Gateway should be updated with the hostname or fqdn name
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2233125
=> external: update objectstore with hostname if rgw-endpoint is hostname

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/ocs_operator_config.go, controllers/util/k8sutil.go
The ocsinitialization controller just creates the ocs-operator-config cm
(from which rook-ceph-operator pod takes env values for configuration).
The task of keeping it updated is on the storagecluster controller. But
when a storagecluster is not there and an upgrade happens the configmap
is not updated but the new rook operator looks for the Key for
configuration. So the rook-cpeh-operator pod fails & so does the
upgrade.
The solution is to change the behavior of the handling of the configmap
so that when the storagecluster controller is not present
ocsinitialization controller should own the configmap & keep it updated.
But when the storagecluster is present it should do nothing and leave it
to the storagecluster controller.
This commit also includes a change where we no longer compare …
=> Fix upgrade issue when storagecluster is not present

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/services.libsonnet
This commit adds a check for the number of ready deployment of rook-ceph-rgw-* pods, this change is done because, ODF/Rook used to run a routine that regularly created a bucket and then wrote/read the bucket to test the RGW health, now the status checking is removed. We now need to reflect the "Readyness" and the "Connected" nature of status of the CephObjectStore.
=> Add deployment check for rgw gateway pods

controllers/storagecluster/prometheus/localcephrules.yaml, metrics/mixin/alerts/obc.libsonnet
ObjectBucketClaim alerts had wrong label format
Wrong format: `{{$labels.objectbucketclaim}}`
Correct format:  `{{ $labels.objectbucketclaim }}`
=> Fix the OBC alert labels

controllers/storagecluster/cephcluster.go
This reverts commit d2cccaeb6d6790d4e43817e0405f49dd85a11663.
This PR reverts the changes done in PR https://github.com/red-hat-storage/ocs-operator/pull/2162 to migrate existing bluestore OSDs to use bluestore-rdr
Note: The plan is to merge this before the 4.14 RC. Refer [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2234735#c7)
=> Bug 2234735:[release-4.14] Revert "support osd migration in RDR customers"

Dockerfile.bundle, PROJECT, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/metadata/annotations.yaml
=> update PROJECT file

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/ocs_operator_config.go, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
This is a manual backport for https://github.com/red-hat-storage/ocs-operator/pull/2157.
=> Bug 2234664:[release-4.13] When NFS is enabled on the storagecluster pass ROOK_CSI_ENABLE_NFS: true

controllers/storagecluster/prometheus/localcephrules.yaml, metrics/mixin/rules/rules.libsonnet
Earlier we decided that a few metrics will be exposed through job, 'rook-ceph-exporter'. But now the implementation has changed and 'ceph_mon_num_elections' will be the only metric produced by the job. Rest of the metrics will still be coming from 'rook-ceph-mgr' job itself.
=> Correcting the job names in prometheus metrics

controllers/storagecluster/external_resources.go, controllers/storagecluster/external_resources_test.go
fqdn is supported in with objectstore,
If the rgw-endoint is passing the fqdn
Gateway should be updated with hostname or fqdn name
(cherry picked from commit 4064e9f6f431e9976ca28b7fb2b313fedda1679a)
=> Bug 2237370:[release-4.12] external: update objectstore with hostname if rgw-endpoint is hostname

must-gather/collection-scripts/gather_namespaced_resources
collect events in a sorted order
This commit is to collect the events in
sorted order and also collect yamls and describe
of oc events resource
=> Bug 2241113: [release-4.12]must-gather: collect events in a sorted order

controllers/storagecluster/storageclasses.go
This signals to kubevirt that requests not explicitly specifying any storage class should use this one.
https://github.com/kubevirt/containerized-data-importer/pull/2913
=> Add default virtualization storage class annotation

controllers/storagecluster/generate.go, controllers/storagecluster/storageclasses.go
Previously the storage cluster was deployed within the operator namespace, which was matching the Provisioner namespace and working well. However with the introduction of multiple StorageClusters, using the storagecluster namespace as provisioner namespace is no longer viable. Instead we should use operator namespace as that is the namespace where provisoners are deployed.
=> Fix Provisioner Namespace Configuration

metrics/internal/collectors/registry.go, metrics/internal/collectors/storageconsumer.go
After removing the capacity field from StorageConsumer CR, the dependency on that field in the metrics exporter was apparently not removed.
=> Fix for metrics exporter pod going in crashbacklloop

controllers/storagecluster/storagecluster_controller.go
The reconciler's context can be `nil`, when the handler is executed if the storagecluster CR is not present, as the reconcile loop will not be triggered and the context field will never be initialised.
But, even if it's `nil` the `r.Client.List` operation doesn't always panic because there is a race scenario of the `cache` being synced by the time code execution reaches here. If the cache is not synced, then it waits for the cache to sync before executing the `List` operation and sends a close request via the `Done` channel of `ctx`, which results in a panic as `ctx` is nil in this case.
Therefore, we should not be using the `r.ctx` field and instead use the `context` pass by the handler to execute the `List` operation.
BUG: https://bugzilla.redhat.com/show_bug.cgi?id=2231076
=> Use context passed via handler instead of reconciler's context

api/v1/storageprofile_types.go, config/samples/ocs_v1_storageprofile.yaml, controllers/storageclassrequest/storageclassrequest_controller.go, controllers/storageconsumer/storageconsumer_controller.go, deploy/csv-templates/ocs-operator.csv.yaml.in
Prior to this, a new CephBlockPool would be created for every new StorageClassRequest. This change allows the reconciler to use an existing CephBlockPool if the StorageClassRequest is from the same StorageConsumer with the same StorageProfile.
Addresses [BZ 2244426](https://bugzilla.redhat.com/show_bug.cgi?id=2244426).
=> Bug 2244426: check for existing CephBlockPool for given consumer/profile in StorageClassRequest

deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/common.sh
Using the tag v17 pulls the latest image from the v17 tag, and the latest image is v17.2.7. This image is problematic and causes the osd-prepare pods to fail. So use the exact version v17.2.6.
BZ-https://bugzilla.redhat.com/show_bug.cgi?id=2247313
=> Use exact ceph image version v17.2.6 instead of v17

controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller.go, controllers/storagecluster/storagecluster_controller_test.go
Previously, the isActiveStorageCluster function listed all storage clusters and checked them. To support one internal and one external cluster, it has been modified to check them separately.
=> Refactor isActiveStorageCluster to handle internal and external clusters

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/storage-client.libsonnet
- In existing rule division is performed on difference of Version to remove patch version and compare against config
- Above calculation results in unwanted behaviour in some cases and is flaky depending on patch version
- This commit removes the patch version at the start resulting in non-flaky calculations always
=> Bug 2248625: Simplify version comparison for StorageClient Alerts

controllers/storagecluster/job_templates.go
This reverts commit 61bfdd5fabe3530a16c8036d7cbc5aaa93f97c24.
We merged a fix for the original [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1970939) we deleted any completed osd removal job after they were successful, So that while creating another osd removal job a check for the earlier completed job's deletion is not necessary. But we didn't know our docs had these steps where customer using encryption have a step where they depend on the logs of the successful job logs to get the PVC name for the replaced osd. They would use this PVC name to clean up the dmcrypt mapping on the node. 
Updating the docs for so many types of platforms at so many places feels risky & anyway, this fix is not adding much value instead just creating more issues. So we should revert the fix. …
=> Revert "Delete a template job after the job gets completed"

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
This PR:
- Reverts the commit to enable bluestore-rdr migration by default when mirroring is enabled.
- allow migration of osds to bluestore-rdr if DR optimization annotation was added by the user later on.
=> allow migration of osds to bluestore-rdr

controllers/storageclassrequest/storageclassrequest_controller.go
While attempting to retrieve a `cephfilesystem`'s data pool that matches the requested profile's device class, the error in case of failure isn't captured properly and gets skipped. ⚠️ Must be merged prior to #2262
=> Bug fix of failed data pool retreival

controllers/storagecluster/storageclasses.go
- StorageClasses should only be created by StorageClassRequests when StorageConsumers are allowed, i.e in Provider mode
- This commit skips virt sc creation if consumers are allowed in StorageCluster CR
=> Skip creation of Virtualization SC in Provider Mode

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/defaults/resources.go, controllers/defaults/utils.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml
```
• Add an storageCluster api field to specify the resource profile.
• The field can only take values "lean", "balanced" and "performance".
• Accordingly, the resourceRequirements for the ceph daemons are set,
currently only mgr, mon, osd, mds and rgw pods are supported.
• It's checked if custom resourceRequirements are specified in the CR,
if yes, then those are used. If not, then profiles are used.
• If no resource profile is specified, balanced profile values are used.
```
=> Add resource profiles to control the resourceRequirements for ceph pods

main.go
Multiple storagecluster requires client to watch all namespaces
=> Watch for specific set of namespaces using the client

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/defaults/defaults.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/resourceprofile.go, controllers/util/k8sutil.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml
```
• Determine resource profile change by comparing sc.Spec.ResourceProfile
with sc.Status.LastAppliedResourceProfile. If they are different, then
a resource profile change is in progress.
• Mark the ContinueUpgradeAfterChecksEvenIfNotHealthy flag on the
cephCluster CR to false if a resource profile change is in progress.
• During the below process mark the storageCluster phase as Progressing.
The storageCluster conditions will show "New resource profile is being
applied".
• Keep checking if any of the pods with the new resource profile
label are in pending state for more than 2 minutes. If yes, then
assume that the resource profile change has failed. Mark the 
storageCluster phase as Error and the storageCluster conditions will 
show "New resource profile failed to apply, please revert …
```
=> Ensure resource profile changes are applied correctly without any issues

controllers/storagecluster/prometheus/localcephrules.yaml, metrics/internal/collectors/ceph-cluster.go, metrics/internal/collectors/ceph-cluster_test.go
To raise the new alert it was needed also to create the new metric ocs_node_labels.
The new metrics can be watched using:
- Executing the following command in the ocs-metrics-exporter pod:
```
sh-4.4$ curl http://localhost:8080/metrics | grep node
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  2533    0  2533    0     0   206k      0 --:--:-- --:--:-- --:--:--  206k
ocs_node_labels{label_failure_domain_beta_kubernetes_io_zone="us-east-2a",label_kubernetes_io_hostname="ip-10-0-10-78.us-east-2.compute.internal",label_provider_id="aws"} 1
ocs_node_labels{label_failure_domain_beta_kubernetes_io_zone="us-east-2b",label_kubernetes_io_hostname="ip-10-0-33-83.us-east-2.compute.internal",label_provider_id="aws"} 1 …
```
=> monitoring: Add new alert CephMonLowNumber

metrics/mixin/README.md
Include information about how to add the alert documentation files in runbook repo and how to link the alert and the runbook file
=> monitoring: runbooks documentation files

controllers/storagecluster/reconcile.go
This bug was intruduced while making the change for updating conditions in the commit 9256514f1b69471fb1134c65a2cdac579121aebb.
It always return after updating the conditions, we should only return if there is an error, otherwise we should continue with reconcile.
=> fix: do not return after updating conditions if there is no error

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/alerts.libsonnet, metrics/mixin/alerts/perf.libsonnet, metrics/mixin/config.libsonnet
**Background:** 
ODF sets requests/limits of the MDS daemon pod to 8Gi. Rook sets the mds_cache_memory_limit is set to 0.5,  that is,  4Gi
The MDS will try to stay under a reservation of this limit by trimming unused metadata in its cache and recalling cached items in the client caches.
It is possible for the MDS to exceed this limit due to slow recall from clients. 
Ceph sends a health warning message when the cache full threshold (mds_health_cache_threshold) of 150%, that is 6Gi in this case, is breached.
Here, we trigger the alert to the user when MDS cache usage breaches 95% of the `mds_cache_memory_limit`, that is, (mds resource request * 0.5)
=> add alert for mds cache over use

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/perf.libsonnet, metrics/mixin/config.libsonnet
This PR adds an alert, OSD is overwhelmed with a lot of performance request. 
There were multiple metrics/values considered to recognise when the cluster is under load. 
1. `util%` for the disks: The value for disk utilization is not very useful for devices with support for multiple queues like ssd and nvme. even if the utilization values are very high, the storage system can "take more work on"
2.  disk latency: we can take a look at an average latency over time, but latency is highly dependent on IO_size
3. CPU usage: on cluster's under high load, the CPU usage of the primary OSD jumps up on a small cluster, increasing the amount of OSDs reduce the cpu usage. 
in the end the PR just adds CPU usage as a factor, with a 35% usage as a threshold, which let's the user know to add more …
=> Add alerts for high osd cpu usage

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/perf.libsonnet, metrics/mixin/config.libsonnet
Raise an alert to scale active MDS pods if the CPU usage of MDS pod is more than 67% for 6 hours.
=> Alert user if ceph metadata server is consuming cpu at threshold point.

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/README.md, metrics/mixin/alerts/blocklist.libsonnet, metrics/mixin/alerts/encryption.libsonnet, metrics/mixin/alerts/mirroring.libsonnet
Once we have available the runbooks files in the runbooks repo,it is needed to link properly the alert with these documentation files.
Added runbook_url annotation label for the following OCS alerts:
KMSServerConnectionAlert
ODFRBDClientBlocked
OdfMirrorDaemonStatus
OdfPoolMirroringImageHealth
Note: This modification in mixin folder is needed (to show the doc url in the alerts)  until we decide to continue(or not) using mixings in OCS.
=> Add runbook_url annotation in alerts

config/rbac/role.yaml, controllers/storagecluster/exporter.go, controllers/storagecluster/prometheus.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/internal/collectors/ceph-block-pool.go, metrics/internal/collectors/ceph-cluster.go, metrics/internal/collectors/ceph-object-store.go, metrics/internal/collectors/cluster-advance-feature-use.go, metrics/internal/collectors/registry.go, metrics/internal/collectors/storage-cluster.go, metrics/internal/collectors/storageconsumer.go, metrics/mixin/alerts/blocklist.libsonnet, metrics/mixin/alerts/encryption-external.libsonnet, metrics/mixin/alerts/encryption.libsonnet, metrics/mixin/alerts/mirroring.libsonnet, metrics/mixin/alerts/obc.libsonnet, metrics/mixin/alerts/services-external.libsonnet, metrics/mixin/alerts/services.libsonnet, metrics/mixin/alerts/storage-client.libsonnet
In a multi storagecluster scenario, both metrics-exporter and PrometheusRules should be enabled on all the namespaces where the StorageClusters are installed.
Follow up PR: #2313
=> Enable MetricsExporter and PrometheusRules on each StorageCluster namespaces

controllers/storagecluster/exporter.go, metrics/internal/cache/pv.go, metrics/internal/collectors/ceph-block-pool.go
Remove an accidental role permissions added to prometheus.
Add the same (missing) permissions to metrics exporter.
A minor code refactor to optimize role/rolebinding addition to metrics exporter
and a minor bug fix
=> Added permissions to resources for metrics exporter

deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/common.sh
Manual backport of https://github.com/red-hat-storage/ocs-operator/pull/2245
Using the tag v17 pulls the latest image from the v17 tag, and the latest image is v17.2.7. This image is problematic and causes the osd-prepare pods to fail. So use the exact version v17.2.6.
BZ-https://bugzilla.redhat.com/show_bug.cgi?id=2247313
=> [release-4.13] Use exact ceph image version v17.2.6 instead of v17

deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/common.sh
Manual backport of https://github.com/red-hat-storage/ocs-operator/pull/2245
Using the tag v17 pulls the latest image from the v17 tag, and the latest image is v17.2.7. This image is problematic and causes the osd-prepare pods to fail. So use the exact version v17.2.6.
BZ-https://bugzilla.redhat.com/show_bug.cgi?id=2247313
=> [release-4.12] Use exact ceph image version v17.2.6 instead of v17

Dockerfile, controllers/storagecluster/provider_server.go, controllers/storagecluster/provider_server_test.go, controllers/storagecluster/storagecluster_controller.go, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/onboarding-secret-generator-binding.yaml, deploy/ocs-operator/manifests/onboarding-secret-generator-role.yaml, deploy/ocs-operator/manifests/onboarding-secret-generator-sa.yaml, onboarding/main.go, rbac/onboarding-secret-generator-binding.yaml, rbac/onboarding-secret-generator-role.yaml, rbac/onboarding-secret-generator-sa.yaml, tools/csv-merger/csv-merger.go
Creation of a job that is responsible for creating the private and public keys as secret in provider/consumer mode.
- Added watch on a public secret if it's deleted storage cluster will reconcile
- Job is created based on public key,
=> Token generation for prov/consumer mode

controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller.go
Provider supports client operator at X.Y and X.(Y-1) versions and if any client is already at X.(Y-1) version and provider gets upgraded then the lagging client goes out of support
This PR prohibits such provider upgrades
Minor: use a single existing enqueue function and removes duplicates
[RHSTOR-5073]
=> Stop provider upgrade if clients version is lagging

controllers/storagecluster/clusterclaims.go
Currently there is no way to determine if external clusters are optimized for DR, that is, they are bluestore-rdr.  So we should skip checking for the OSD store type in the cephCluster status in case of a external cluster. 
Note: We would want to revisit this in future once we start supporting external clusters for RDR.
=> skip checking osd store type for external clusters

Dockerfile, controllers/storagecluster/provider_server.go, controllers/storagecluster/provider_server_test.go, controllers/storagecluster/storagecluster_controller.go, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/onboarding-secret-generator-binding.yaml, deploy/ocs-operator/manifests/onboarding-secret-generator-role.yaml, deploy/ocs-operator/manifests/onboarding-secret-generator-sa.yaml, onboarding/main.go, rbac/onboarding-secret-generator-binding.yaml, rbac/onboarding-secret-generator-role.yaml, rbac/onboarding-secret-generator-sa.yaml, tools/csv-merger/csv-merger.go
=> [fusion-hci-4.14] added creation of job template

.github/workflows/ocs-operator-ci.yaml, Dockerfile, api/go.mod, api/go.sum, go.mod, go.sum, metrics/Dockerfile, vendor/modules.txt
Updating go modules to Golang v1.21. Also, removing tests for go 1.20 as it might cause false alarms.
=> Update go modules to Golang v1.21

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/perf.libsonnet
ceph-mds-mem-rss, used in MDSCacheUsageHigh alert, is in KB rather than bytes.
This PR converts the ceph-mds-mem-rss metric value to bytes before comparing it 
with the mds pod memory limit.
=> use correct units for MDSCacheUsageHigh alerts

services/provider/server/server.go, services/types.go, services/ux-backend/handlers/onboardingtokens/handler.go, services/ux-backend/main.go
- Move content of services/types package to the services package
- Move onboading_tokens content into its own sub-package
- Separate msg handling into Distinct functions based on HTTP method
- fix onboarding_tokens invalid content type
=> Some minor changes/fixes to ux backend

controllers/storagecluster/prometheus/localcephrules.yaml, metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/obc.libsonnet, metrics/mixin/alerts/services-external.libsonnet, metrics/mixin/alerts/services.libsonnet
Adding 'runbook_url' link to following alerts,
CephMgrIsAbsent
CephMgrIsMissingReplicas
CephMdsMissingReplicas
CephMonQuorumAtRisk
CephMonQuorumLost
CephMonHighNumberOfLeaderChanges
CephNodeDown
CephOSDCriticallyFull
ObcQuotaObjectsAlert
ObcQuotaBytesExhausedAlert
ObcQuotaObjectsExhausedAlert
ClusterObjectStoreState
=> Add 'runbook_url' link to alerts' annotation

controllers/storagecluster/prometheus/localcephrules.yaml
this PR adds the links for CephOSDNearFull,
CephOSDDiskNotResponding, and fixes link for PersistentVolumeUsageNearFull
=> add runbooks links for ceph rules

controllers/storageclassrequest/storageclassrequest_controller.go, controllers/storageclassrequest/storageclassrequest_controller_test.go, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/pkg/cache/informertest/fake_cache.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/testing.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/unconventionallisttypecrd.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/util.go
This PR is a follow-up to #2228 that addresses some remaining discussion points. First is a refactor to better define the "Initialization" phase of the reconciliation loop. Second is the introduction of unit tests for the controller, as well as a small bug fix that was discovered because of the new tests.
=> storageclassrequest: refactor and unit testing

controllers/storagecluster/prometheus/localcephrules.yaml
Fixes: #2257634
https://bugzilla.redhat.com/show_bug.cgi?id=2257634
=> Fixed wrong runbook link for CephMonLowNumber alert

deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
- Added group to delegate to URL
- when API is a call made from the pod it is mandator that resources should be in small cases and groups also needed because this is how we have to mention in the cluster role
=> Added group and made resource to smallcase to support api call from pod

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/perf.libsonnet
The PR adds the run book URL for the MDSCacheUsageHigh alert. It gives detailed call to action for the customers when they see this alert.
=> add runbook url for MDSCacheUsageHigh alert

metrics/internal/cache/rbd-mirror.go, metrics/internal/collectors/rbd-mirror.go
The PR removes the metrics
```
ocs_rbd_mirror_image_primary_snapshot_timestamp
ocs_rbd_mirror_image_secondary_snapshot_timestamp
ocs_rbd_mirror_image_image_bytes
ocs_rbd_mirror_image_image_snapshot_bytes
```
as corresponding metrics already exist in ceph
```
ceph_rbd_mirror_snapshot_image_local_timestamp
ceph_rbd_mirror_snapshot_image_remote_timestamp
ceph_rbd_mirror_snapshot_image_last_sync_bytes
```
`image_bytes` and snapshot bytes can be calculated by `sync_time` and `sync_bytes` metrics exported by ceph
```
ocs_rbd_mirror_image_image_bytes :  ceph_rbd_mirror_snapshot_image_last_sync_bytes / ceph_rbd_mirror_snapshot_image_last_sync_time
```
=> remove rbd-mirror metrics already exported by ceph

metrics/internal/collectors/ceph-block-pool.go
In case CephBlockPool mirroring is not enabled, it is logged as an error by metrics-exporter which is not true. This commit updates the check to ensure that we skip such cases and only log error when mirroring status is available but not in the state we expect.
=> fix false positive error log in metrics-exporter

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/perf.libsonnet, metrics/mixin/config.libsonnet
alert was getting triggered in normal workloads, so we've increased the threshold
=> increase the threshold for OSDCPULoadHigh

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
RBD mirror daemon count was defaulted to 1 with no min or max limit.
This could be problematic if users set unexpected values. So, this
commit adds a minimum of 0 and maximum of 1 as valid values and retains
the default value of 1.
=> RBD mirror daemon count validation

metrics/internal/cache/pv.go
PV cache resync obtains the lock to PV cache but then delegates the cache
update job to another function which also tries to gain lock but fails.
This commit separates the locking from cache update function to a shared
function without lock. This new function is not thread safe and should
be called from within threadsafe function.
=> Fix PV cache lock mechanism

controllers/storagecluster/cephconfig.go, controllers/storagecluster/cephconfig_test.go
The update of the rook-config-override configmap is not working and the overall function is complicated. This patch refactors the function to make it more readable and also fixes the update of the configmap.
BZ-https://bugzilla.redhat.com/show_bug.cgi?id=2260131
=> Refactor the ensureCreated func for rook-config-override configmap

controllers/storagecluster/exporter.go, deploy/ocs-operator/manifests/rook-monitor-mgr-role.yaml, deploy/ocs-operator/manifests/rook-monitor-mgr-role_binding.yaml, rbac/rook-monitor-mgr-role.yaml, rbac/rook-monitor-mgr-role_binding.yaml
In a multicluster mode, rook operator pod is throwing following exception,
```
failed to enable external service monitor.
service monitor could not be enabled: failed to retrieve servicemonitor.
servicemonitors.monitoring.coreos.com "rook-ceph-mgr" is forbidden:
User "system:serviceaccount:openshift-storage:rook-ceph-system" cannot
get resource "servicemonitors" in API group "monitoring.coreos.com" in
the namespace "openshift-storage-extended"
```
Adding cluster wide role and rolebinding to rook-ceph-mgr serviceaccount.
=> Adding 'ClusterRole' and 'ClusterRoleBinding' to rook-ceph-mgr

controllers/storageclassrequest/storageclassrequest_controller_test.go, controllers/storagecluster/cephfilesystem_test.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/storagecluster_controller_test.go
- Related PRs: #2204 #2231 #2274
=> `StorageProfile` unit tests

controllers/namespace/namespace_controller_test.go, controllers/storagecluster/storagecluster_controller.go
This is a manual backport of #2174 and #2232
=> Bug 2246527:[release-4.14] Use context passed via handler instead of reconciler's context

metrics/internal/cache/pv.go
For cases where PV exists without PVC, or PV/PVC exists but is not used by any Pod etc, we skip caching those PVs instead of returning an error as these neither provide any meaningful data nor have any impact on monitoring.
=> fix PV cache error conditions

controllers/storagecluster/exporter.go, metrics/internal/cache/ceph-blocklist.go, metrics/internal/cache/pv.go, metrics/internal/cache/pv_test.go, metrics/internal/cache/rbd-mirror.go, metrics/internal/cache/rbd_mirror_test.go, metrics/internal/options/options.go
Users can define custom auth via "ocs-metrics-exporter-ceph-auth" secret or fallback to "rook-csi-rbd-provisioner" which has the auth we need. It will work for all modes of deployment.
=> Enable ceph client and collectors for multicluster case

deploy/ocs-operator/manifests/rook-ceph-metrics-role.yaml, deploy/ocs-operator/manifests/rook-ceph-monitor-role.yaml, deploy/ocs-operator/manifests/rook-monitor-mgr-role.yaml, rbac/rook-ceph-metrics-role.yaml, rbac/rook-ceph-monitor-role.yaml, rbac/rook-monitor-mgr-role.yaml
Some build tools do not work well with multiple yaml in same file. This
causes operator bundle builds to fail.
=> split rook monitoring rbac into multiple files

controllers/storagecluster/cephcluster.go
Currently we add the 'managedBy' label to ceph metrics, similarly we need to add 'managedBy' label to ceph exporter metrics.
=> Add 'managedBy' label to rook-ceph-exporter metrics

controllers/storagecluster/generate.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/volumesnapshotterclasses.go, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
The current practice is to prefix the names of CephCSI drivers with the namespace name of the deployed Rook operator. However, if Rook is deployed in a different namespace (e.g. "xyz"), then the CephCSI driver name will also be prefixed with "xyz". This is not desirable, as we always want to use "openshift-storage" as the prefix, regardless of the namespace where Rook is deployed. This PR sets the CSI_DRIVER_NAME_PREFIX to a static value, i.e. "openshift-storage" for all CephCSI drivers.
=> add CSI_DRIVER_NAME_PREFIX to Rook config

controllers/storagecluster/provider_server.go, controllers/storagecluster/storagecluster_controller.go, deploy/ocs-operator/manifests/onboarding-secret-generator-role.yaml, hack/ticketgen/ticketcheck.go, onboarding/main.go, rbac/onboarding-secret-generator-role.yaml, services/provider/server/server.go
- fixed re-trigger job issue when the public key deleted
- formatted the logger in a proper format
=> fixed re-trigger job issue when public key deleted

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/storage-cluster.libsonnet
Even when number of MONs were increased from 3 to 5, the alert was not stopping. This is because the query did not check if Mon count is already >=5. This PR adds that check to ensure we stop alerting when MON count is 5 or more.
=> stop CephMonLowNumber alert when MON count is 5

controllers/storagecluster/exporter.go, controllers/util/predicates_test.go, tools/csv-merger/csv-merger.go
Huge thanks to @malayparida2000 for finding this over a year ago. :laughing: 
Waiting on #2385
=> controllers: use k8s pointer util

controllers/storagecluster/noobaa_system_reconciler.go
This is a small fix where we need to enable SSL only when tlsSecretName is present.
https://bugzilla.redhat.com/show_bug.cgi?id=2257982#c12
=> Enable externalPgSSLRequired only when tlssecret exists

controllers/storageclassrequest/storageclassrequest_controller.go, controllers/storageclassrequest/storageclassrequest_controller_test.go, controllers/util/slices.go
this PR updates the svg to have a consistent naming scheme and fetch the resources via ownerReference instead of looking at the status for the source of truth
=> storageClassRequest: move away from status as source of truth

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
While defining the default for the field it should have been
kubebuilder in all small letters, but earlier it was defined as
kubeBuilder which was causing the error. As the default 1 was not being
set, 0 was being passed as the count to the cephcluster which was reporting
invalid spec error.
Ref-https://bugzilla.redhat.com/show_bug.cgi?id=2263319
=> Fix cephCluster invalid spec error in replica-1 due to misspelled field

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/noobaa_system_reconciler.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
This commit adds changes to enable TLS on external postgresql server independent of whether the client passes certificates or not. Certificates are optional requirement and TLS can be enabled without them.
=> Adds spec changes to enable TLS on external Postgresql server

tools/csv-merger/csv-merger.go
The csv-merger tool contained code intended to replace allegedly unnecessary single quotes with double quotes in component crds.
This could sometimes result in broken csvs where ending quotes were simply removed
This change fixes these breakages by removing the culprit replacement code.
=> fix csv generation. 

controllers/defaults/placements.go
We were using one single TSC for both OSDs and OSD Prepare pods. This was causing problems in the even distribution of OSDs as the TSC was taking into account the OSD Prepare pods as well.
Bz-https://bugzilla.redhat.com/show_bug.cgi?id=2253634
=> Use separate TSCs with labels for osd & osd prepare pods

controllers/defaults/resources.go
Ref-https://bugzilla.redhat.com/show_bug.cgi?id=2258357#c13
We had reduced the mgr resources to minimal possible values during the introduction of the resource profiles. But recently we have observed that the mgr is getting OOMKilled in some of the setups during some actions.
=> Increase mgr resources to avoid mgr OOMKilled

controllers/storagecluster/storagecluster_controller.go
This is a manual backport of #2232 and #2174, with some changes due to package version changes.
DO NOT MERGE before #2235 is merged
=> Bug 2246526:[release-4.13] Use context.TODO() instead of reconciler's context

metrics/deploy/prometheus-ocs-rules.yaml
Running more than one active MDS is not tested as of now.
=> Remove active mds solution from alert

onboarding-validation-keys-generator/main.go
- changing native client to runtime client because when the job functionality was implemented it was using only native resources now custom resources are also part of the job.
- Also, I replaced 'os.exit' with 'klog.exit' to make the code cleaner.
=> changing native client to runtime client

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/kms_resources.go
EPIC: https://issues.redhat.com/browse/RHSTOR-5466
Tested the changes to see if cephCluster is getting the KMS settings correctly
``` security:
keyRotation:
enabled: false
schedule: '@weekly'
kms:
connectionDetails:
AZURE_CERT_SECRET_NAME: azure-ocs-ffwc9o1j
AZURE_CLIENT_ID: az-client-id1
AZURE_TENANT_ID: az-tenant-id1
AZURE_VAULT_URL: https://sapillai-kv2.vault.azure.net
KMS_PROVIDER: azure-kv
storage:
```
=> add support for Azure key vault

controllers/storagecluster/cephcluster.go
We need to increase monitoring interval of cephcluster. Rook-operator will read the monitoring -> interval from cephcluster CR and intern increase the rook ceph-exporter and ceph-mgr intervals.
Refer BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2269354
=> Adding a monitoring interval for cephcluster

controllers/storagecluster/external_resources.go, controllers/storagecluster/storageclasses.go
In external mode if replica-1 is enabled & topology details are provided then create a storage class for replica-1. We construct the TopologyConstrainedPools from the topology details provided in the external cluster details secret.
=> Create replica-1 sc for external mode if topology details are provided

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/util/k8sutil.go
set the CSI_REMOVE_HOLDER_PODS to true for new users on version 4.16 onwards and set it to false for older/upgraded user to give them time to migrate manually.
with version 4.17 we will make the CSI_REMOVE_HOLDER_PODS to true for all customers older and new both.
If the configmap is being created for the first time we are considering it as a new install.
Jira: https://issues.redhat.com/browse/RHSTOR-5340?focusedId=24357013&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24357013
=> Add CSI_REMOVE_HOLDER_PODS key and its value in the ocs configmap

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/generate.go, controllers/storagecluster/storageclasses.go, controllers/util/k8sutil.go
In external mode the replica-1 feature is not enabled via the
storageCluster CR. So detect the feature is enabled by checking if the
replica-1 storageClass exists. In external mode the failure domain is
not set in the storageCluster CR, so determine the failure domain key
by using the parameter of the storageClass. Also add a watch for
storageClass in the ocsinitialization controller to detect the
storageClass creation. Accordingly set the values in the CM.
=> Set values in ocs-operator-config CM for replica-1 in external mode

controllers/storagecluster/generate.go, controllers/storagecluster/storageclasses.go
Similar to CSI_DRIVER_NAME_PREFIX for obc provisioner so that the obc provisioner always checks for storageclass with name
`openshift-storage.ceph.rook.io/bucket`
=> add ROOK_OBC_PROVISIONER_NAME_PREFIX to Rook Config

config/rbac/role.yaml, controllers/defaults/resources.go, controllers/ocsinitialization/ocsinitialization_controller.go, controllers/ocsinitialization/ocsinitialization_controller_test.go, controllers/platform/platform_detection.go, controllers/util/util.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/k8s-metrics-servicemonitor-role-binding.yaml, deploy/ocs-operator/manifests/k8s-metrics-servicemonitor-role.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/odf-prometheus-role-binding.yaml, deploy/ocs-operator/manifests/odf-prometheus-role.yaml, rbac/k8s-metrics-servicemonitor-role-binding.yaml, rbac/k8s-metrics-servicemonitor-role.yaml, rbac/odf-prometheus-role-binding.yaml, rbac/odf-prometheus-role.yaml, templates/alertmanager.go, templates/k8smetricsservicemonitor.go, templates/prometheus.go, templates/prometheuskuberbacproxyconfig.go
Story link : [RHSTOR-5367](https://issues.redhat.com/browse/RHSTOR-5367)
Things added in this PR
- Prometheus instance
- Prometheus Service
- AlertManager instance
- Prometheus behing TLS
- Check for ROSA HCP platform before setting up monitoring resources
=> Added support for Prometheus

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml
Since queries for both ObcQuotaObjectsAlert and
ObcQuotaObjectsExhausedAlert are same, we don't require both the alerts to be fired at the same time.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2257949
=> Prevent ObcQuotaObjectsAlert overlapping with ObcQuotaObjectsExhausedAlert

controllers/storagecluster/storageclasses.go
with new fix at csi ceph/ceph-csi#4459 we dont need the pool parameter dependency from the storageclass So removing it
=> rbd: update rbd sc for topology provisioning

controllers/storageclassrequest/storageclassrequest_controller.go
The `own()` method was no setting a controller ownerref on objects created by the controller, which meant that updates to the created resources would not trigger reconciliation when using `Owns()` for the reconciler.
=> storageclassrequest: set controller ownerref

controllers/storagecluster/cephobjectstores.go
OCS-Op was crashing since objectstore.spec.hosting was not initialised
=> initalise objectstore.spec.hosting for virtualHostnames

controllers/storagecluster/cephblockpools.go
We support adding additional OSDs for each replica-1 pool. But as the pg & pgm num always stays at 1, the data always gets stored in the same OSD. Ideally we would want the data to be distributed across all the OSDs for a particular cephblockpool for a failure domain.
=> Specify pg & pgm num to distribute data across OSDs for replica-1 pools

config/dependencies/dependencies.yaml, deploy/ocs-operator/metadata/dependencies.yaml, hack/source-manifests.sh
In older clusters, upgrading the odf channel from 4.15 to 4.16 tries to bring the rook-operator, leading to conflicts with ocs-operator 4.15, which already contains all Rook components in its 4.15 CSV. This conflict results in upgrade failures.
To address this issue, the Rook dependency is removed from the odf-operator and added to the ocs-operator. This solution ensures a smooth upgrade process, as changing the ocs-operator channel will now bring Rook along with ocs-operator 4.16 without encountering conflicts.
This commit should be reverted in 4.17 as 4.16 will feature different CSVs. In 4.17, removing Rook as a dependency in ocs and adding it in the odf should facilitate smooth installations and upgrades.
Bugs: …
=> bundle: add rook as a dependency to allow upgrades from 4.15 to 4.16

controllers/storageclassrequest/storageclassrequest_controller.go, controllers/storageclassrequest/storageclassrequest_controller_test.go
rook cleans up underlying ceph resources when an annotation is set during deletion and we set that annotation when storageclassrequest is marked for deletion.
=> allow cleanup of ceph resources when storageclassrequest is deleted 

controllers/defaults/placements.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/clusterclaims.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/placement.go, controllers/storagecluster/resourceprofile.go, controllers/storagecluster/storagecluster_controller.go, controllers/storagecluster/storagecluster_controller_test.go, controllers/storagecluster/storagequota_test.go
Topology Spread Constraints have been supported since kube version 1.19. It's a cleaner way of spreading osds compared to podAffinity and podAntiAffinity. So we should always use TSCs for osd placements.
=> Remove support TSC check & always use TSCs for osd placements

templates/prometheus.go
Introduced in #2465 the service monitor selector in the Prometheus configuration was marked wrongly,hence it was scraping metrics from only k8s-service-monitor. Adding an empty service monitor selector scrapes metrics from all Service monitors  present in the namespace.
List of Service Monitors present in the namespace
```
k8s-metrics-service-monitor                      
noobaa-mgmt-service-monitor                    
ocs-metrics-exporter                            
odf-operator-controller-manager-metrics-monitor  
rook-ceph-exporter                              
rook-ceph-mgr                                    
s3-service-monitor                                
```
=> Adding empty label selector for prom service monitor selector

controllers/storagecluster/prometheus/localcephrules.yaml
Added 'managedBy' label to all the expressions to avoid any conflicting results.
These changes make sure that we don't have any 'PrometheusRuleFailures' in a multicluster mode scenario
=> Make all alerts/rules compatible with multicluster mode

controllers/storagecluster/external_resources.go
currently, if the rgw endpoint is not reachable
all the storageclass creation fails
The fix will make the rgw endpoint validation separate and will create rbd and cephfs storageclasses if rgw endpoints validation fails
=> external: seaprate rgw endpoint validation from cephfs and rbd sc

config/dependencies/dependencies.yaml, deploy/ocs-operator/metadata/dependencies.yaml, hack/source-manifests.sh
This reverts commit 366b7d2036193912fa9bcf629e75bc6acce647f8.
4.17 onwards odf will take a ownership over rook and bring it as a OLM deps.
Related PR: #2565
=> Revert "bundle: add rook as a dependency to allow upgrades from 4.15 to 4.16"

controllers/storagecluster/prometheus/localcephrules.yaml
Added 'managedBy' label and 'rook-ceph-mgr-external' job to expressions (where it was needed) to avoid any
conflicting results. These changes make sure that we don't have any 'PrometheusRuleFailures' in a multicluster mode scenario
(cherry picked from commit 31820dc029159113950d54d4a014b6ab6c394be8)
=> Bug 2262943: [release-4.16] Make all alerts/rules compatible with multicluster mode

.github/workflows/docker-push.yaml
=> action: add action to build and push images on demand

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/storagecluster_controller.go, go.mod
Noobaa and CephCluster CRs' status.conditions[].lastHeartbeatTime and status.conditions[].lastTransitionTime etc change frequently, causing unnecessary StorageCluster reconciliations. Implement logic to filter out these frequent, non-essential changes and trigger reconciliations only on relevant events.
Also add the owns for other objects as noobaa and cephcluster will trigger the recociles only for the relevant events. Previously, even though these objects were not owned by the controller, reconciliations were triggered due to status updates of the NooBaa and CephCluster CRs. Now the other objects should send thier own recocile requests because noobaa and ceph clkuster wont trigger the unnecessary reconciles and these objects can not rely on noobaa and ceph cluster.
Signed-off-by: Nitin …
=> controllers: limit reconciliations to relevant events

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/storagecluster_controller.go, go.mod
Noobaa and CephCluster CRs' status.conditions[].lastHeartbeatTime and status.conditions[].lastTransitionTime etc change frequently, causing unnecessary StorageCluster reconciliations. Implement logic to filter out these frequent, non-essential changes and trigger reconciliations only on relevant events.
Also add the owns for other objects as noobaa and cephcluster will trigger the recociles only for the relevant events. Previously, even though these objects were not owned by the controller, reconciliations were triggered due to status updates of the NooBaa and CephCluster CRs. Now the other objects should send thier own recocile requests because noobaa and ceph clkuster wont trigger the unnecessary reconciles and these objects can not rely on noobaa and ceph cluster.
Signed-off-by: Nitin …
=>  Bug 2282086:[release-4.16] controllers: limit reconciliations to relevant events

.github/workflows/ocs-operator-ci.yaml, controllers/storagecluster/noobaa_system_reconciler.go, docs/catalog-generation.md, hack/gen-promethues-rules.sh, must-gather/collection-scripts/gather_namespaced_resources
Fix typo for `unifed`, `promethues` and `decleared` and added `NotIn`, `notin` to ignore_word_list for spell check CI
=> [release-4.12] Fix spell check CI

controllers/defaults/defaults.go, controllers/storagecluster/cephcluster.go
Remove default value of waitTimeoutForHealthyOSDInMinutes from ocs-operator, and only update the SC CR, if a value is provided by the user.
Reference PR that added this code: #2579
=> Bug 2276824: [release-4.15] Remove default value of waitTimeoutForHealthyOSDInMinutes

controllers/defaults/defaults.go, controllers/storagecluster/cephcluster.go
Remove default value of waitTimeoutForHealthyOSDInMinutes from ocs-operator, and only update the SC CR, if a value is provided by the user.
Reference PR that added this code: #2579
=> Bug 2277926: [release-4.13] Remove default value of waitTimeoutForHealthyOSDInMinutes

controllers/defaults/defaults.go, controllers/storagecluster/cephcluster.go
Remove default value of waitTimeoutForHealthyOSDInMinutes from ocs-operator, and only update the SC CR, if a value is provided by the user.
Reference PR that added this code: #2579
=> Bug 2276825: [release-4.14] Remove default value of waitTimeoutForHealthyOSDInMinutes

controllers/defaults/defaults.go, controllers/storagecluster/cephcluster.go
Remove default value of waitTimeoutForHealthyOSDInMinutes from ocs-operator, and only update the SC CR, if a value is provided by the user.
Reference PR that added this code: #2579
=> Bug 2277928: [release-4.12] Remove default value of waitTimeoutForHealthyOSDInMinutes

controllers/ocsinitialization/sccs.go, controllers/storagecluster/noobaa_system_reconciler.go, go.mod, go.sum, metrics/go.mod, metrics/go.sum, metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/backingstore_types.go, metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go, metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, metrics/vendor/modules.txt, vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/backingstore_types.go, vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go, vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, vendor/github.com/noobaa/noobaa-operator/v5/pkg/bundle/deploy.go, vendor/modules.txt
This PR adds support for provisioning SCC for NooBaa operator alongside the Rook Operator. NooBaa operator added this SCC due to the IBM security requirements raised a few months ago.
=> [MCG] Add support for deploying NooBaa operator SCC along with Rook SCCs

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/generate.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
BZ-https://bugzilla.redhat.com/show_bug.cgi?id=2274175
Set the deviceClasses of the pools to avoid wrong data placement 
Earlier when replica-1 was getting enabled on an existing cluster the pool was setting it's deviceClass to replicated but there were no osds with this deviceClass as osd's during normal creation were given SSD deviceClass if blank, and now they can't change. To avoid & solve this problem we have to intelligently set the deviceClass for the pools, Depending on whether replica-1 is enabled & the number of deviceClasses found in the cephCluster CR status.
To do this we added a DefaultCephDeviceClass field in StorageCluster Status which will  hold the default ceph device class to be used for the pools. Depending  on whether replica-1 is enabled & the number of deviceClasses …
=> Set deviceClasses to avoid replicated pool spreading PGs across all OSDs

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/generate.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
This is a manual backport of https://github.com/red-hat-storage/ocs-operator/pull/2615
BZ-https://bugzilla.redhat.com/show_bug.cgi?id=2274175
Set the deviceClasses of the pools to avoid wrong data placement
Earlier when replica-1 was getting enabled on an existing cluster the pool was setting it's deviceClass to replicated but there were no osds with this deviceClass as osd's during normal creation were given SSD deviceClass if blank, and now they can't change. To avoid & solve this problem we have to intelligently set the deviceClass for the pools, Depending on whether replica-1 is enabled & the number of deviceClasses found in the cephCluster CR status.
To do this we added a DefaultCephDeviceClass field in StorageCluster Status which will hold the default ceph device class to be used …
=> Bug 2274175: [release-4.16] Set deviceClasses to avoid replicated pool spreading PGs across all OSDs

controllers/ocsinitialization/sccs.go, go.mod, go.sum, vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go, vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go, vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, vendor/github.com/noobaa/noobaa-operator/v5/pkg/bundle/deploy.go, vendor/modules.txt
This is a backport PR. Original PR - https://github.com/red-hat-storage/ocs-operator/pull/2655
This PR adds support for provisioning SCC for NooBaa operator alongside the Rook Operator. NooBaa operator added this SCC due to the IBM security requirements raised a few months ago.
Corresponding BZ created for NooBaa/MCG - https://bugzilla.redhat.com/show_bug.cgi?id=2273923
=> Bug 2273923:[release-4.15] [MCG] add support for deploying NooBaa operator SCC along with Rook SCCs

controllers/storagecluster/prometheus/localcephrules.yaml
Previous alerts were raised at 75% (NearFull) and 85% (Critical). At these percentages, customers still had enough storage left and felt that these were timed a bit aggressively.
=> Increase PV usage alert percentages

api/v1alpha1/storageconsumer_types.go, config/crd/bases/ocs.openshift.io_storageconsumers.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml, deploy/ocs-operator/manifests/storageconsumer.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
- Adding spec field to storage consumer CR
- Making it optional because for the consumer whos is having unlimited quota this field will not be set
=> Adding storage quota field to spec of storage consumer

config/rbac/role.yaml, controllers/storagecluster/reconcile.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
```
Process:
1.Deploy OCP4.16
2.Install ODF4.16
3.Check clusterrole status:
$ oc get clusterrole ocs-operator.v4.16.0-rho-5RplQlPvR925g4JZ4kfHCVObO1Flr5sTYbYn2P -o yaml
- apiGroups:
- noobaa.io
resources:
- noobaas
verbs:
- '*'
4.Add Get verb ocs-operator clusterrole status:
Add [get]
$ oc edit clusterrole ocs-operator.v4.16.0-rho-5RplQlPvR925g4JZ4kfHCVObO1Flr5sTYbYn2P
- apiGroups:
- noobaa.io
resources:
- noobaas
verbs:
- get
5.Delete ocs-operator pod and check ocs-operator pod logs:
$ oc get pods | grep ocs-oper
ocs-operator-595c6965f6-wd7dm                                     1/1     Running     11 (99m ago)    17h
$ oc delete pod ocs-operator-595c6965f6-wd7dm
$ oc logs ocs-operator-595c6965f6-wh6fk | grep noobaas
W0710 07:58:33.257978       1 reflector.go:539] …
```
=> Reducing the noobaas resources privilege according to the required verbs

controllers/storagecluster/storageclient.go, controllers/util/provider.go, services/types.go, services/ux-backend/handlers/onboardingtokens/handler.go
- Passing nil quota to function means unlimited quota
- Quota will be sent as HTTP request body
- Sample request: 
-`{
"value": 1,
"unit": "Pi"
}`  or no body
- Valid types are [Gi,Ti,Pi]
- Its been decided that quota will be saved always in Gib hence logic for converting in Gib is added
- Test performed:
Send empty body or value as zero  decoded json looks like this
`{"id":"4ae06e2f-cd04-41b1-b903-81a5947df11d","expirationDate":"1719058928"}`
With valid value it looks like this
`{"id":"64f3458e-bf91-4dc5-b9ac-13cd8ccb6daa","expirationDate":"1719059027","storageQuotaInGiB":1}`
- Test cases for handler will be added as part of different PR
=> Changes to the onboarding token api to include quota in the body

controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephblockpools_test.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go
There was no CephBlockPool defined for the .mgr pool, therefore it was using the default crush rule (with no deviceClass specified) The CephObjectStore & CephFilesystem metadataPool does not define the deviceClass (it is only set in the dataPools).
To fix this Create a CephBlockPool CR for the .mgr pool with the same poolSpec as the default CephBlockPool. Also set the deviceClass for the metadataPool in CephObjectStore and CephFilesystem.
BZ-https://bugzilla.redhat.com/show_bug.cgi?id=2253013
=> Fix pg_autoscaler won't scale due to overlapping roots

services/provider/server/server.go, services/provider/server/server_test.go
Sends `VolumeGroupSnapshotClass` as an external resource to the client via the storage claim response.
Must be merged prior to [ocs-client-operator/pull/168](https://github.com/red-hat-storage/ocs-client-operator/pull/168).
[RHSTOR-5795](https://issues.redhat.com/browse/RHSTOR-5795)
=> Sends `VolumeGroupSnapshotClass` to client

controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/odfinfoconfig.go
- [Fix](https://github.com/red-hat-storage/ocs-operator/pull/2440#discussion_r1673761210) for fetching CSV when populating the OCS version in odf-info. 
#2440
=> Fix fetching CSV from right namespace

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/storagecluster_controller_test.go
with 4.17 csi pods will be collecting logs by the
log rtoation setting, so even if its external mode turn on the log collector setting
=> external: enable log rotation and log collection for external mode

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
This new mode was added in Squid due to the balancer module not balancing the reads.
(BZ - https://bugzilla.redhat.com/show_bug.cgi?id=1870804)
=> use "upmap-read" as default balancer mode

controllers/storagecluster/noobaa_system_reconciler.go
Sets an annotation to noobaa cr if provider mode is enabled to allow pool ownership feature to be enabled.
Part of [Implement OCS and MCG operator support for pool ownership](https://issues.redhat.com/browse/RHSTOR-6123)
=> Add a check for provider mode and pass to noobaa

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/storagecluster_controller.go, go.mod
Noobaa and CephCluster CRs' status.conditions[].lastHeartbeatTime and status.conditions[].lastTransitionTime etc change frequently, causing unnecessary StorageCluster reconciliations. Implement logic to filter out these frequent, non-essential changes and trigger reconciliations only on relevant events.
Also add the owns for other objects as noobaa and cephcluster will trigger the recociles only for the relevant events. Previously, even though these objects were not owned by the controller, reconciliations were triggered due to status updates of the NooBaa and CephCluster CRs. Now the other objects should send thier own recocile requests because noobaa and ceph clkuster wont trigger the unnecessary reconciles and these objects can not rely on noobaa and ceph cluster.
Signed-off-by: Nitin …
=> Bug 2282087:[release-4.15] controllers: limit reconciliations to relevant events

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/storagecluster_controller.go, go.mod
Noobaa and CephCluster CRs' status.conditions[].lastHeartbeatTime and status.conditions[].lastTransitionTime etc change frequently, causing unnecessary StorageCluster reconciliations. Implement logic to filter out these frequent, non-essential changes and trigger reconciliations only on relevant events.
Also add the owns for other objects as noobaa and cephcluster will trigger the recociles only for the relevant events. Previously, even though these objects were not owned by the controller, reconciliations were triggered due to status updates of the NooBaa and CephCluster CRs. Now the other objects should send thier own recocile requests because noobaa and ceph clkuster wont trigger the unnecessary reconciles and these objects can not rely on noobaa and ceph cluster.
Signed-off-by: Nitin …
=> Bug 2282089:[release-4.14] controllers: limit reconciliations to relevant events

controllers/storagecluster/provider_server.go
Set a configuration for client operator's configmap to not manage noobaa's subscription while in provider mode
=> Disable client operator's noobaa subscription management

controllers/storagecluster/cephcluster.go, controllers/storagecluster/kms_resources.go
Add the missing KMS endpoint keys for Thales and Azure KMS configs to the known list of `kmsProviderAddressKeyMap`.
=> Adding endpoint key for Thales enterprise KMS (KMIP)

controllers/storagecluster/odfinfoconfig.go, controllers/storagecluster/odfinfoconfig_test.go
- Add 'gopkg.in/yaml.v2' import.
- go fmt import changes
This change is required because 'sigs.k8s.io/yaml' produced a PascalCase output, which the UI cannot use. By using the new dependency 'gopkg.in/yaml.v2', we ensure the output is in camelCase, which the UI can use for its unmarshalling.
example output by `sigs.k8s.io/yaml`
```
Clients:
- ClusterID: cluster1
Name: client1
- ClusterID: cluster2
Name: client2
DeploymentType: internal
StorageCluster:
CephClusterFSID: fsid12345
NamespacedName:
Name: storage-cluster
Namespace: openshift-storage
StorageProviderEndpoint: http://storage-provider-endpoint/
StorageSystemName: storage-system-1
Version: 4.17.0
```
example output required by UI  and done by 'gopkg.in/yaml.v2',
```
version: 4.17.0
deploymentType: internal
clients:
- name: client1 …
```
=> Bug 2302448: Refactor imports in odfinfoconfig.go

OWNERS
Joining the list of approvers and reviewers for the OCS operator, particularly in case of urgent reviews and merges.
=> Add travisn to approvers and reviewers

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
upmap-read mode of the balancer isn't supported by the kernel client. There was a recent change on the RADOS side which actually enforced this, see ceph/ceph#57776. Prior to 18.2.4 and 19.1.1 all sorts of incompatibility checks were missing in this area. So we need to revert upmap-read mode for now.
=> remove upmap-read balancer mode

controllers/storagecluster/storageclasses.go
This reverts commit e079940750ee2596cc8060fe286b768f14e65ea0.
We are not adding the annotation to storage classes
by default in this release due to extra validations
required to support only the vault KMS.
=> Revert "Annotate RBD storageclasses for keyrotation"

controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephblockpools_test.go, controllers/storagecluster/storagecluster_controller_test.go, controllers/storagecluster/uninstall_reconciler_test.go
The current implementation assumes only a single entity can touch the CR. Hence modifying the implementation such that the controller owns the specific fields and other entities are allowed to modify other fields of the cephblockpool CR.
Part of [RHSTOR-4886](https://issues.redhat.com/browse/RHSTOR-4886)
=> storagecluster: rewrite cephblockpool reconcilation

controllers/storagecluster/kms_resources.go
Vault URL provided in the KMS settings does not have a port number. As a result, endpoint reachable check in `checkEndpointReachable` function fails.  . This only works when we provide the default port of 443 and along with the URL. For now, we can simply avoid checking azure vault URL for endpoint reachability.
This fixes BZ - https://bugzilla.redhat.com/show_bug.cgi?id=2303619 which is a blocker for Azure customers using KMS
=> kms: skip checking azure kms endpoint reachability

config/rbac/role.yaml, controllers/storagecluster/reconcile.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
```Process:
1.Deploy OCP4.17
2.Install ODF4.17  [4.17.0-29.stable]
3.Check clusterrole status:
// +kubebuilder:rbac:groups=apps,resources=deployments;daemonsets;replicasets;statefulsets,verbs=*
$ oc get clusterrole ocs-operator.v4.17.0-29.-a2YWGo4YLCr5DJ6FdgHYR9jOIUTJOWs7bLd3qO -o yaml | grep deployment -C10
- apiGroups:
- apps
resources:
- daemonsets
- deployments
- replicasets
- statefulsets
verbs:
- '*'
4. Add create verb ocs-operator clusterrole status:
Add [create]
$ oc edit clusterrole ocs-operator.v4.17.0-29.-a2YWGo4YLCr5DJ6FdgHYR9jOIUTJOWs7bLd3qO 
- apiGroups:
- apps
resources:
- daemonsets
- deployments
- replicasets
- statefulsets
verbs:
- create
5.Delete ocs-operator pod and check ocs-operator pod logs:
$ oc delete pod ocs-operator
$ oc logs ocs-operator-7d49979444-l58wr
list: …
```
=> Reducing the apps group privileges

config/rbac/role.yaml, controllers/storagecluster/reconcile.go, controllers/storagerequest/storagerequest_controller.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
```
Procedure:
1. Deploy OCP4.17 [4.17.0-0.nightly-2024-08-19-165854]
2. Deploy ODF4.17 [odf-operator.v4.17.0-80.stable]
$ oc get storagecluster 
NAME                 AGE     PHASE   EXTERNAL   CREATED AT             VERSION
ocs-storagecluster   5m22s   Ready              2024-08-22T15:07:34Z   4.17.0
+kubebuilder:rbac:groups=storage.k8s.io,resources=storageclasses,verbs=*
$ oc get clusterrole ocs-operator.v4.17.0-80.-5ZFqOum5B7idpvPbl6Z3TfkwxJZUIirvkN8UEe -o yaml | grep storageclasses -C 10
- apiGroups:
- storage.k8s.io
resources:
- storageclasses
verbs:
- '*'
- create
- delete
- get
- list
- patch
- update
- watch
5. Add create and  delete verbs to ocs-operator clusterrole:
$ oc edit clusterrole …
```
=> Reducing the storage.k8s.io group privileges

config/rbac/role.yaml, controllers/storagecluster/reconcile.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
```
Procedure:
1. Deploy OCP4.17 [4.17.0-0.nightly-2024-08-19-165854]
2. Deploy ODF4.17 [4.17.0-84.stable]
$ oc get storagecluster
NAME                 AGE    PHASE   EXTERNAL   CREATED AT             VERSION
ocs-storagecluster   3d3h   Ready              2024-08-26T08:39:13Z   4.17.0
// +kubebuilder:rbac:groups=console.openshift.io,resources=consolequickstarts,verbs=*
5. Delete console.openshift.io from clusterrole:
-        - apiGroups:
-          - console.openshift.io
-          resources:
-          - consolequickstarts
-          verbs:
-          - '*'
6.Delete ocs-operator pod and check ocs-operator pod logs:
$ oc delete pod ocs-operator
$ oc logs ocs-operator
[no errors]
7.Check the code
I did not find any …
```
=> Delete console.openshift.io group from clusterrole

config/rbac/role.yaml, controllers/storageconsumer/consumer_test.go, controllers/storageconsumer/storageconsumer_controller.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/provider-role.yaml, rbac/provider-role.yaml, services/provider/server/consumer.go, services/provider/server/consumer_test.go, services/provider/server/server.go, services/provider/server/server_test.go
=> Added support for ocs provider server to fetch noobaa client resources

config/rbac/role.yaml, controllers/storagecluster/reconcile.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
```
Procedure:
1. Deploy OCP4.17 [4.17.0-0.nightly-2024-08-31-032707]
2. Deploy ODF4.17 [odf-operator.v4.17.0-53.stable]
$ oc get storagecluster
NAME                 AGE   PHASE   EXTERNAL   CREATED AT             VERSION
ocs-storagecluster   20h   Ready              2024-09-01T11:48:56Z   4.17.0
// +kubebuilder:rbac:groups=snapshot.storage.k8s.io,resources=volumesnapshots;volumesnapshotclasses,verbs=*
5. Add "create" and "delete" verbs
delete: https://github.com/red-hat-storage/ocs-operator/blob/main/controllers/storagecluster/volumesnapshotterclasses.go#L174
create: https://github.com/red-hat-storage/ocs-operator/blob/main/controllers/storagecluster/volumesnapshotterclasses.go#L108
$ oc edit clusterrole …
```
=> Reducing the snapshot.storage.k8s.io group privileges

config/rbac/role.yaml, controllers/storagecluster/reconcile.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
```
Procedure:
1. Deploy OCP4.17 [4.17.0-0.nightly-2024-08-19-165854]
2. Deploy ODF4.17 [4.17.0-84.stable]
$ oc get storagecluster
NAME                 AGE    PHASE   EXTERNAL   CREATED AT             VERSION
ocs-storagecluster   3d3h   Ready              2024-08-26T08:39:13Z   4.17.0
// +kubebuilder:rbac:groups=template.openshift.io,resources=templates,verbs=*
- apiGroups:
- template.openshift.io
resources:
- templates
verbs:
- '*'
5. Add create and  delete verbs to ocs-operator clusterrole:
- apiGroups:
- template.openshift.io
resources:
- templates
verbs:
- create
- delete
6.Delete ocs-operator pod and check ocs-operator pod logs:
$ oc delete pod ocs-operator
$ oc logs ocs-operator
W0829 12:16:57.004941       1 …
```
=> Reducing the template.openshift.io group privileges

config/rbac/role.yaml, controllers/storagecluster/reconcile.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
https://github.com/red-hat-storage/ocs-operator/blob/main/controllers/storagecluster/storagecluster_controller.go#L232
=> Add watch verb to snapshot.storage.k8s.io group

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
Sometimes, during installation with ODF, the rook mgr module in ceph cluster is being enabled. This pr ensures that it is disabled during installation. 
For example:
`sh-4.4$ ceph mgr module ls | grep rook`
`rook                  on`     
With this change:
`sh-4.4$ ceph mgr module ls | grep rook`
`rook                  -`
=> disabling rook mgr module in CephCluster

controllers/storagecluster/cephobjectstores.go
This reverts commit f5ba884b012bf0a7acfe612578f1f0091b2d1fd2.
(cherry picked from commit ef469011231b9ba925acab1457d9ea02b73039fa)
=> Bug 2270889: [release-4.14] Revert "add topology mode annotation rgw service"

controllers/storagecluster/noobaa_system_reconciler.go
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=2311551
We revert the nodeAffinity change to apply only to cases where users explicitly set nodeAffinity in storage cluster spec.
=> restore default affinity for noobaa standalone

controllers/defaults/resources.go, metrics/deploy/deployment.yaml
removing the limits on ocs-metrics-exporter, the in memory cache scales
with the amount of PVs in the cluster making it hard to point out an
upper limit for the memory.
Signed-off-by: Divyansh Kamboj <dkamboj@redhat.com>
=> remove resource limits on ocs-metrics-exporter

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
The sc.Status.DefaultCephDeviceClass helps us to set the deviceClasses on the pool on the CRs. Till now we are trying to determine the field in each reconcile loop. But with the introduction of multiple deviceClasses support in day-2, we can't always determine it as the logic for the determination is that it chooses the first non replica-1 deviceClass from the list of deviceClasses on the cephCluster CR status. If we determine it in each reconcile loop, we are running the risk of going back & forth between the multiple non replica-1 deviceClasses.
Although the current ceph logic returns the list in a consistent order so the problem shouldn't appear today, but any change in this logic might introduce future bugs. as we have the assurance that any additional deviceClass will be added in …
=> Set default CephDeviceClass in the status only if it's not set yet

api/v1/storagecluster_types.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
Earlier the cluster utilization alert rules (CephClusterNearFull,
CephClusterCriticallyFull, CephClusterReadOnly) and the osd alert rules
(CephOSDNearFull, CephOSDCriticallyFull) were hardcoded to use the
nearFullRatio 0.75, criticallyFullRatio 0.80, and fullRatio 0.85 values.
But these values are now configurable on the storageCluster CR. So the
prometheus rules for these alerts will now be updated to use the
specified values if provided in the storageCluster CR.
This also includes the refactor of the changing the prometheus rule
process. The function is now easier to read, maintain & expand.
Also add tests for prometheus rule changing process.
While adding the fields the description of the fields were directly
lifted off from rook-operator. The values of NearFull, BackfillFull &
Full in …
=> Update the Prometheus rule alerts acc to specified value & correct the default values in API desc

controllers/storagecluster/storageclient.go, controllers/util/provider.go, services/provider/server/server.go, services/types.go, services/ux-backend/handlers/onboarding/clienttokens/handler.go, services/ux-backend/handlers/onboarding/peertokens/handler.go, services/ux-backend/main.go
Update the onboarding Ticket to include an OnboardingSubjectRole - ocs-client, ocs-peer
1. ocs-client will be used to onboard a Client
2. ocs-peer role will be used to onboard a StorageCluster
Add a new endpoint to generate the peer onboarding token.
Part of [RHSTOR-4886](https://issues.redhat.com/browse/RHSTOR-4886)
=> changes to onboarding token api to include role in body

controllers/storagecluster/cephblockpools_test.go, controllers/storagecluster/cephrbdmirrors_test.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/provider_server.go, controllers/storagecluster/provider_server_test.go, controllers/storagecluster/storageclient.go, controllers/storagecluster/storagecluster_controller_test.go, controllers/util/k8sutil.go, deploy/ocs-operator/manifests/onboarding-validation-keys-generator-binding.yaml, deploy/ocs-operator/manifests/onboarding-validation-keys-generator-role.yaml, deploy/ocs-operator/manifests/provider-role-binding.yaml, deploy/ocs-operator/manifests/provider-role.yaml, onboarding-validation-keys-generator/main.go, rbac/onboarding-validation-keys-generator-binding.yaml, rbac/onboarding-validation-keys-generator-role.yaml, rbac/provider-role-binding.yaml, rbac/provider-role.yaml, services/provider/main.go
Allow provider-server to be deployed in intenal and provider mode
Why?
This is a part of RDR for Provider Mode RHSTOR-4886.
With this epic, we are introducing rpc calls for odf to odf communication, the RPC's we have for this epic are limited to Onboarding a Storage Cluster on different Openshift clusters and Getting the Mirroring Info required for setting up RDR (refer #2671).
This can also be used to replace the mechanism we have in the internal mode for setting up Mirroring for blockpool using MCO's Agents.
Hence moving the ocs-provider-server deployment to be deployed in both modes to enable both client to provider communication and cross odf communication.
The PR does the following:
1. Create service, deployment, onboarding job for both modes
2. Update the variable from …
=> Update provider-api-server to be deployed in internal and provider mode

controllers/storageconsumer/consumer_test.go, controllers/storageconsumer/storageconsumer_controller.go, services/provider/server/server.go, services/provider/server/server_test.go
Since a provider cluster already has a NooBaa system and does not require a NooBaa account to connect to a remote cluster, unlike client clusters. A NooBaa account only needs to be created if the storage consumer is for a client cluster.
Changes in this PR -
- Ignore Creation of noobaa account if cluster is a provider cluster by match cluster id
- Ignore adding noobaa resources to Storage config if on provider cluster
=> Prevent noobaaccount creation in provider cluster

services/provider/server/server.go, services/provider/server/server_test.go
The ceph health checker secret and the rook-ceph-mon secrets to configure cephclients are not being used anymore but they are being sent via GetStorageConfig grpc. These secrets were being created and since they lacked permissions to run ceph commands the cephclients were in failure state. This PR removes these secrets from being sent to storageclients.
The secrets were being created by ocs-client operator and were introduced in this PR, https://github.com/red-hat-storage/ocs-client-operator/pull/176
=> Ignore sending healthchecker & rook-ceph-mon secrets via storageconfig

Dockerfile, config/manager/manager.yaml, controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storageclasses_test.go, controllers/storagecluster/storagecluster_controller.go, controllers/storagecluster/storagecluster_controller_test.go, controllers/util/k8sutil.go, controllers/util/predicates.go, controllers/util/util.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/entrypoint.sh, main.go
- Update the storageCluster controller to react whenever a create/delete event has been enqueued for a specific CRD that's become newly available.
- Exit the ocs-operator process with a specific exit code whenever a new card of interest is being created or deleted
- Catch the exit code with a bash script and restart the ocs-operator process
- Conditionally watch the ClusterClaim CRD from the ocsinit controller
=> Available CRDs check feature

controllers/storagecluster/storagecluster_controller.go, hack/build-functest.sh
The enqueueStorageClusterRequest event handler is used to enqueue a reconcile request for the controller from the watched objects. Although the handle is being used by all the watched objects, but it checks the object type and returns if the object is not of type OCSInitialization. Due to this when any thing happens with the watched objects other than OCSInitialization, the reconcile request is not enqueued and the controller does not reconcile the object.
The watch process on certain resources we had on our code is broken in 4.14. But the issue was being masked due to the side effect of other problem where we were doing continuous reconcile each second.Recently Nitin fixed that Bug so now unnecessary reconciles don't happen anymore,https://github.com/red-hat-storage/ocs-operator/pull/2624 …
=> Bug 2313492: [release-4.14] Remove check of object type & return in enqueueStorageClusterRequest

config/rbac/role.yaml, controllers/storagecluster/reconcile.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
```
Procedure:
1. Deploy OCP4.17 [4.17.0-0.nightly-2024-10-06-021039]
2. Deploy OCS4.17 [4.17.0-117.stable]
$ oc get storagecluster
NAME                 AGE   PHASE   EXTERNAL   CREATED AT             VERSION
ocs-storagecluster   37h   Ready              2024-10-08T16:24:24Z   4.17.0
// +kubebuilder:rbac:groups=core,resources=pods;services;serviceaccounts;endpoints;persistentvolumes;persistentvolumeclaims;events;configmaps;secrets;nodes,verbs=*
$ oc edit clusterrole ocs-operator.v4.17.0-117-arcDX0KWGNx65tdjyZ3BPWOaOrKVTvxGaY4Adk
- apiGroups:
- ""
resources:
- configmaps
- endpoints
- events
- nodes
- persistentvolumeclaims
- pods
- secrets
- serviceaccounts
- services
verbs:
- '*'
5. Add "create" and "delete" verbs
- …
```
=> Reducing the core group privileges

controllers/storagecluster/noobaa_system_reconciler.go
We are adding affinity to Noobaa if not in noobaa-standalone mode or if placement is specified. But we are not clearing the affinity if the affinity was set previously. This is breaking upgrade.
https://bugzilla.redhat.com/show_bug.cgi?id=2314636
=> Clear the affinity on Noobaa if it was set previously to handle upgrades

api/v1alpha1/odfinfoconfig.go, controllers/storagecluster/odfinfoconfig.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
To uniquely indentify a storageConsumer from outside a cluster we need StorageClusterUID and ClientID (storageConsumerUID). Add this information to the odf-info configMap so that MCO or any other component can easily identify the consumer from these two information.
=> controller: update the odf-info to include client identification info

services/provider/server/server.go, services/provider/server/server_test.go
When in-transit encryption is enabled/disabled the kernel mount option for cephFS needs to be updated between prefer-crc/secure. So the desired state hash needs to include the EiT state, so that if the EiT state is changed the desired state hash will change and the client will reconcile to get the updated mount option.
=> Include Encryption In-Transit state as part of the desired state hash sent to clients

controllers/storagecluster/topology.go
The OCS operator searches for the `topology.kubernetes.io/zone` label key using a string containing logic. 
If the customer has a node with a label that includes the string `zone`. 
The OCS operator can read another label containing 'zone' instead of topology.kubernetes.io/zone.
=> Adjust Node Label Conditions Based on Full Label Name

services/provider/server/server.go
Currently the log displayed when there is a failure to add corev1 to provider server scheme is incorrect and shows
`failed to add ocsv1alpha1 to scheme`. This patch fixes the above
=> Fix an incorrect log statement

controllers/storagecluster/storageclient.go, controllers/util/k8sutil.go, controllers/util/provider.go, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ux_backend_role.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/provider.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/services/types.go, metrics/vendor/modules.txt, metrics/vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go, metrics/vendor/sigs.k8s.io/controller-runtime/pkg/client/config/doc.go, onboarding-validation-keys-generator/main.go, rbac/ux_backend_role.yaml, services/provider/server/server.go, services/types.go, services/ux-backend/handlers/onboarding/clienttokens/handler.go, services/ux-backend/handlers/onboarding/peertokens/handler.go, services/ux-backend/main.go, tools/csv-merger/csv-merger.go
onboarding ticket should contain the storageCluster UID the token was generated for and to fetch the storageCluster for UID, we fetch the storage Cluster from operator namespace
=> onboardingTicket: add uid to the ticket

services/provider/server/server.go, services/provider/server/server_test.go
- Sends two VRCs (one for image flattening) and one VGRC. Depends on #2620 
- Labels V*RepClass, V*SnapClass and StorageClass
[RHSTOR-5753](https://issues.redhat.com/browse/RHSTOR-5753), [RHSTOR-5794](https://issues.redhat.com/browse/RHSTOR-5794), [RHSTOR-5754](https://issues.redhat.com/browse/RHSTOR-5754)
=> Sends and labels `V*ReplicationClass`, `V*SnapClass`, `StorageClass` to client

metrics/deploy/prometheus-ocs-rules.yaml, metrics/internal/collectors/storageconsumer.go
- Trigger alert when quota utilization reaches 80%
=> exporter: add alert for storagequotautilizationration > 0.8

controllers/storageconsumer/consumer_test.go, controllers/storageconsumer/storageconsumer_controller.go
Solves: https://github.com/red-hat-storage/ocs-operator/issues/2829
=> Remove healthchecker ceph client

controllers/storagerequest/storagerequest_controller.go
add a blockpool name in the lable so UI can watch for the rados namespace that belongs to the particular blockpool
=> rbdmirror: add a blockpool name label in the rados namespace cr

services/provider/server/server.go
When there are at least two connected peers, the replication flag needs to be enabled for the correct labeling to take place.
=> Fix replication flag assignment

api/v1/storageclusterpeer_types.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller.go, controllers/storageclusterpeer/storageclusterpeer_controller.go, controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageclusterpeer_types.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageclusterpeer_types.go
add logic for storage cluster peer controller
Depends on:
1. https://github.com/red-hat-storage/ocs-operator/pull/2671
2. https://github.com/red-hat-storage/ocs-operator/pull/2677
3. https://github.com/red-hat-storage/ocs-operator/pull/2843
4. https://github.com/red-hat-storage/ocs-operator/pull/2671
Part of [RHSTOR-4886](https://issues.redhat.com/browse/RHSTOR-4886)
(review only the last two commits)
=> storageClusterPeer: add logic for storageclusterpeer controller

config/rbac/oauth_proxy_role.yaml, controllers/storagecluster/storageclasses.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ux_backend_role.yaml, rbac/ux_backend_role.yaml, services/ux-backend/handlers/expandstorage/handler.go, services/ux-backend/main.go
update the ux backend server to use new expandstorage handler
For end to end UI testing image used for backend server: http://quay.io/paarora/rook-ceph:v637
UI will send the form 
```
type AttachStorageForm = {
storageClassForOSDs: string
enableEncryption: boolean
storage: "1"
replica: int
count: int
strogaeClusterName: string
poolDetails: { 
volumeType: 'Filesystem' | 'Block'
poolName: string
dataProtectionPolicy: '2Way' | '3Way'
enableCompression: boolean
filesystemName: string
failureDomain: string 
}
storageClassDetails: {
reclaimPolicy: 'Retain' | 'Delete'
name: string 
volumeBindingMode: 'Immediate' | 'WaitForFirstConsumer'
enableStorageClassEncryption : bool
encryptionKMSID: string
}
}
```
=> ux: add a new expandStorage handler

metrics/deploy/prometheus-ocs-rules.yaml
Now CPU usage high alerts are categorized to TWO different sections, 
First section: where we have high CPU usage due to high MDS requests rate: at this point we need to scale horzontally by adding more mds pods.
Second section: where we have only CPU usage high: at this point we need to add scale vertically by adding more resources (CPU, memory) to the pods.
=> Add alerts to notify vertical or horizontal scaling

services/provider/server/server.go, services/provider/server/server_test.go
-  PVCs are in Gib and quota is in GB because of which pvc creation is restricted when the quota reaches around 95%
- Fix for https://issues.redhat.com/browse/DFBUGS-559
=> saving quota in GiB instead GB

controllers/storagecluster/external_resources.go
This update ensures that the secret hash in the storage cluster status is updated only after all resources are created successfully.
Previously, the status was updated prematurely, preventing the reconcile loop from re-running whether there was a failure or success. This change enables the reconcile process to continue retrying until all resources are successfully created.
=> external: Defer secret hash update until all resources are successfully created

controllers/mirroring/mirroring_controller.go
As the mirroring controller, lists consumers based on the annotation to trigger maintenance mode, add a watch for storage consumer annotation change in the mirroring controller
=> controllers: watch for consumer annotation in mirroring controller

services/provider/server/server.go, services/provider/server/server_test.go
- PVCs are in Gib and quota is in GB because of which pvc creation is restricted when the quota reaches around 95%
- manual Cherry-pick of https://github.com/red-hat-storage/ocs-operator/pull/2895
=> DFBUGS-872: [release-4.17] server: saving quota in GiB instead GB

services/provider/server/server.go, services/provider/server/server_test.go
The PR does the following:
1. ramen label for storageid was misspelled as storageID 
2. add the maintenancemode label to the VRC
3. always add the labels for ramen
=> provider: fix ramen labels

controllers/mirroring/mirroring_controller.go
instead of listing the storageclusterpeer, read the name from the annotation on storage-client-mapping config
=> controllers: read the storageclusterpeer name from annotation

metrics/internal/collectors/ceph-block-pool.go, metrics/internal/collectors/ceph-block-pool_test.go
consider mirroring enabled if spec.Mirroring for
CephBlockPoolRadosNamespace is not nil
=> DFBUGS-976: monitoring: mark mirroring enabled if spec.Mirroring is !nil

controllers/storagecluster/cephcluster.go
When parts of the placement spec, such as tolerations or node affinity, are defined, the ocs-operator stops applying default placement specs, including TSCs. The osd distribution may become potentially uneven in absence of the TSC. Always adding default TSCs ensures consistent and balanced OSD placement across nodes.
=> Add default TSCs if not present to ensure even distribution of OSDs

services/ux-backend/handlers/expandstorage/handler.go
In the expandstorage handler pool name is incorrect,
Rook adds the filesystemName prefix to every datapool, which was missing in the storageclass parameter
https://github.com/rook/rook/blob/44e96c8ab67a27121354a04b121b7f16b6a38894/pkg/operator/ceph/file/filesystem.go#L321
=> filesystem: correct the pool name in the ux backend handler

metrics/deploy/prometheus-ocs-rules.yaml
[DFBUGS-951](https://issues.redhat.com//browse/DFBUGS-951)
=> Fixed an indentation issue in 'prometheus-ocs-rules.yaml' file

controllers/storagecluster/prometheus/localcephrules.yaml, metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml
Need to address changes in 'ceph_disk_occupation' metric labels.
What is the change in 'ceph_disk_occupation' metric?
'ceph_disk_occupation' result no longer has 'exported_instance' label, instead it has 'instance' label.
What is the issue we are facing because of it?
We are hitting 'PrometheusRuleFailures' due to this new label change in our alerts / rules.
Second issue is that we are not seeing any results for some of the query expressions.
What is the solution?
Update the query expressions, change 'exported_instance' to 'instance'. Any 'label_replace' action which changes 'exported_instance' label to 'instance' label is no longer required (as the 'instance' label is directly available now)
=> DFBUGS-789: Fix 'ceph_disk_occupation' query expressions

.github/workflows/ocs-operator-ci.yaml, Dockerfile, api/go.mod, go.mod, metrics/Dockerfile, metrics/go.mod, metrics/vendor/modules.txt, services/provider/api/go.mod, vendor/modules.txt
Include go module changes, Dockerfile changes & GitHub workflow changes
=> Update to Go 1.23 including go module, Dockerfile, Workflows

metrics/deploy/prometheus-ocs-rules.yaml
This is related to - https://issues.redhat.com/browse/DFBUGS-368 
Customers are complaining about erroneous MDS cache usage alerts. Ceph team suggested that `ceph_mds_mem_rss` might not be the right metric to capture this cache usage. So this alert needs to looked at again. For the time being, we can just remove this alert while looking for a better solution.  Decision to remove this was discussed in Weekly meeting.
Details about the discussion with the Ceph team:
`rss` is not right metric for cache warning. `mds_co_bytes` is the correct metric but its not exposed by Ceph.
MDS pod memory is 8Gi set by ODF is low. (Not related to this issue but just a general observation)
Possible Resolution:
Operator should be able to read the MDS cache warning from the Ceph health and raise a promethus …
=> remove MDSCacheUsageHigh prometheus alert

metrics/deploy/prometheus-ocs-rules.yaml
Jira: https://issues.redhat.com/browse/DFBUGS-1276
=> Fix url typo in runbook for MDS alert

controllers/storagecluster/cephblockpools.go
https://issues.redhat.com/browse/DFBUGS-1185
=> Unset CephBlockPool mirroring if Mirroring spec is nil on SC

controllers/storagecluster/external_resources.go
Currently, the sc name is hardcoded,
in future if we support multiple rados namespace per tenant we need a variable name 
updating sc names to contain rados-namespace name
rook pr: https://github.com/rook/rook/pull/15243
=> external: fix sc name for rados namespace #2955

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephnfs.go, controllers/storagecluster/cephnfs_test.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
This PR introduces a new parameter, spec.nfs.LogLevel, to the StorageCluster CR.
The LogLevel parameter allows users to configure the log level for NFS, providing greater flexibility and control over logging behavior.
This enhancement aims to improve the user experience by enabling more precise logging settings for debugging and monitoring purposes.
Additionally, a unit test has been added to verify that the StorageCluster CR exports the Rook NFS CR, ensuring proper integration between the OCS operator CR and the Rook operator CR.
=> Add StorageCluster.spec.nfs.LogLevel in storagecluster CR

controllers/mirroring/mirroring_controller.go
For the failover to be completed, we need to reconcile the rbdMirror CR.
ocs-client creation was blocking the reconciliation of rbdMirror, hence
move the creation of ocs-client to where it is required
Manual Cherry pick of https://github.com/red-hat-storage/ocs-operator/pull/2957
=> DFBUGS-1258: [release-4.18] controllers: allow failover to complete when peer site is down

services/ux-backend/handlers/expandstorage/handler.go
with exandstorage ux-backend handler we will be
adding ssd disk always,
So by default make the deviceSet spec, `deviceType: ssd`
=> osd: add tunefastdeviceclass: true for all ssd disk

controllers/storagecluster/odfinfoconfig.go, controllers/storagecluster/storagecluster_controller.go, controllers/util/predicates.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/predicates.go
Since odf-info is created in operator namespace, in case of multi- storageCluster, we get a "cross-namespace owner references are disallowed" issue. To address this, stop owning the configMap and watch the configMap from storageCluster reconciler
More info on "cross-namespace owner references are disallowed" [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications). 
Bug: https://issues.redhat.com/browse/DFBUGS-1266
=> odf-info: stop owning the odf-info configMap

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/external_resources_test.go
https://issues.redhat.com/browse/DFBUGS-1357
=> Avoid reconciling rook-ceph-operator-config via the external controller

controllers/storagecluster/external_resources_test.go
=> fix codespell action error "indx ==> index"

controllers/defaults/placements.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/placement.go, controllers/storagecluster/placement_test.go
Rook creates the rook-ceph daemon's placement by merging the "all" and specific key placements. The OCS operator specifies the default OCS tolerations and node affinity in both the "all" key and the specific key leading to duplicated placements. To avoid this, skip specifying the default OCS tolerations and node affinity with the specific key.
=> Remove duplicate placements for rook-ceph dameons due to specifying with all & specific key

controllers/storagecluster/generate.go, controllers/storagecluster/volumegroupsnapshotterclasses_test.go
Change of format of naming VolumeGroupSnapshotClass from: 
```
ocs-storagecluster-rbdplugin-groupsnapclass
ocs-storagecluster-cephfsplugin-groupsnapclass 
```
To:
```
ocs-storagecluster-ceph-rbd-groupsnapclass
ocs-storagecluster-cephfs-groupsnapclass
```
=> edit VolumeGroupSnapshotClass Name

Dockerfile
Docker requires consistent casing for keywords.
If a keyword is in uppercase, all keywords should be in uppercase. If a keyword is in lowercase, all keywords should be in lowercase.
=> Fix casing do not match warning in Dockerfile

api/v1/topologymap.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/topologymap.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/topologymap.go
The failure domain is determined as "host", but the supportedLabels list used "hostname". This mismatch caused the topologyKey in the spec to be empty during topology generation, as the "host" key was not present. Updated the key in supportedLabels to "host" to resolve the issue.
It was introduced in https://github.com/red-hat-storage/ocs-operator/pull/2965
=> Rename hostname key to host in supportedLabels to resolve mismatch

controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go, services/provider/server/server.go, services/provider/server/server_test.go
This is a manual backport of https://github.com/red-hat-storage/ocs-operator/pull/3008
The automated backport was failing due to linter issue: https://github.com/red-hat-storage/ocs-operator/pull/3031
=> DFBUGS-1323: [release-4.18] provider: update the storageID for ramen

controllers/mirroring/mirroring_controller.go, services/provider/server/server.go, services/provider/server/server_test.go
Ramen's replication ID is combination of storageIDs.
storageID is a combination of cephfsid,cephblockpool id and the rns name
To generate the peerStorageID, 
- use the blockpool's mirroring token to get the peer cephfsid.
- to the cephblockpool id from the peer cluster, use the annotation on the blockpool
- use the rns.Spec.Mirroring.RemoteNamespace to fetch the remote namespace
=> provider: update the replicationID for ramen

controllers/defaults/placements.go, controllers/storagecluster/placement.go, controllers/storagecluster/placement_test.go
When Active MDS is 1, there would be 2 mds pods & we want them to be scheduled on different nodes always. So we use the required pod anti-affinity. If Active MDS are more than 1 then in a 3 node cluster scheduling issues would be there, so we switch to using preferred anti-affinity.
=> Use Required Pod anti affinity if Active MDS is not more than 1

controllers/storagecluster/cephcluster.go
sometimes jobs has duplicate toleartions,
and kube-state-metrics complaints about it
So deleting the jobs that have duplciate toleartions
=> osd: delete completed prepare pod jobs

Dockerfile, hack/build-metrics-exporter.sh, hack/build-operator-bundle.sh, hack/build-operator-catalog.sh, hack/build-operator.sh, hack/common.sh, hack/ensure-operator-sdk.sh, hack/ensure-opm.sh, hack/gen-protobuf.sh, hack/shellcheck-test.sh, metrics/Dockerfile
The development build for the ocs-operator image on macOS/arm64 was broken due to the `hack/entrypoint.sh` script being copied as a arm64 binary during the Docker build process. This caused execution failures on the amd64 based OpenShift cluster.
To resolve this, the `--platform` flag has been added to the Docker build command to ensure the base image and build process match the target OS/architecture. This ensures that the built binaries and shell script are correctly generated for the target environment.
=> Fix broken dev build process on Mac OS & cleanup

templates/k8smetricsservicemonitor.go, templates/prometheus.go
Currently the params are generated in k8sservice monitor to federate in-cluster kube metrics as below which is wrong. This patch fixes the correct string params.
```
params:
match[]:
- '{__name__=''kube_node_status_condition''}'
- '{__name__=''kube_persistentvolume_info''}'
- '{__name__=''kube_storageclass_info''}'
- '{__name__=''kube_persistentvolumeclaim_info''}'
- '{__name__=''kube_deployment_spec_replicas''}'
- '{__name__=''kube_pod_status_phase''}'
- '{__name__=''kubelet_volume_stats_capacity_bytes''}'
- '{__name__=''kubelet_volume_stats_used_bytes''}'
- '{__name__=''node_disk_read_time_seconds_total''}'
- '{__name__=''node_disk_write_time_seconds_total''}'
- '{__name__=''node_disk_reads_completed_total''}'
- '{__name__=''node_disk_writes_completed_total''}'
```
Also fixed tech debt …
=> Fix metrics params for k8s service monitor

controllers/defaults/placements.go, controllers/storagecluster/placement.go, controllers/storagecluster/placement_test.go
When Active MDS is 1, there would be 2 mds pods & we want them to be scheduled on different nodes always. So we use the required pod anti-affinity. If Active MDS are more than 1 then in a 3 node cluster scheduling issues would be there, so we switch to using preferred anti-affinity.
Manual backport of https://github.com/red-hat-storage/ocs-operator/pull/3035
=> DFBUGS-1603: [release-4.17] Use Required Pod anti affinity if Active MDS is not more than 1

controllers/storagecluster/noobaa_system_reconciler.go
We are adding affinity to Noobaa if not in noobaa-standalone mode or if placement is specified. We are also clearing the affinity if it was set previously to handle upgrade.
Combined manual backport of https://github.com/red-hat-storage/ocs-operator/pull/2797, https://github.com/red-hat-storage/ocs-operator/pull/2851
=> DFBUGS-1659: [release-4.15] Restore default affinity for noobaa standalone & clear if set previously

controllers/storagecluster/noobaa_system_reconciler.go
We are adding affinity to Noobaa if not in noobaa-standalone mode or if placement is specified. We are also clearing the affinity if it was set previously to handle upgrade.
Combined manual backport of https://github.com/red-hat-storage/ocs-operator/pull/2797, https://github.com/red-hat-storage/ocs-operator/pull/2851
=> DFBUGS-1646: [release-4.16] restore default affinity for noobaa standalone & clear if set previously

controllers/mirroring/mirroring_controller.go, services/provider/server/server.go
mirroring token is generated only after mirroring is enabled. If both sides reconcile simultaneously (in parallel) the mirroring token won't be fetched. Hence, we re-queue when an empty mirroring token is fetched.
[DFBUGS-1682](https://issues.redhat.com/browse/DFBUGS-1682)
=> mirroring: requeue if mirroring token is not generated

README.md
#2972
This PR enhances the Installation section of the ocs-operator README by adding a new installation option using the `make install` command. The `make install` method provides a streamlined way to deploy the OCS operator in development environments or with private images.
=> Add make install Procedure to README for Installation

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
In clusters where the devices were initially of type hdd and later replaced with ssd, Ceph continues to list hdd in the available device classes under ceph osd crush class ls. This occurs even after all devices have been replaced with ssd. As rook populates the available device classes from this list, the hdd device class persists in the CephCluster status.
Starting from OCS 4.16, OCS operator determines and assigns a defaultCephDeviceClass to all pools by selecting the first non-replica-1 entry in the CephCluster status. Due to the persistence of the hdd device class, the OCS operator incorrectly selects hdd as the default device class, even though all underlying device sets have been updated to ssd.
To address this issue, we are introducing a hardcoded check in the OCS operator: if both …
=> DFBUGS-1667: [release-4.17] Fix conflict between SSD and HDD device classes causing CRUSH rule issue

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
In clusters where the devices were initially of type hdd and later replaced with ssd, Ceph continues to list hdd in the available device classes under ceph osd crush class ls. This occurs even after all devices have been replaced with ssd. As rook populates the available device classes from this list, the hdd device class persists in the CephCluster status.
Starting from OCS 4.16, OCS operator determines and assigns a defaultCephDeviceClass to all pools by selecting the first non-replica-1 entry in the CephCluster status. Due to the persistence of the hdd device class, the OCS operator incorrectly selects hdd as the default device class, even though all underlying device sets have been updated to ssd.
To address this issue, we are introducing a hardcoded check in the OCS operator: if both …
=> DFBUGS-1668: [release-4.16] Fix conflict between SSD and HDD device classes causing CRUSH rule issue

controllers/storagecluster/cephcluster.go, controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
PrometheusDuplicateTimestamps alert is generated due to the presence of duplicate tolerations on the osd-prepare job pods & osd-key-rotation cronjob pods. Although the root of the issue has been fixed with another fix, the existing succeeded pods need to be cleaned up to stop the alert.
=> DFBUGS-1654: [release-4.18] Delete the succeeded pods with duplicate tolerations to avoid alert

controllers/storagecluster/topology_test.go
Enhanced `TestFailureDomain` by adding validations for `expectedFailureDomainKey` and `expectedFailureDomainValues`. This ensures correctness of failure domain selection, key mapping, and associated topology values.
=> Improve TestFailureDomain for Failure Domain Key and Values

controllers/storagecluster/odfinfoconfig.go, controllers/storagecluster/storagecluster_controller.go, controllers/util/predicates.go
Since odf-info is created in operator namespace, in case of multi storageCluster, we get a "cross-namespace owner references are disallowed" issue. To address this, stop owning the configMap and watch the configMap from storageCluster reconciler
Signed-off-by: Rewant Soni <resoni@redhat.com>
(cherry picked from commit ccbefaab3c4ac7a6ca985131acc959e46d998737)
Manual backport for https://github.com/red-hat-storage/ocs-operator/pull/2959
=> DFBUGS-1326: [release-4.17] odf-info: stop owning the odf-info configMap

services/provider/server/server.go, services/provider/server/server_test.go
update the storageid for rbd to be hash(ceph_fsid, rns) and cephfs to be hash(ceph_fsid, svg name)
There will be a follow-up PR to fetch the peer rbd storageID from the annotation on the storageConsumer (to be added once https://github.com/red-hat-storage/ocs-operator/pull/3078 is merged) instead of generating it on the fly.
=> provider: update storageid for rbd and cephfs

controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephblockpools_test.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephfilesystem_test.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/cephobjectstores_test.go
The bulk flag makes the autoscaler start with the max number of PGs, and the autoscaler then decreases the pg count only if the PG usage starts to skew too much. This could improve performance for ODF users due to great amount of parallelism during read/write on large clusters.
We are going to set the bulk flag for now on the default cephBlockPool & replica-1 cephBlockpools, default cephFS metadata pool & data pools, default cephObjectStore metadata pool & data pool.
The flag is set to true only during new pool creation, as setting it on existing pools can cause data movement.
Ref-https://issues.redhat.com/browse/RHSTOR-6774
=> Set bulk flag to true on intended pools for performance gain

controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephblockpools_test.go
Remove the deployment mode annotation ref from cephblockpool reconcile as blockpool mirroring will be handled by the mirroring controller.
=> cephblockpool: stop reconciling mirroring field

controllers/storagecluster/cephcluster.go
there is a bug in ceph https://tracker.ceph.com/issues/70571 until that is fixed diabling the probes
=> mgr: disable mgr liveness and startup probe

controllers/storagecluster/cephfilesystem.go
We were mistakenly using the data pool spec
for the metadata pool.
=> Set metadata pool spec on the cephFS metadata pool

controllers/storagecluster/obcstorageclasses.go, controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
The storageClass is a cluster scoped resources, it doesn't need a namespace. 
Also, a storageClass should follow createOrReplace logic instead of createOrUpdate as the params are immutable
=> controllers: fix obc storageclass creation

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Make the allowRemoteStorageConsumers immutable for the provider mode upgrade to 4.19 internal mode
=> api: make allowRemoteStorageConsumers immutable

controllers/mirroring/mirroring_controller.go, controllers/storagecluster/odfinfoconfig.go, services/provider/server/server.go
This PR does the following:
- update the blockpool mirroring mode to init-only - ceph requires the blockpools to be enabled for mirroring before we enable mirroring for the rns. The init-only mode specifies that a particular blockpool's rns are ready to be mirrored 
- send consumers/client info in odf-info if they are enabled - If a consumer is not enabled, we shouldn't let ACM read the information about the consumer
- use StorageConsumerResources in GetStorageClientsInfo to fetch the right rns - Till 4.18 we had one rns per consumer hence the assumption that we had to send the rns held. But with 4.19 we are moving to multiple rns with the same rns name and which is stored in a configmap, hence moving to fetch the configmap and using the rns name in the configmap
- fetch the rns using …
=> rdr: update the controller/server for rdr after convergence

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go, controllers/storagecluster/obcstorageclasses.go, controllers/storagecluster/storageconsumer.go, controllers/storageconsumer/storageconsumer_upgrade_controller.go, controllers/util/storageclasses.go, controllers/util/storageconsumer.go, main.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go, services/provider/server/server.go
For Provider Mode update to 4.19, we are creating a new controller `StorageConsumerUpdateController`. This will look at the existing consumers for which the clients are in DF 4.18 and process these consumers to create a configMap and then update the consumer spec to include all the default classes. Once all the changes are made we will add an annotation to these consumers to imply that these are processed, and we can proceed with the reconciliation of these consumers.
=> controllers: add a new controller to handle provider upgrades

controllers/storagecluster/cephcluster.go, controllers/util/k8sutil.go
PrometheusDuplicateTimestamps alert is generated due to the presence of duplicate tolerations on the osd-prepare job pods & osd-key-rotation cronjob pods. Although the root of the issue has been fixed with another fix, the existing succeeded pods need to be cleaned up to stop the alert.
Manul Backport of https://github.com/red-hat-storage/ocs-operator/pull/3056
=> DFBUGS-1701: [release-4.17] Delete the succeeded pods with duplicate tolerations to avoid alert

docs/design/storage-auto-scale.md
Currrently the controller was dependednt on reading cr status, update the design so controller to not depend on cr status
=> autoscaler: update storageautoscaler design doc

controllers/storagecluster/cephcluster.go, controllers/util/k8sutil.go
PrometheusDuplicateTimestamps alert is generated due to the presence of duplicate tolerations on the osd-prepare job pods & osd-key-rotation cronjob pods. Although the root of the issue has been fixed with another fix, the existing succeeded pods need to be cleaned up to stop the alert.
Manual backport of https://github.com/red-hat-storage/ocs-operator/pull/3056
=> DFBUGS-1702: [release-4.16] Delete the succeeded pods with duplicate tolerations to avoid alert

controllers/storagecluster/cephcluster.go
The mon_target_pg_per_osd parameter determines the recommended total PG count and PG-per-OSD ratio. The default value is 100, but setting it to 400 improves performance by increasing parallelism through a higher PG count. 
On existing clusters this can trigger data movement and rebalancing.
https://issues.redhat.com/browse/DFBUGS-2249
=> Set mon_target_pg_per_osd to 400 for better performance from higher PG count

metrics/deploy/prometheus-ocs-rules.yaml
Customers are complaining about erroneous MDS cache usage alerts. Ceph team suggested that `ceph_mds_mem_rss` might not be the right metric to capture this cache usage. So this alert needs to looked at again. For the time being, we can just remove this alert due to increasing number of customer cases around this.
Signed-off-by: Santosh <sapillai@redhat.com>
(cherry picked from commit 4c85bc9be200d428313bb825d12f8b6c8cfc0e41)
=> DFBUGS-1033: [release 4.17] remove MDSCacheUsageHigh prometheus alert

metrics/deploy/prometheus-ocs-rules.yaml
Customers are complaining about erroneous MDS cache usage alerts. Ceph team suggested that `ceph_mds_mem_rss` might not be the right metric to capture this cache usage. So this alert needs to looked at again. For the time being, we can just remove this alert due to increasing number of customer cases around this.
Its a manual backport of https://github.com/red-hat-storage/ocs-operator/pull/2938
Signed-off-by: Santosh <sapillai@redhat.com>
(cherry picked from commit 4c85bc9be200d428313bb825d12f8b6c8cfc0e41)
=> DFBUGS-1034: [release 4.15] remove MDSCacheUsageHigh prometheus alert

controllers/storagecluster/cephconfig.go
a new ceph config bluestore_slow_ops_warn_lifetime:0 needed to be set to avoid slow ops warning
coming from latest 19.2.1.x release
On 4.19 build we didn't see the issue after deployment of ODF, but after triggering the regression test suit we saw the issue.
=> osd: add a new ceph config to prevent slow ops

controllers/defaults/resources.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/defaults/resources.go
update the exporter and crashcollector with limits and priority class, so it wont get evicted
during memeory pressure testing
Used the default limits as of `mon`
=> cluster: update exporter and crashcollector resources

api/v1/storageautoscaler_types.go, controllers/storageautoscaler/storageautoscaler_controller.go, controllers/storageautoscaler/verify.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageautoscaler_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storageautoscaler_types.go
Add a new invalid phase:
1)  if more than one storage autoscaler present with same
device class and same storage cluster, do not reconcile
2) If lso storageclass is detected
3) if lean profile is detected
=> storageautoscaler: add a invalid phase in cr

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephconfig.go
Ref-https://issues.redhat.com/browse/DFBUGS-2372
After mon_target_pg_per_osd is set to 400, sometimes we see a ceph health warning about too many PGs per OSD as the osd count reaches 600-700 sometimes. Setting the mon_max_pg_per_osd to 1000 will help avoid this warning.
=> Set mon_max_pg_per_osd to 1000 to avoid too many PGs warning

controllers/storagecluster/cephconfig.go, controllers/storagecluster/cephrbdmirrors.go, controllers/storagecluster/reconcile.go
Irrespective of whether rbd-mirror is deployed or not, the debug logging configs are always applied. This maakes the code simpler & clearr. As without rbd-mirror present, the debug logging configs are anyways not used so it is not a problem.
Ref-https://issues.redhat.com/browse/DFBUGS-2087
=> Always apply rbd-mirror debug logging ceph configs

services/ux-backend/handlers/expandstorage/handler.go
Custom cephBlockPool are not reconciled by ocs-operator, so if the user does not set the target size ratio value, it will be not set. This would affect the scaling of the pool.
So we need to add the target size ratio default value to the custom cephBlockPool during creation.
Part Of https://github.com/red-hat-storage/odf-console/pull/2067
https://issues.redhat.com/browse/DFBUGS-2059
=> Add target size ratio value to custom cephBlockPool during creation

controllers/storagecluster/storageconsumer.go
Replaces incorrect use of NFS StorageClass name with the correct NFS VolumeSnapshotClass name in `getLocalVolumeSnapshotClassNames()`.
=> Fix NFS snapshot class name used in internal consumer distribution

controllers/ocsinitialization/ocsinitialization_controller.go
[DFBUGS-1272](https://issues.redhat.com/browse/DFBUGS-1272)
Add node toleration to prometheus operator pod
=> Add node toleration to prometheus operator pod

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
Following discussion on https://issues.redhat.com/browse/DFBUGS-2391 & ODF Weekly call it was decided to make mon_target_pg_per_osd = 400 always, both for new & upgraded clusters. This was decided based on factors like
1. New & Upgraded clusters should not diverge in terms of behavior
2. Old customers are able to utilize the performance gain from this
This will trigger a data movement upon upgrade from 4.18 to 4.19. We have to add upgrade notes, release notes notifying customers of the data movement & the health warning that would appear upon upgrade.
=> Make mon_target_pg_per_osd = 400 always both for new & upgraded clusters

api/v1alpha1/storageconsumer_types.go, config/crd/bases/ocs.openshift.io_storageconsumers.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml, deploy/ocs-operator/manifests/storageconsumer.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
Added CEL validation to ensure StorageQuotaInGiB cannot be decreased via CR updates.
Tested manually:
1.Delete the old CRD, apply the new CRD, and verify that the CRD was created.
```
$ oc delete crd storageconsumers.ocs.openshift.io
customresourcedefinition.apiextensions.k8s.io "storageconsumers.ocs.openshift.io" deleted
$ oc get crd storageconsumers.ocs.openshift.io
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "storageconsumers.ocs.openshift.io" not found
$ oc apply -f config/crd/bases/ocs.openshift.io_storageconsumers.yaml
customresourcedefinition.apiextensions.k8s.io/storageconsumers.ocs.openshift.io created
$ oc get crd storageconsumers.ocs.openshift.io
NAME                                CREATED AT
storageconsumers.ocs.openshift.io …
```
=> Prevent quota reduction via CEL validation in StorageConsumer CRD

controllers/storageautoscaler/scraper.go, controllers/storageautoscaler/scraper_test.go, controllers/storageautoscaler/storageautoscaler_controller.go, controllers/storageautoscaler/storageautoscaler_controller_test.go
add a another check for scaling to scale only when more than threshold minus 10% of cluster is full
in some cases ceph takes time to balance the osd,
so its important to calculate the total cluster size for a device class
=> storageautoscaler: scale only when more than threshold minus 10% percent of cluster is used

controllers/mirroring/mirroring_controller.go, controllers/storageclusterpeer/storageclusterpeer_controller.go
add a finalizer to stop deletion of storageclusterpeer if storageclientmapping configmap is created. This will ensure that if storageclusterpeer is marked for deletion before configmap the dr uninstall will not get stuck
Fixes: https://issues.redhat.com/browse/DFBUGS-2407
=> controllers: prevent deletion of storageclusterpeer

controllers/storagecluster/cephblockpools.go
In a cluster if customer has specified the replication size for the default CephBlockPool for example 2, then the .mgr pool should also have the same replication size. This will majorly help in prototyping ODF for 2 node cluster as for all other pools we have ways to specify the replication size but not for the .mgr pool.
Ref-https://issues.redhat.com/browse/DFBUGS-2568
=> Follow the replicate size of the default CephBlockPool for the .mgr pool

metrics/internal/collectors/storageconsumer.go
This PR introduces a nil check for the `Client` object under `StorageConsumer` in `metrics-exporter` since it has been changed to use pointer semantics.
- **Currently**: When a `StorageConsumer` resource lacks a valid `Client`, the `ocs-metrics-exporter` pod encounters a nil pointer dereference, causing it to enter a `CrashLoopBackOff` state and finally an
```
NAME                                   READY    STATUS            RESTARTS      AGE
ocs-metrics-exporter-b84c6797d-w5d9t   2/3      CrashLoopBackOff  5 (48s ago)   24m
```
- **With the fix**: `ocs-metrics-exporter` continues to run without an error even without a valid `Client`. 
Fixes: [DFBUGS-2509](https://issues.redhat.com/browse/DFBUGS-2509)
=> add nil check for client in metrics exporter

deploy/ocs-operator/manifests/provider-role.yaml, rbac/provider-role.yaml, services/provider/server/server.go
When the channel of the ocs-operator subscription is changed (e.g., from stable-4.18 to stable-4.19), this update is immediately propagated to the client, triggering its upgrade. However, if the client upgrades before the provider has completed its own CSV upgrade, the provider may detect that the client is ahead and mark itself as NotUpgradeable, blocking the upgrade process.
This commit ensures that the updated channel information is only sent to the client after the provider's CSV has reached the Succeeded phase. This prevents premature client upgrades and avoids upgrade deadlocks caused by version skew between provider and client.
Ref- https://issues.redhat.com/browse/DFBUGS-2502
=> Send OCS sub channel only if the current CSV of the sub has succeeded

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
There were concerns of additional memory load on the OSDs with the increased mon_target_pg_per_osd value of 400. To mitigate this, we are setting the mon_target_pg_per_osd value based on the resource profile. By default for the balanced profile, the value is set to 200. For the lean profile, the value is set to 100. For the performance profile the value is set to 400.
https://issues.redhat.com/browse/DFBUGS-2569
=> Set mon_target_pg_per_osd based on the resource profile

controllers/storagecluster/reconcile.go, controllers/storagecluster/storageclient.go, controllers/storagecluster/storageconsumer.go
Deletion of internal client/consumer shouldn't be allowed, and they should be removed only when storageCluster is deleted.
To ensure the same, finalizers would be added to storageConsumer and storageClient in such a way that they can only be deleted when the storageCluster is deleted. 
Resolves: [DFBUGS-2333](https://issues.redhat.com/browse/DFBUGS-2333)
=> controllers: add finalizers for internal client/consumer

controllers/storagecluster/external_resources.go, controllers/storagecluster/external_resources_test.go, controllers/storagecluster/storageconsumer.go, controllers/storagecluster/volumegroupsnapshotterclasses.go, controllers/storagecluster/volumesnapshotterclasses.go, controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go, services/provider/server/server.go
1) Adding labels to external storageclass and external volume snapshot and volume group snapshot storageclaaes, so distinguish between internal and external storageclass
2) Add a filter to deafult storageconsumer to not use the external classes 
3) Adding filter in provider reconcile to not distribute external storageclasses to the clients
=> external: add external mode label to storageclasses

services/provider/server/server.go
Instead of returning nil and error, `FullFillStorageClaim` will return empty `FullFillStorageClaimResponse` and no error
=> server: FullFillStorageClaim returns empty response and no error

controllers/storagecluster/storageconsumer.go, controllers/util/storageclasses.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go, services/provider/server/server.go
We are adding the disable key rotation annotation from the storageCluster to the internal storage consumer. And based on that annotation, we will add the key rotation annotation to the storageClass.
Ref-https://issues.redhat.com/browse/DFBUGS-2288
=> Add disable key rotation annotation only for the internal client

controllers/mirroring/mirroring_controller.go, controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go, services/provider/server/server.go
This PR does the following:
1. Removes the hack we had to fetch the rbd StorageID to fetch it from the GetStorageClientsInfo rpc
2. Generate clientProfileMapping with the right local and remote clientProfiles
This is a followup PR to https://github.com/red-hat-storage/ocs-operator/pull/3260
Review only the last two commits
Fixes: https://issues.redhat.com/browse/DFBUGS-2307
=> rdr: update peer storageID and clientProfile to be fetched from the peerClientInfo annotation

services/provider/server/server.go
This PR addresses the bug where read affinity was not configured in the CephConnection resource.
Adds ReadAffinity section with default CrushLocationLabels:
```
"topology.rook.io/chassis", "topology.rook.io/rack", "topology.rook.io/row", "topology.rook.io/pdu", "topology.rook.io/pod", "topology.rook.io/room", "topology.rook.io/datacenter", "topology.kubernetes.io/region", "topology.kubernetes.io/zone", "kubernetes.io/hostname"
```
This change ensures that CSI read affinity is enabled by default.
=> Enable ReadAffinity with default CrushLocationLabels in CephConnection

controllers/storagecluster/reconcile.go
The client version might be updated on the client side by manual action. If that happens the hub would be blocked from upgrading the provider. To avoid that, we should not block the provider upgrade if the client version is greater than the provider version.
=> Do not block provider upgrade if client is having a greater version

controllers/mirroring/mirroring_controller.go
the mirroring controller should remove finalizer from scp first and then from configmap because if there is an error while removing finalizer from scp, it will remain as configmap will be deleted
Fixes: https://issues.redhat.com/browse/DFBUGS-2776
=> controllers: remove finalizer in right order

deploy/ocs-operator/manifests/provider-role.yaml, rbac/provider-role.yaml, services/provider/server/server.go
We just discovered there can be multiple catalogSources with the same name & namespace. So we need to filter the list with the catSrc Name & Namespace of the subscription to get the correct packageManifest.
=> Filter packageManifests with the catalogSource Name & Namespace

controllers/storagecluster/reconcile.go
The client version might be updated on the client side by manual action. If that happens the hub would be blocked from upgrading the provider. To avoid that, we should not block the provider upgrade if the client version is greater than the provider version.
=> DFBUGS-2833: [release-4.18] Do not block provider upgrade if client is having a greater version

config/rbac/role.yaml, controllers/defaults/defaults.go, controllers/storagecluster/storageconsumer.go, controllers/storageconsumer/storageconsumer_upgrade_controller.go, controllers/util/k8sutil.go, controllers/util/storageconsumer.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/defaults/defaults.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
The internal Client/consumer in provider mode needs to be handled differently.
We need to onboard the client to the internal consumer. Hence, from the upgrade controller, we are creating a consumer/configMap, updating the client status to point to this new consumer, and in the end, deleting the old storage consumer.
Fixes: https://issues.redhat.com/browse/DFBUGS-2290
=> controller: handle internal client in provider mode upgrade 

controllers/storagecluster/cephcluster.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storageconsumer.go, controllers/util/storageconsumer.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
The PR does the following:
1. Skip default csi user creation by rook
2. Fill the internal and fresh deployment configmap with the correct values for the csi secret names
=> controllers: update the consumer configmap default values

controllers/storageconsumer/consumer_test.go, controllers/storageconsumer/storageconsumer_controller.go, controllers/util/k8sutil.go, controllers/util/storageconsumer.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/common.sh, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go, services/provider/server/server.go
This PR does the following:
1. Create the cephClients with the desired name based on the generation and consumer UID
Review only the last commit
=> consumer: update the naming convention for the ceph clients

hack/common.sh, hack/install-ocs-operator.sh
Update client operator dependencies & Add new dependencies for it to the install script as well. Remove the deployment ready check as during the bundle run operator-sdk will wait for the csv to be succeeded which in turn waits for the deployment to be ready.
=> Update ocs-client-operator bundle image & it's dependencies

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/storagecluster_controller_test.go, controllers/util/env.go, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/common.sh, hack/generate-unified-csv.sh, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/env.go, tools/csv-merger/csv-merger.go
=> set ceph daemons key rotation policy

api/v1/storagecluster_types.go, controllers/defaults/resources.go, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/defaults/resources.go, tools/csv-merger/csv-merger.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
This PR adds the default requests and limits for the ocs-operator pods.
The default metrics are set for the following pods
- ocs-operator
- ocs-metircs-exporter
- ux-backend
- crash-collector
- log-collector
=> Add default requests and limits for ocs-operator pods

controllers/defaults/utils.go, controllers/defaults/utils_test.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/defaults/utils.go
On IBM Z platform the individual CPU cores are much more powerful than other architectures. Hence, we halve the CPU requests of daemons to optimize resource usage.
Ref-https://issues.redhat.com/browse/RHSTOR-7611
=> Halve the CPU requests of daemons for IBM Z platform

controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/prometheus/localcephrules.yaml
When ceph health reports pool to be near full or full, then raise an alert
=> Add alerts for CephPoolNearFull and CephPoolFull

controllers/util/storageclasses.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go, services/ux-backend/handlers/expandstorage/handler.go
This patch sets the key rotation annotation by default on encrypted RBD storageclasses.
=> storageclasses: automate key rotation for encrypted RBD storageclasses

controllers/storagecluster/prometheus/localcephrules.yaml
The label in the query had an extra underscore
=> Fix typo in alert query CephPoolNearFull

services/provider/server/server.go
This PR includes - 
- adds controllerPublishSecret (provisioner secret) to
ClientProfile.Spec.(RBD|CephFs).CephCsiSecrets.ControllerPublishSecret{}
=> csi: add controllerPublishSecret to ClientProfile

controllers/storagecluster/storageclient.go, controllers/storagecluster/storageclient_test.go
**VERY IMPORTANTLY:** I haven't had time to test this fix in a deployed dev environment. I am quite confident that the issue is resolved, especially by new unit tests. Depending on priorities, this might be merged and then validated by QE without further dev testing. Otherwise, a dev will have to pick up the testing portion of this change. For now, I am leaving this as a draft so that it won't be merged.
-------------
The existing `getCephNetworkAnnotationValue()` function and the immediate caller behavior made the assumption that any StorageCluster/CephCluster deployed with Multus enabled was required to include a `public` network selection.
In reality, `public` and `cluster` networks can be selected independently and individually. Update the function and its caller to support …
=> fix annotation error in multus cluster-only environs

OWNERS
I already do review & approve PRs in the repo via the admin access by manually adding the labels. This change will allow me to automatically approve and review PRs without needing to add labels manually.
=> Add malayparida2000 to approvers and reviewers in OWNERS file

functests/setup_teardown.go
After some discussion & thoughts, we decided to always collect the ocs must-gather irrespective of test result. This would help a lot in verifying the results of any fix whether or not that fix actually results in a test failure. We acknowledge that this would result in sight increase in the time taken to run the tests. But this would help a lot in looking at the impact of any PR readily.
=> Always collect ocs must-gather irrespective of test result

controllers/storageconsumer/storageconsumer_controller.go
UI requires us to add the blockpool name label to the rns to display mirroring information on the blockpools page
This was initially added to rns created by the storagerequest controller, but it was missed while creating the RNS in the storageconsumer controller
Original PR: https://github.com/red-hat-storage/ocs-operator/pull/2883
Fixes: https://issues.redhat.com/browse/DFBUGS-2832
=> controllers: add blockpool label to rns

controllers/storagecluster/cephnfs.go
msg="Failed to determine correct type of scrape target." component=
"scrape manager" scrape_pool=serviceMonitor/openshift-storage/
ocs-storagecluster-cephnfs-servicemonitor/0 target=
http://10.131.4.20:9587/metrics content_type="" fallback_media_type=
"" err="non-compliant scrape target sending blank Content-Type and no
fallback_scrape_protocol specified for target"
Prometheus v3 is more strict concerning the Content-Type header received when scraping. If a scrape target is not providing the correct Content-Type header the fallback protocol can be specified using the fallback_scrape_protocol parameter.
Fix-https://issues.redhat.com/browse/DFBUGS-3883
=> Fix no fallback_scrape_protocol specified for target with nfs metrics

config/rbac/role.yaml, controllers/storagecluster/cephtoolbox.go, controllers/storagecluster/exporter.go, controllers/storagecluster/reconcile.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-metrics-exporter-hostnetwork-role-binding.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, rbac/ocs-metrics-exporter-hostnetwork-role-binding.yaml
ocs-metrics-exporter and toolbox needs to run on host network for data replication separation as pod network will not have access to secondary host network and will not be able to execute ceph commands
=> ocs-metrics-exporter and toolbox needs to run on host network for data replication separation

services/provider/main.go, services/provider/server/consumer.go, services/provider/server/server.go, services/provider/server/server_test.go
This PR creates a subset logger from ctx for each endpoint. While logging, we log the endpoint name along with the key params the call is working on. This PR also logs the request received for each endpoint.
Fixes: [DFBUGS-2316](https://issues.redhat.com/browse/DFBUGS-2316)
=> server: improve logging for server

controllers/util/replicationclasses.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/replicationclasses.go, services/provider/main.go, services/provider/server/consumer.go, services/provider/server/server.go, services/provider/server/server_test.go
This is a manual backport for https://github.com/red-hat-storage/ocs-operator/pull/3450 and https://github.com/red-hat-storage/ocs-operator/pull/3473
3450 adds the rename capability for VRCs
3473 improves the logs in provider server
=> DFBUGS-2316: [release-4.20] server: improve logging for server

controllers/storagecluster/cephfilesystem.go
enable the mds livenessProbe
As the jq support was added back in the ceph image 
```
Ceph has added jq back in ceph image from 19.2.1-244.el9cp
https://bugzilla.redhat.com/show_bug.cgi?id=2354764#c11
```
This reverts commit 3d8bba4fc8f184f6634610a9ddc37b9dae6650b3.
=> mds: enable the mds livenessProbe

deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/cluster_monitoring_view_prometheus_k8s_role_binding.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, rbac/cluster_monitoring_view_prometheus_k8s_role_binding.yaml, templates/k8smetricsservicemonitor.go
Fixes
- https://issues.redhat.com/browse/DFBUGS-224
-  https://issues.redhat.com/browse/DFBUGS-370
=> Create ClusterRoleBinding to fetch in-cluster monitoring metrics
