version/version.go
Testing the new CI integration.
=> Fix lint issues for CI

Makefile, must-gather/Dockerfile, must-gather/OWNERS, must-gather/README.md, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_noobaa_resources
This commit adds code for ocs-must-gather and also implements Makefile for building the ocs-operator and ocs-must-gather images.
=> enhance: Adds code for OCS-must-gather

design/fencing_mitigation.md
=> [Design] Fencing mitigation.

OWNERS
Currently, only one reviewer/approver is available and we need to
progress. We will figure out a more appropriate OWNERS file soon.
=> Extend the OWNERS file to unblock a merging impasse

deploy/Dockerfile, hack/build-registry-bundle.sh
Fixes #17.
Also, don't push the registry image automatically.
=> Move manifests to different location in registry image

README.md
Also, added bullets for the items created by the deploy-olm manifest to 
be more visual.
=> Fixed a broken link and Openshift

must-gather/README.md
This commit updates ocs-must-gather image registry with upstream in readme.md
=> Updates ocs-must-gather image registry with upstream

README.md
Fixes #38.
Signed-off-by: Petr Balogh <pbalogh@redhat.com>
=> Add CSV check to the documentation

Makefile
In order to force the usage of the vendor dir for builds, we need to add the 'mod=vendor' go build flag. However, in order to add the go build flag, we need to ensure we're using a operator-sdk version that supports passing in go build flags.
To address both of these issues, I added logic to our Makefile that ensures we're all using a specific version of the operator-sdk cli when performing builds (cached into build/_output/tools). Then I added the ```--go-build-args="-mod=vendor"``` flag to the ocs-operator build.
The result is the build should be forced to use the packages within the vendor directory. If something isn't present within the vendor directory, then the build should fail.
=> Lock operator-sdk version and force use of vendor dir for builds

build/Dockerfile
=> updates build/Dockerfile to use ubi8-minimal base image

pkg/apis/ocs/v1alpha1/ocsinitialization_types.go, pkg/controller/ocsinitialization/ocsinitialization_controller.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller.go, pkg/controller/util/status.go, test/crd_validation_test.go
This fixes the issues found in `go fmt -s` command and also fixes the misspelled word.
=> run go fmt tool

pkg/controller/ocsinitialization/ocsinitialization_controller.go, pkg/controller/storagecluster/reconcile.go
Follow up for #51.
Placement Configurations for different components:
=> follow-up for openshift/ocs-operator/pull/51

pkg/controller/storagecluster/reconcile.go, pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
- added topologyKey to podAntiAffinity
=> fixes rook components placement config

README.md
=> Updated README.md to include node label/taint details

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
=> Don't enforce fixed name for StorageClusterInit

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
=> Change failure domain to zone for all cephv1.PoolSpecs

README.md
This updates the README to make it clear when to use taints.
=> doc: Clarify tainting of nodes

pkg/controller/storageclusterinitialization/noobaa_system_reconciler.go, pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
This commit adds OwnerReference info to resources created by the storageClusterInitialization CR.
=> Adds Owner Reference info to storageClusterInitialization resources

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller.go, pkg/controller/storagecluster/storagecluster_controller_test.go, pkg/controller/util/status.go
- previous implementation gave inaccurate information about cluster
expansion and NotReady phases
=> updated StorageCluster controller to reflect accurate .Status.Phase

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
=> Default RBD storageclass to "ext4"

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
This reverts commit 20336cfbbafccd11d9203fd01abf49d5b31b1f44.
=> Revert "storageclusterinit: Use provided CEPH_IMAGE for toolbox"

deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, hack/latest-csv-checksum.md5, tools/csv-merger/csv-merger.go
- enables listing of Resources managed by StorageCluster CR
=> adding Resources spec to CSV for owned StorageCluster CRD

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_noobaa_resources
This commit adds support to collect the output of ceph volume prepare logs from nodes.
=> enhance(must-gather): Adds support to collect osd prepare logs

hack/source-manifests.sh
This PR adds some print statements during the csv generation that should help indicate at what step the csv generation may be failing at.
=> Additional debug output when generating latest csv

deploy/deploy-with-olm.yaml, go.mod, pkg/deploy-manager/common.go, pkg/deploy-manager/subscription.go
- this is to enable monitoring by OCP Prometheus
=> adding appropriate label to namespace created

go.mod, must-gather/Dockerfile, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_noobaa_resources
This commit freezes the ocs-must-gather base image to `quay.io/openshift/origin-must-gather:4.2`.
=> fix(must-gather): Freezing ocs-must-gather base image to 4.2

pkg/controller/storageclusterinitialization/noobaa_system_reconciler.go
When a failure occurred while trying to get noobaa cr using `client.Get()`, only "not found" errors were handled. all other errors were ignored.
=> fixed error handling when failing to Get noobaa cr

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
=> storageclusterinit: Set Spec.DataPool for CephObjectStore

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
=> zone detection: check for nil topology labels

pkg/controller/storageclusterinitialization/storageclusterinitialization_controller.go
=> Bug 1759288: storageclusterinit: Set Spec.DataPool for CephObjectStore

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources
This commit adds support to collect storagecluster resources using OCS-must-gather.
Signed-off-by: Rajat Singh <rajasing@redhat.com>
=> must-gather:Adds support to collect ocs related operator logs

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources
Backport of PR https://github.com/openshift/ocs-operator/pull/219
=> Bug 1762236: must-gather doesn't collect openshift-storage pod logs if StorageCluster creation is not yet triggered

must-gather/collection-scripts/gather_noobaa_resources
Backport of PR https://github.com/openshift/ocs-operator/pull/222
=> Bug 1764525: must-gather : error in syntax reported during ocs must-gather

must-gather/Dockerfile, must-gather/collection-scripts/gather_ceph_resources
Backport of PR https://github.com/openshift/ocs-operator/pull/233
=> Bug 1757863: most must_gather_commands files with output of ceph commands are empty

pkg/deploy-manager/storagecluster.go
Previously we were checking for a canary per osd, when the validation should have been one canary per node an osd runs on.
=> Check for one canary per node running osd

functests/config.go, functests/storagecluster_creation_test.go, go.mod, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller.go, pkg/deploy-manager/config.go, pkg/deploy-manager/storagecluster.go
=> Bug 1751956: Operator shouldn't allow creation of a second StorageCluster in the same namespace

deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, go.mod, go.sum, hack/generate-latest-csv.sh, hack/latest-csv-checksum.md5
=> Update noobaa to 2.0.4

tools/csv-merger/csv-merger.go
=> Fix indentation in csv-merger

go.mod, pkg/controller/storagecluster/reconcile.go
Missed a newline in the Ceph config override. Also a few linting changes.
=> Fix Ceph config override data formatting

pkg/controller/storagecluster/reconcile.go
=> Bug 1765550: Fix Ceph config override data formatting

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
(cherry picked from commit ab3bede8b977fcf69ffefabe7f8b12a04b9109c8)
=> Bug 1767993: zone detection: check for nil topology labels

functests/must-gather_test.go, go.sum, hack/common.sh, hack/functest.sh, must-gather/functests/functests.sh, must-gather/functests/integration/command_output_test.sh
This commit adds integration test for must-gather which checks whether the commands output collection functionality of ocs-must-gather.
=> enhance(must-gather): Adds integration test for must-gather

must-gather/Dockerfile, must-gather/collection-scripts/gather_ceph_resources, must-gather/templates/ceph.conf.template, must-gather/templates/keyring.template, must-gather/templates/pod.template
This commits enhances must-gather to use a helper pod for collecting ceph command output.
=> enhance(must-gather): Use helper pod for collecting ceph output

must-gather/collection-scripts/gather_ceph_resources
This commit adds support to collect out of non running pod by the must-gather
=> enhance(must-gather): Adds support to collect output of non running pods

hack/cluster-clean.sh
This logic takes advantage of the fact that the StorageClusterInitialization object doesn't recreate NooBaa objects if we delete them. This means you can techincally delete the noobaa object and resulting pvcs, then tear down the rest of the cluster without using cascade=false on certain objects.
=> Simplified cluster clean logic

must-gather/collection-scripts/gather_ceph_resources
This commit adds support to collect out of non running pod by the must-gather
=> Bug 1770941: must-gather does not collect logs of Completed , Running 0/1 or CBLO ocs pods

pkg/controller/storagecluster/initialization_reconciler_test.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
=> Check for minimum number of storage nodes

pkg/controller/storagecluster/initialization_reconciler_test.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
=> Bug 1768874: Check for minimum number of storage nodes

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
This change ensures that if a cluster has already been assigned the
rack failure domain in previous reconcile loops, it will continue
to use that failure domain.
Signed-off-by: Elise Gafford <egafford@redhat.com>
=> Preserve rack FailureDomain if previously assigned

must-gather/collection-scripts/gather_ceph_resources
Add request timeout option in ceph commands
Fixing must-gather ceph resources accordind to shell check
and adding timeout for ceph commands
Fixing must-gather ceph resources accordind to shell check
and adding timeout for ceph commands
Add request timeout option in ceph commands
=> Bug 1770293: Add timeout for ceph commands

must-gather/collection-scripts/gather
This commit modifies must-gather to remove collection of empty files and directories from the dump collected.
=> enhance(must-gather): Removes collection of empty files

must-gather/collection-scripts/gather_ceph_resources
This commit updates gather script to collect pod spec of non-running pods.
=> fix(must-gather): Updates gather script to collect pod spec of non-runing pods

must-gather/collection-scripts/gather_ceph_resources
=> Bug 1775059: Collect yaml file for osd-prepare pods in ocs-must-gather

must-gather/collection-scripts/gather_ceph_resources
This commit fixes must-gather not able to collect output of ceph command.
=> fix(must-gather): fixes must-gather not able to collect o/p of ceph commands

must-gather/collection-scripts/gather_ceph_resources
This commit fixes collection of ceph volume command o/p and prepare volume log .
=> fix(must-gather): fix collection of ceph volume o/p and prepare volume log 

must-gather/collection-scripts/gather_ceph_resources
=> Bug 1776723: must_gather_command folder does not have any ceph command output files

deploy/olm-catalog/ocs-operator/0.0.1/ocs-operator.v0.0.1.clusterserviceversion.yaml, hack/latest-csv-checksum.md5, tools/csv-merger/csv-merger.go
=> Bug 1778805: deploy: Disable csi-snapshotter in Rook deployment

pkg/controller/defaults/resources.go
=> Bug 1780157: defaults: Reduce CPU request for OSD to 1

OWNERS
I still keep getting assigned for reviews. So removing myself from the list.
=> Remove kshlm from OWNERS

functests/cluster_upgrade_test.go
enabling ocs upgrade test that was disabled to unblock CI
at #321 
=> functest: enabling upgrade test

functests/must-gather_test.go
=> functest: Always output must-gather info

openshift-ci/Dockerfile.deploy
=> ci: Use ubi8 base for test images

must-gather/collection-scripts/gather
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1795120
=> Add output of oc commands in must-gather

pkg/controller/storagecluster/initialization_reconciler.go, pkg/controller/storagecluster/reconcile.go
=> Bug 1797918 - Enables balancer module

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
This commit updates the reconcile logic to use storageDeviceSet PVC template for mons if no monPVCTemplate is provided. The reconcile flow after this commit is as follows.
1. If the `monPVCTemplate` is provided, the mons will be provisioned on the provided `monPVCTemplate`.
2. If the `monDataDirHostPath` is provided without the `monPVCTemplate`, the mons will be provisioned on the provided `monDataDirHostPath`.
3. If no `monPVCTemplate` and no `monDataDirHostPath` is provided, the mons will be provisioned using the PVC template of first StorageDeviceSets if present.
=> Updates the reconcile logic to use storageDevicePVC for mons

pkg/controller/storagecluster/noobaa_system_reconciler.go, pkg/controller/storagecluster/noobaa_system_reconciler_test.go
- Restructure the code to use CreateOrUpodate (from controllerutils) which get, create and update, instead of doing it manually.
- Reconcile specific props of the NooBaa CR, stated by the setNooBaaDesiredState func, instead of blindly override everything in the NooBaa CR. (leaving some form of autonomy over the NooBaa CR).
=> Change noobaa system reconcile to use "smart" desired state

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
=> Check for nil pointer with StorageClass name

pkg/controller/storagecluster/reconcile.go
=> Pedantic spelling corrections for StorageClass

functests/cluster_upgrade_test.go
The upgrade test is facing some issues.
It is being disabled while it is being fixed.
=> Disable upgrade test.

OWNERS
=> Add Umanga to the OWNERS.

pkg/controller/storagecluster/reconcile.go
This commit changes the job name consistent with the template name also
adds the flag --force and --yes-i-really-mean-it on ceph purge command
=> Changed job name and added --force flag

openshift-ci/Dockerfile.tools
=> adds gcc to build tools

must-gather/collection-scripts/gather
Fixing: https://bugzilla.redhat.com/show_bug.cgi?id=1823886
=> Add get subscription command in must-gather

pkg/controller/storagecluster/reconcile.go
This change prevents running osd from being marked out if running osd id is
provided by a user to the osd removal job template.
A constant purgeOSDScript is created with the bash scipt in it which finds the osd status of given a FAILED_OSD_ID.
If osd is up and running, osd will not be marked out. If osd status is down, it will be
taken out of the cluster and purged.
(cherry picked from commit 969317a8c350174766a200b7c595dc43c1b9bd79)
=> Bug 1833317: Added script to avoid healthy osd from marking out

must-gather/collection-scripts/gather_ceph_resources
https://bugzilla.redhat.com/show_bug.cgi?id=1806953
=> Add rbd, subvolume and listing of pool names command in ceph must-gather

must-gather/collection-scripts/gather_noobaa_resources
https://bugzilla.redhat.com/show_bug.cgi?id=1833880
=> Add noobaa raw output for noobaa obc list

pkg/controller/storagecluster/placement.go
This was broken strangely.
This is making it easier to read.
=> Improve formatting in getPlacement()

pkg/controller/storagecluster/reconcile.go
=> Simplify getStorageClusterEligibleNodes() a bit more

must-gather/collection-scripts/gather_ceph_resources
Add more ceph commands to ease debugging as well as ordering the
commands for visibility.
=> must-gather: add more ceph commands

pkg/controller/ocsinitialization/sccs.go
We want to create a noobaa own secure context in order to fix these two issues:
https://bugzilla.redhat.com/show_bug.cgi?id=1835125
https://bugzilla.redhat.com/show_bug.cgi?id=1804168
Currently trying to validate if this fix indeed resolves our upgrade issue
Signed-off-by: jackyalbo jalbo@redhat.com
=> Creating a new noobaa SCC

pkg/controller/storagecluster/platform_detection.go
https://bugzilla.redhat.com/show_bug.cgi?id=1825994
=> Fix GCP cloud platform ProvideID is gce(google compute engine)

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storageclusterinit.go
Moved the logic for `StorageClusterInit` in a new file for better clarity and understanding.
=> Refactor: Moving StorageClusterInit in a new file.

pkg/controller/defaults/resources.go
=> Update OSD QoS to Guaranteed

pkg/controller/defaults/resources.go
(cherry picked from commit 3df72fbb4559d447776f0fdf42d5225736feceff)
=> Bug 1836359: Update OSD QoS to Guaranteed

pkg/controller/defaults/placements.go, pkg/controller/storagecluster/placement.go
https://bugzilla.redhat.com/show_bug.cgi?id=1774087
=> Prevent multiple mds from running on the same node

must-gather/collection-scripts/gather_noobaa_resources
https://bugzilla.redhat.com/show_bug.cgi?id=1833880
=> Fix a bad substitution

pkg/controller/storagecluster/reconcile.go
This change will remove the host associated with the failed osd from the
crush map. When node removal process is done and all osds have been
removed from that host, the empty host will be removed from crush map.
=>  Remove the host from crush map

must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_noobaa_resources
https://bugzilla.redhat.com/show_bug.cgi?id=1847487
=> must-gather: Add more timeout to ceph and noobaa resources

must-gather/collection-scripts/gather
https://bugzilla.redhat.com/show_bug.cgi?id=1853025
=> Add csv resource

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources
https://bugzilla.redhat.com/show_bug.cgi?id=1858778
=> must-gather: Add more resources to must-gather

deploy/olm-catalog/ocs-operator/manifests/backingstore.crd.yaml, deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/generate-latest-csv.sh, hack/latest-csv-checksum.md5
=> Update noobaa image reference and regenerate latest csv

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_noobaa_resources
https://bugzilla.redhat.com/show_bug.cgi?id=1858900
=> must-gather: Remove timeout option from oc inspect commands

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_noobaa_resources
Backport for [PR](https://github.com/openshift/ocs-operator/pull/658)
=> Bug 1858900:must-gather: Remove timeout option from oc inspect commands

deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/generate-latest-csv.sh, hack/latest-csv-checksum.md5
=> Update noobaa-core image

OWNERS
It's been a long time since I contributed, so my knowledge is out-of-date. I
also hope this will reduce or stop the occurrences of me being auto-assigned as
a reviewer of PRs, since that isn't helpful at this point.
=> removes mhrivnak (me) from OWNERS

OWNERS
Added myself to the OWNERS file
=> add agarwal-mudit(myself) to OWNERS file

pkg/controller/storagecluster/reconcile.go
Added annotation template.alpha.openshift.io/wait-for-ready to the
object of a kind Job. This change ensures template readiness
=> Added annotation to the Job

pkg/controller/storagecluster/cephblockpools.go
Part of https://github.com/rook/rook/pull/5680
=> enables RBD per image IO stats collection by default

docs/design/metrics-exporter.md
This is the design for Metrics Exporter which will be
used to export metrics related to Custom Resources of
interest to OCS.
=> Design document for Custom Resource Metrics Exporter

Makefile, build/Dockerfile.build, hack/build-container.sh, hack/common.sh, hack/go-build.sh
=> Containerize operator binary build

docs/design/template.md
=> Feature design template

build/Dockerfile.build
=> Correct the make target in the build container

pkg/controller/storagecluster/uninstall_reconciler.go
=> StorageCluster: log unknown error in deleteStorageClasses

pkg/controller/storagecluster/reconcile.go
This code setup the noobaa cleanup policy to destroy the obc
[1]. https://github.com/noobaa/noobaa-operator/blob/v2.3.0/pkg/apis/noobaa/v1alpha1/noobaa_types.go#L331
=> Add ability to set noobaa cleanup policy during uninstall

deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml, hack/latest-csv-checksum.md5, pkg/apis/ocs/v1/storagecluster_types.go, pkg/controller/storagecluster/cephfilesystem.go, pkg/controller/storagecluster/cephobjectstores.go, pkg/controller/storagecluster/cephobjectstoreusers.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storagecluster_controller_test.go
This reverts #675 due to some concerns over potential race conditions with deletion of some of the resources affected.
=> Bug 1857802: Revert PR #675

deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/csv-templates/rook-csv.yaml.in
=> Fix CSV templates after SnapshotClass update

pkg/controller/storagecluster/cephobjectstores.go, pkg/controller/storagecluster/cephobjectstores_test.go, pkg/controller/storagecluster/external_resources.go, pkg/controller/storagecluster/external_resources_test.go, pkg/controller/storagecluster/generate.go, pkg/controller/storagecluster/storageclasses.go
CephObjectStore creation in external cluster mode according to the latest rook-ceph changes
=> Ceph object store for external cluster

functests/ceph_tools_test.go, functests/cluster_upgrade_test.go, functests/data_validation_test.go, functests/must-gather_test.go, functests/pvc_creation_test.go, functests/storagecluster_creation_test.go, functests/storageclusterinitialization_test.go
=> Refactoring of all functional tests under `functest` dir

pkg/controller/storagecluster/reconcile.go
This is addresses some of the suggestions made in #718 . Keeping it as a separate PR.
Please merge this before merging #718 
cc: @iamniting
=> change from label to annotation for the uninstall-cleanup policy

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_clusterscoped_resources, must-gather/collection-scripts/gather_namespaced_resources
=> Re-structure of ocs-must-gather

deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/external_resources.go, pkg/controller/storagecluster/storagecluster_controller.go, tools/csv-merger/csv-merger.go
This PR is to enable monitoring on the external mode in OCS. 
The changes have been done in keeping mind that monitoring will be mandatory for OCS as the UI depends on it.
Depends on #638  for some functions and shall be merged post that.
Please review commit:  Enabled monitoring for external mode
=> Enable Monitoring for external mode

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_clusterscoped_resources, must-gather/collection-scripts/gather_namespaced_resources, must-gather/collection-scripts/gather_noobaa_resources
This can be used by using following commands:
oc adm must-gather --image=must-gather-image /usr/bin/gather since=5s
or
oc adm must-gather --image=must-gather-image /usr/bin/gather since-time=[specific date (RFC3339)]
resolves: https://github.com/openshift/ocs-operator/issues/356
=> must-gather: Add feature for collecting logs at particular time

pkg/controller/storagecluster/placement.go
=> StorageCluster: make readability enhancement

deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
=> Adding the CRDs missed while creating external reconcile PR

pkg/controller/storagecluster/exporter.go, pkg/controller/storagecluster/reconcile.go
The logr implementation encourages structured logging.
Fixes issue: #757 
=> Fixed incorrect logr usage

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml
This PR adds temporary placeholder Prometheus alert rule yamls to help https://github.com/openshift/release/pull/11528 to be merged.
=> Added temporary placeholder Prometheus alert rule yamls

docs/design/osd-topology-spread-constraints.md
=> Design: OSD Topology Spread Constraints

pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/uninstall_reconciler.go
It should be merged after https://github.com/openshift/ocs-operator/pull/753
=> Move the uninstall code from reconcile.go to uninstall_reconcile.go to organize it in better way.

pkg/controller/ocsinitialization/ocsinitialization_controller.go
=> fixed cephTools update when spec is changed

pkg/controller/storagecluster/storagecluster_controller.go, pkg/controller/storagecluster/storagecluster_controller_test.go, pkg/controller/storagecluster/topology_test.go
- added case tables in storagecluster_controller and topology (where ever applicable)
- improved unit test coverage
=> added case tables for storageCluster_controller unit tests

pkg/controller/ocsinitialization/ocsinitialization_controller_test.go
=> added case tables for ocsinitialization_controller_test.go

pkg/controller/storagecluster/exporter.go, pkg/controller/storagecluster/reconcile.go
=> Bug 1760426: [release-4.6] Enhance Uninstall logging and comments

pkg/controller/storagecluster/exporter.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/uninstall_reconciler.go
=> Bug 1760426: [release-4.6] Move the uninstall code from reconcile.go to uninstall_reconcile.go to organize it in better way.

pkg/controller/storagecluster/cephblockpools_test.go
=> Refactored cephblockpools_test.go to table-driven tests

pkg/controller/storagecluster/cephfilesystem_test.go
Signed off by Priyanka Jiandani: <pjiandan@redhat.com>
=> Refactored cephfilesystem_test.go to table-driven tests

pkg/controller/storagecluster/reconcile.go
Removed the bash script as we would be running an operator in order to
perform osd removal procedure.
=>  Avoid bash script to purge osds in job template

deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml, pkg/apis/ocs/v1/storagecluster_types.go, pkg/controller/storagecluster/external_resources.go, pkg/controller/storagecluster/external_resources_test.go
Cherry-picking the changes to `release-4.6` branch...
=> Bug 1865825: [release-4.6] External resource reconciliation

pkg/controller/storagecluster/uninstall_reconciler.go
Fix the typo retrive to retrieve in uninstall_reconciler logs
=> storagecluster: Fix typo in logs

pkg/controller/storagecluster/placement.go, pkg/controller/storagecluster/placement_test.go
=> Bug 1883767: Using placement strategies in cluster-service.yaml causes ocs-operator to crash

Makefile, functests/common.go, functests/data_validation_test.go, functests/pvc_creation_test.go, functests/setup_teardown.go, hack/common.sh, hack/functest.sh, pkg/deploy-manager/common.go, pkg/deploy-manager/config.go, pkg/deploy-manager/subscription.go
=> [release-4.6] e2e: Update from master

deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml, pkg/apis/ocs/v1/storagecluster_types.go, pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/topology.go, pkg/controller/storagecluster/topology_test.go
Allow the cluster to be expanded by one host at a time
=> Introduce flexible scaling

deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml
=> Add missing CSV changes for removing StorageClusterInitialization

pkg/controller/storagecluster/cephobjectstoreusers_test.go
=> Added table driven tests on cephobjectstoreusers_test.go

must-gather/collection-scripts/gather_noobaa_resources
=> must-gather: Fix shellcheck errors in gather_noobaa_resources

deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml, pkg/apis/ocs/v1/storagecluster_types.go, pkg/controller/storagecluster/noobaa_system_reconciler.go, pkg/controller/storagecluster/noobaa_system_reconciler_test.go, pkg/controller/storagecluster/reconcile.go
=> Allow NooBaa CR to not be reconciled

pkg/controller/storagecluster/uninstall_reconciler_test.go
Add test for deleteStorageClasses in uninstall_reconciler_test.go
=> UnitTests: Add test TestDeleteStorageClasses

pkg/controller/storagecluster/cephobjectstores_test.go
Signed of by: Priyanka Jiandani <pjiandan@redhat.com>
=> Added table driven tests to cephobjectstores_test.go

pkg/controller/storagecluster/external_resources.go
Signed-off-by: anmol sachan <anmol13694@gmail.com>
=> Bug 1888614: Changed the execution of connection closing, to avoid closing uncreated connection.

pkg/controller/defaults/placements.go
=> Fix Unbalanced distribution of OSD pods by TSC for more than 3 AZs

pkg/controller/storagecluster/noobaa_system_reconciler.go
Add Uninstall prefix in the deleteNoobaaSystems func and Fix https://bugzilla.redhat.com/show_bug.cgi?id=1886416
=> Enhance logging of deleteNoobaaSystems func

pkg/controller/storagecluster/exporter.go, pkg/controller/storagecluster/prometheus.go
=> Resolve errors reconciling metrics-exporter

pkg/controller/storagecluster/uninstall_reconciler_test.go
Add remaining tests for uninstall_reconciler.go
=> UnitTests: Add Uninstall tests

pkg/controller/defaults/placements.go
- Added helper functions to generate placement structs and added more function params to change values for a specific struct. 
- This will make each struct more flexible and will also reduce the complexity of structures that need to be written by hand.
=> refactor: helper functions to generate placement structs

must-gather/collection-scripts/gather_clusterscoped_resources
remove quotes as shellcheck error
is ignored
=> must-gather: Fix oc get command

must-gather/collection-scripts/gather_ceph_resources
=> must-gather: add jq command to must-gather helper pod

must-gather/collection-scripts/gather_ceph_resources
=> must-gather: delete helper pod after collecting ceph crash info

must-gather/collection-scripts/gather_noobaa_resources
=> must-gather: Fix noobaa script shellcheck errors

pkg/controller/storagecluster/cephobjectstoreusers.go, pkg/controller/storagecluster/storageclasses.go, pkg/controller/storagecluster/volumesnapshotterclasses.go
This PR fixes a few issues found when trying to reconcile the auxiliary managed resources.
=> Fix errors in managed resources reconciliation

cmd/manager/main.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/role.yaml, pkg/controller/storagecluster/cephblockpools_test.go, pkg/controller/storagecluster/cephfilesystem_test.go, pkg/controller/storagecluster/cephobjectstores.go, pkg/controller/storagecluster/cephobjectstores_test.go, pkg/controller/storagecluster/cephobjectstoreusers.go, pkg/controller/storagecluster/cephobjectstoreusers_test.go, pkg/controller/storagecluster/initialization_reconciler_test.go, pkg/controller/storagecluster/noobaa_system_reconciler_test.go, pkg/controller/storagecluster/platform_detection.go, pkg/controller/storagecluster/storageclasses.go, pkg/controller/storagecluster/storageclasses_test.go, pkg/controller/storagecluster/storagecluster_controller.go, pkg/controller/storagecluster/storagecluster_controller_test.go, pkg/controller/storagecluster/uninstall_reconciler_test.go, pkg/controller/storagecluster/volumesnapshotterclasses_test.go
This PR is w.r.t issue https://github.com/openshift/ocs-operator/issues/562
Signed off by: Priyanka Jiandani<pjiandan@redhat.com>
=> Use resource infrastructure instead of Nodes

deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
=> csv-merger: Add OCS Toleration to metrics-exporter

must-gather/collection-scripts/gather_ceph_resources
1. change log file names to rbd_vol_and_snap_info &
cephfs_subvol_and_snap_info
2. add subvolumegroup name (csi)
3. add snapshot count for cephFS subvolumes
=> must-gather: some improvements in snapshot info collection

pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/cephobjectstores.go, pkg/controller/storagecluster/cephobjectstores_test.go
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=1883828
=> NodeAffinity for rgw pods.

must-gather/collection-scripts/gather
remove / to make it compatible with noobaa cli
=> must-gather: remove / from BASE_COLLECTION_PATH

must-gather/collection-scripts/gather_ceph_resources
add ceph crash collection func and make it
run it a process for every storage node
=> must-gather: add ceph crash collection func

pkg/controller/storagecluster/cephblockpools.go, pkg/controller/storagecluster/cephfilesystem.go, pkg/controller/storagecluster/cephobjectstores.go, pkg/controller/storagecluster/cephobjectstoreusers.go, pkg/controller/storagecluster/reconcile.go, pkg/controller/storagecluster/storageclasses.go, pkg/controller/storagecluster/volumesnapshotterclasses.go
=> Default managed resources to 'manage'

pkg/controller/defaults/placements.go, pkg/controller/storagecluster/cephcluster.go
Fixes : #879 
Signed-off-by: kesavan kvellalo@redhat.com
=> Fix Adding multiple topology constraints for osd prepare pod

pkg/controller/storagecluster/placement.go, pkg/controller/storagecluster/placement_test.go
=> Properly set topologyKey in mon Placement

must-gather/collection-scripts/gather_clusterscoped_resources, must-gather/collection-scripts/gather_namespaced_resources
=> must-gather: Collect OBC, OB resources details

must-gather/collection-scripts/gather_ceph_resources
Fixed the path for ceph volume logs in the collection script.
Fixes #828
=> must-gather: Fix path for ceph volume logs.

deploy/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml, pkg/apis/ocs/v1/storagecluster_types.go, pkg/controller/storagecluster/reconcile.go
add new property in storagedeviceset
DeviceType is the property which will allow admin to add the device type in Storagecluster CR.
=> Add new property in storagedeviceset

must-gather/collection-scripts/gather_namespaced_resources
Signed-off-by: Nitin Goyal nigoyal@redhat.com
cc @raghavendra-talur
=> must-gather: collect OBC of all namespaces

deploy/olm-catalog/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
- Used by UI to block the radio button for External Mode
- UI fetches the CSV and compares it with the infrastructure it's running on
/assign @umangachapagain @jarrpa
=> Track platforms that support external mode from CSV

CONTRIBUTING.md
=> Change typo in contribution guide

hack/source-manifests.sh
=> hack: fix OCS Operator image in source-manifests.sh

controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/cephobjectstoreusers.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go, controllers/storagecluster/quickstarts.go, controllers/storagecluster/quickstarts_test.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/uninstall_reconciler.go, controllers/storagecluster/uninstall_reconciler_test.go, controllers/storagecluster/volumesnapshotterclasses.go
As part of this PR below tasks are done
[1] Introduce an interface resourceManager with ensureCreated and ensureDeleted funcs. 
[2] Create dummy/empty types to apply resourceManager interface on all OCS resources.
cc @raghavendra-talur
=> Refactor: Introduce an interface to enforce a developer to create a func for resource creation and deletion both

must-gather/collection-scripts/gather_clusterscoped_resources
Signed-off-by: jackyalbo <jalbo@redhat.com>
=> Must-gather: Add SCC to cluster-scoped must-gather

controllers/storagecluster/quickstart_constants.go
https://bugzilla.redhat.com/show_bug.cgi?id=1913277
Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>
=> Fixes typos and numberings for the list in Getting Started Quickstart

must-gather/OWNERS
Add rajatsing as reviwers and
remove ashishranjan738.
=> Must-gather: Update OWNERS file

controllers/storagecluster/noobaa_system_reconciler.go
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1915737
cc @raghavendra-talur
=> storagecluster: Enhance Noobaa ensureDeleted logging

docs/design/admission-webhooks.md
This is a new branch for work done in https://github.com/openshift/ocs-operator/pull/390
Adds a design document for supporting admission controllers in OCS
Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>
=> Design document for admission controllers in OCS

controllers/storagecluster/cephcluster.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/placement_test.go, controllers/storagecluster/reconcile.go, controllers/util/predicates.go, pkg/deploy-manager/config.go, tools/csv-merger/csv-merger.go
=> fix misspelling across codebase

controllers/storagecluster/placement_test.go, controllers/storagecluster/prometheus.go
=> remove ineffectual assignment from prometheus.go

controllers/storagecluster/cephcluster.go
Updated the CephCluster CRD to include ceph
logcollector settings
=> Add LogCollector to CephCluster CRD

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/post-uninstall.sh, must-gather/collection-scripts/pre-install.sh
problem: wait for different pods caused must-gather to execute by taking lot of time.
solution: for every pod must-gather creates should for only 5 minutes and debug pod can be used accros must-gather scripts.
=> Make must-gather more efficient 

must-gather/collection-scripts/gather
this pr will add the feature to show the total time take by the collection script.
=> must-gather: collect timestamp and total time taken by the MG

must-gather/collection-scripts/gather_ceph_resources
skip the ceph collection if helper not
in 1/1 state.
=> Must-gather: skip the ceph collection

must-gather/collection-scripts/pre-install.sh
add oc wait cmd and wait for the condition
to be true. make the check function run
in bg and wait for the pids to finish.
=> Must-gather: update pre-install.sh script

must-gather/collection-scripts/gather
this pr will fix the issue where the collection script was not able to log the total time taken by the must gather collection script
=> must-gather:log the total time taken by collection script

controllers/storagecluster/reconcile.go, controllers/util/events.go
Automated cherry-pick for https://github.com/openshift/ocs-operator/pull/1010 didn't work because of conflicts hence I am creating this request manually.
=> Bug 1913357: [release-4.7] Fail validation if arbiter and flexibleScaling both are enabled

must-gather/collection-scripts/post-uninstall.sh
add namespace in delete cmd and
remove label from deletion cmd.
=> Must-gather: update uninstall script

functests/setup_teardown.go
=> e2e: trigger must-gather on failed BeforeTestSuiteSetup

must-gather/collection-scripts/gather, must-gather/collection-scripts/post-uninstall.sh, must-gather/collection-scripts/pre-install.sh
with storage cluster deleted, MG should not attempt to bring up helper pod.
=> must-gather:do not create  helper pod if storagecluster is deleted

controllers/storagecluster/noobaa_system_reconciler.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, hack/common.sh
Signed-off-by: Danny Zaken <dannyzaken@gmail.com>
fix for https://bugzilla.redhat.com/show_bug.cgi?id=1922113
=> added DBType=postgres to noobaa CR

controllers/storagecluster/noobaa_system_reconciler.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, hack/common.sh
=> Bug 1922113: [release-4.7] - added DBType=postgres to noobaa CR

controllers/storagecluster/noobaa_system_reconciler.go
=> storagecluster: Fix noobaa uninstall logs

controllers/storagecluster/reconcile.go, controllers/util/events.go
=> storagecluster: Update uninstall error as an events

controllers/storagecluster/noobaa_system_reconciler.go
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1915737
=> Bug 1915737: [release-4.7] storagecluster: Fix noobaa uninstall logs

controllers/storagecluster/reconcile.go, controllers/util/events.go
=> Bug 1927338: [release-4.7] storagecluster: Update uninstall error as an events

functests/must-gather/must_gather_test.go, functests/ocs/ceph_tools_test.go, functests/ocs/cluster_upgrade_test.go, functests/ocs/data_validation_test.go, functests/ocs/ocs_test.go, functests/ocs/pvc_creation_test.go, functests/ocs/storagecluster_creation_test.go, go.mod, hack/build-functest.sh, vendor/modules.txt
=> Use Golang 1.15 for security fixes to Golang std library

functests/must-gather/must_gather_test.go, functests/ocs/ceph_tools_test.go, functests/ocs/cluster_upgrade_test.go, functests/ocs/data_validation_test.go, functests/ocs/ocs_test.go, functests/ocs/pvc_creation_test.go, functests/ocs/storagecluster_creation_test.go, go.mod, hack/build-functest.sh, vendor/modules.txt
=> Bug 1906016: [release-4.7] Use Golang 1.15 for security fixes to Golang std library

controllers/storagecluster/cephcluster.go, controllers/storagecluster/kms_resources.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/uninstall_reconciler.go
This PR is a backport for PR: https://github.com/openshift/ocs-operator/pull/1087
=> Bug 1925249: [release-4.7] Delete kms resources while uninstalling StorageCluster

must-gather/collection-scripts/gather_namespaced_resources
Signed-off-by: rewantsoni <resoni@redhat.com>
=> Must-Gather: Fix duplicate collection of objectbucketclaims

controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/platform_detection.go, controllers/storagecluster/storageclasses_test.go
Signed-off-by: Ambika Nair ambiknai@in.ibm.com
When the Cloud Provider is IBMCloud and Cos Secret is present, disable deployment of CephObjectStore
=> Disable CephObjectStore when the cloud provider is IBMCloud

must-gather/collection-scripts/gather_ceph_resources
=> must gather: small patch to fix the error message

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>
=> Enabled block pool tab under ocs operator

must-gather/README.md
Signed-off-by: Dhruv Bindra <dbindra@redhat.com>
=> must-gather: Readme update with how to contribute

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
This is a cherry-pick of #1113
This PR replaces the automated backport PR #1121
=> Bug 1922421:[release-4.7] Increase mon failover timeout to 15 min for IBMCloudPlatformType

deploy/csv-templates/crds/ocs.openshift.io_storageclusters_crd.yaml, deploy/olm-catalog/ocs-operator/manifests/storagecluster.crd.yaml, pkg/controller/storagecluster/cephcluster.go, pkg/controller/storagecluster/cephcluster_test.go, pkg/controller/storagecluster/platform_detection.go
This PR is cherry-pick of #1113
=> Bug 1937837: [release-4.6] Increase mon failover timeout to 15 min for IBMCloudPlatformType

controllers/storagecluster/cephblockpools_test.go, controllers/storagecluster/cephfilesystem_test.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/cephobjectstores_test.go, controllers/storagecluster/cephobjectstoreusers.go, controllers/storagecluster/cephobjectstoreusers_test.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/platform_detection.go, controllers/storagecluster/routes.go, controllers/storagecluster/routes_test.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storageclasses_test.go
=> Refactor Platform_detection.go

controllers/storagecluster/cephcluster.go, controllers/storagecluster/kms_resources.go, controllers/storagecluster/noobaa_system_reconciler.go
Adding one more KMS resource to delete.
=> Delete csi kms resource

controllers/storagecluster/external_resources.go, controllers/storagecluster/generate.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storageclasses_test.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
This PR also includes some missing CSV changes.
=> Create RBD StorageClass with thick provisioning

controllers/storagecluster/cephcluster.go
=> storagecluster: Fix intermediate ready phase in storage cluster during installation

controllers/storagecluster/reconcile.go
Implementing an automated way to recover from read-only mode
When cluster capacity reaches a critical limit, the cluster goes to read-only, and even delete operations are not permitted on the cluster. This job serves as a quick work way to recover from the read-only mode
Signed-off-by: Prajith Kesava Prasad <pkesavap@redhat.com>
=> [Ocs extend cluster limit] Implementing an automated way to recover from read-only mode

controllers/util/predicates.go
=> predicates: avoid theoretical nil pointer deref

controllers/ocsinitialization/sccs.go, deploy/bundle/manifests/namespacestore.crd.yaml, deploy/bundle/manifests/noobaa.crd.yaml, deploy/bundle/manifests/objectbucketclaim.crd.yaml, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/crds/noobaa/noobaa-crd.yaml, deploy/csv-templates/noobaa-csv.yaml, hack/common.sh, hack/source-manifests.sh
* updated the images to point to latest upstream builds
* fixed dump commands in source-manifests.sh
* Create noobaa-endpoint SCC which is required by noobaa endpoints 
Signed-off-by: Danny Zaken <dannyzaken@gmail.com>
=> updated noobaa core\operator images in common.sh

controllers/storagecluster/reconcile.go
=> fix noobaa core desired image

controllers/storagecluster/quickstart_constants.go
Some changes to Quickstart guide to match new design changes for release-4.8.
=> update quickstart guide for monitoring dashboards

must-gather/collection-scripts/gather
=> must-gather: collect noobaa logs independent of sc and external sc

must-gather/templates/pod.template.latest, must-gather/templates/pod.template.standard
=> must-gather: helper pod fails to run on tainted nodes

must-gather/collection-scripts/gather_ceph_resources, must-gather/collection-scripts/gather_namespaced_resources
=>  must-gather: collect logs for RegionalDR

deploy/bundle/manifests/namespacestore.crd.yaml, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/crds/noobaa/noobaa-crd.yaml, deploy/csv-templates/noobaa-csv.yaml, hack/common.sh
Bumped the version/images of NooBaa core and operator
=> Bumping NooBaa version

must-gather/collection-scripts/pre-install.sh
Signed-off-by: parthdhanjal <dparth@redhat.com>
=> MUST-GATHER: LOGS OF BG PROCESS IN PRE-INSTALL SCRIPT

pkg/controller/ocsinitialization/ocsinitialization_controller.go
(cherry picked from commit e524fc1ce339429ed4263796ea4a858e81678b0b)
=> Bug 1978578: [release-4.6] fixed cephTools update when spec is changed

controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/cephobjectstoreusers.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/kms_resources.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/prometheus.go, controllers/storagecluster/quickstarts.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/routes.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storagecluster_controller.go, controllers/storagecluster/topology.go, controllers/storagecluster/uninstall_reconciler.go, controllers/storagecluster/volumesnapshotterclasses.go, go.mod, vendor/modules.txt
=> Refactored logs for storagecluster controller

controllers/storagecluster/external_resources.go, controllers/storagecluster/generate.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storageclasses_test.go
Thick provisioning feature is now dev preview, hence removing
the sc creation.
=> Bug 1979263: [release-4.8] revert: creation of thick provisioned storage class in 4.8

must-gather/collection-scripts/gather_ceph_resources
=> must-gather: call gather_common_ceph_resources with proper args

controllers/ocsinitialization/ocsinitialization_controller.go
Container will run with privileged permissions but not as a root user.
Signed-off-by: bindrad <dbindra@redhat.com>
=> Ceph toolbox will run as non-root user

api/v1/storagecluster_types.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/storagecluster_controller_test.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, go.mod, go.sum, vendor/gotest.tools/v3/LICENSE, vendor/gotest.tools/v3/assert/assert.go, vendor/gotest.tools/v3/assert/cmp/compare.go, vendor/gotest.tools/v3/assert/cmp/result.go, vendor/gotest.tools/v3/assert/result.go, vendor/gotest.tools/v3/internal/difflib/LICENSE, vendor/gotest.tools/v3/internal/difflib/difflib.go, vendor/gotest.tools/v3/internal/format/diff.go, vendor/gotest.tools/v3/internal/format/format.go, vendor/gotest.tools/v3/internal/source/defers.go, vendor/gotest.tools/v3/internal/source/source.go, vendor/modules.txt
Looking for other places this might be touched in code. Will update then.
Necessary for IPv6 support so that IPFamily and dualstack can be specified: https://issues.redhat.com/browse/KNIP-1467
=> Change rookv1.NetworkSpec to cephv1.NetworkSpec and pass full networkspec if it is specified.

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go
Injecting default label to CephCluster monitoring labels.
`rook.io/managedBy=<StorageClusterName>` label is used to reference
owner of a CephCluster. This is merged with user provided
labels from StorageCluster.Monitoring.Labels.
If users provide label with `rook.io/managedBy` key, it will be overwritten by default.
```
NOTE:
A mutation webhook injecting labels to StorageCluster would be better,
but we don't have that today. So, this is minimal, less intrusive change
that doesn't require operator to update StorageCluster CR.
We cannot use default markers on api spec as we want this label to persist.
```
=> controller: inject default label to CephCluster

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/rules/rules.libsonnet
Required because of https://github.com/openshift/console/pull/9582#pullrequestreview-715764859
=> add recording rules for cephcluster latency metrics

deploy/bundle/manifests/exporter-role.yaml, metrics/internal/collectors/ceph-block-pool.go, metrics/internal/collectors/ceph-block-pool_test.go, metrics/internal/collectors/ceph-object-store.go, metrics/internal/collectors/ceph-object-store_test.go, metrics/internal/collectors/ceph-rbd-mirror.go, metrics/internal/collectors/ceph-rbd-mirror_test.go, metrics/internal/collectors/registry.go, metrics/internal/collectors/testUtil.go, rbac/exporter-role.yaml
Issue: [RHSTOR-1903](https://issues.redhat.com/browse/RHSTOR-1903)
Ceph Block Pool mirroring metrics to observe the storage DR behavior
1. Mirroring Status
2. Mirroring Image Health
3. Mirroring Daemon Status
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>
=> Pool mirroring metrics

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
Signed-off-by: Kaustav Majumder kmajumder@redhat.com
=> Allow DBStorageClass to be set from Storage Cluster CR for Noobaa

must-gather/collection-scripts/pre-install.sh
Signed-off-by: Rewant Soni <resoni@redhat.com>
=> Clean up before running must-gather

controllers/storagecluster/cephconfig.go
This PR addresses a few fixes and refactor changes to the cephconfig.go file
=> storagecluster: refactor error handling in cephconfig.go

hack/common.sh
=> hack: change ocs-must-gather image in openshift CI

OWNERS
Signed-off-by: Jose A. Rivera jarrpa@redhat.com
=> Add BlaineEXE to OWNERS

controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephblockpools_test.go
When mirroring is enabled on a CephBlockPool, it is valid to have an empty 
mirroringPeerSpec. Allow CephBlockPool reconciliation to succeed in this
scenario.
issue: https://issues.redhat.com/browse/RHSTOR-2140
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>
=> Fix StorageCluster reconcile failure when peerSecretNames is empty or invalid

controllers/storagecluster/volumesnapshotterclasses.go
=> Fix VolumeSnapshotClass creation for Ceph RBD

controllers/storagecluster/reconcile.go, controllers/storagecluster/topology.go
=> storagecluster: move topology map reconciliation into its own resourceManager

controllers/storagecluster/external_resources.go, controllers/storagecluster/generate.go, controllers/storagecluster/noobaa_system_reconciler.go, controllers/storagecluster/noobaa_system_reconciler_test.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/storageclasses_test.go
Backport of #1257 after resolving the conflicts
/assign @jarrpa 
/assign @obnoxxx
=> Bug 2000865: [release-4.9] revert: creation of thick provisioned storage class in 4.9 

controllers/storagecluster/noobaa_system_reconciler.go
=> noobaa: don't set NodeAffinity for standalone

controllers/storagecluster/placement.go, controllers/storagecluster/placement_test.go
add check for PodAntiAffinity not nil before checking
underlying resources otherwise it will cause nil pointer
err. Also updating unit test to test this nil pointer
condition.
=> add check for PodAntiAffinity not nil

controllers/storagecluster/noobaa_system_reconciler.go
Inject default label to noobaa_system_reconciler
Signed-off-by: liranmauda <liran.mauda@gmail.com>
=> Inject default label to noobaa_system_reconciler

functests/config.go, functests/ocs/cluster_upgrade_test.go, functests/setup_teardown.go, hack/cluster-deploy.sh, hack/functest.sh, hack/gen-deployment-yaml.sh, pkg/deploy-manager/subscription.go, tools/cluster-deploy/cluster-deploy.go
Moving to index images from appregistry format so renaming the variables to more general names.
=> Refactor code to rename variables to refer to catalog image

must-gather/collection-scripts/gather_ceph_resources
=> must-gather: add listomapvals command for ceph rados

must-gather/collection-scripts/gather_namespaced_resources
This commit collects must-gather for
`oc describe configmap -n openshift-dr-system`
=> Collect must-gather for oc describe configmap

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/job_templates.go
adding `tty:true` to toolbox deployment
as it need to acces terminal.
=> toolbox: add `tty:true` to toolbox deployment

controllers/storagecluster/provider_server.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller.go, controllers/storagecluster/uninstall_reconciler.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, go.mod, tools/csv-merger/csv-merger.go, vendor/modules.txt
create required resources to enable the remote connection on the provider.
=> Implement a controller for ocs to ocs provider

controllers/storagecluster/provider_server.go
remove nigoyal from the logs which was left mistakenly during the
initial PR.
=> ocs-to-ocs: correct logging

controllers/storagecluster/provider_server.go
STORAGE_CLUSTER_NAME and STORAGE_CLUSTER_UID is required for the garbage
collection of the storage consumer.
=> ocs-to-ocs: Add required env var in the API server deployment

services/provider/client/client.go
- This PR abstracts the gRPC connection by adding it inside the `NewProviderClient` function. 
- Also provides an function to close the connection 
- Passes parent context for each gRPC call.
=> Update gRPC provider client

services/provider/client/client.go
=> add nil check before closing the provider client connection

config/rbac/role.yaml, controllers/storagecluster/cephcluster.go, controllers/storagecluster/external_ocs.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/uninstall_reconciler.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in
As part of the PR Implement onboard, upscaling and offboard.
=> ocs-to-ocs: Implement API calls for the consumer

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
fix: https://bugzilla.redhat.com/show_bug.cgi?id=2046186
=> api: move the TODO line above so it does not show up in the description

controllers/storagecluster/uninstall_reconciler.go
make sure no storageConsumer exists before proceeding with the
uninstallation in the provider cluster.
=> ocs-to-ocs: make sure no storageConsumer exists in the provider

controllers/storagecluster/external_resources.go
skip offboarding request if consumer is not onboarded.
=> ocs-to-ocs: verify consumer is onboarded before offboarding

must-gather/collection-scripts/gather, must-gather/collection-scripts/post-uninstall.sh, must-gather/collection-scripts/pre-install.sh
skip helper pod creation and ceph log collection for MCG only cluster
=> must-gather: skip helper pod creation and ceph log collection

controllers/storagecluster/cephobjectstores.go
=> rgw-kms: fix invalid memory issue

controllers/storagecluster/provider_server.go, deploy/bundle/manifests/provider-role.yaml, deploy/bundle/manifests/provider-role_binding.yaml, deploy/bundle/manifests/provider-sa.yaml, rbac/provider-role.yaml, rbac/provider-role_binding.yaml, rbac/provider-sa.yaml
create role, roleBinding, serviceAccount to grant permission to the API
server for accessing the other resources.
=> provider: create resources to add permissions to the server

config/rbac/role.yaml, controllers/storageconsumer/storageconsumer_controller.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in
This PR adds changes to StorageConsumer controller to provide storage service (rbd) for the consumers . 
Signed-off-by: kesavan kvellalo@redhat.com
=> StorageConsumer: [Ceph rbd] Add controller changes to provide storage service for consumers

services/provider/server/server.go
This PR validates the signature of the onboarding ticket
used by the consumer cluster to onboard a storage provider cluster
Note: This PR assumes that the public key secret to be created by the deployer will be called `onboarding-ticket-key`
=> validate onboarding ticket signature.

services/provider/server/server.go, services/provider/server/server_test.go
this commit fetch cephFilesystemSubVolumeGroup resources
from rook and append it to the external resource list.
=> ocs-to-ocs: fetch cephFilesystemSubVolumeGroup resources

services/provider/server/server.go
adding check to verify if if ticket date is greater than current date.
=> ocs-to-ocs: check if ticket date is greater than current date

api/v1alpha1/storageconsumer_types.go, api/v1alpha1/zz_generated.deepcopy.go, controllers/storageconsumer/storageconsumer_controller.go, services/provider/server/server_test.go
This PR holds the fix related to cephresource spec update and refactoring
=> Storageconsumer: Added changes to fix cephresource spec update

api/v1alpha1/storageconsumer_types.go, api/v1alpha1/zz_generated.deepcopy.go, controllers/storageconsumer/storageconsumer_controller.go, services/provider/server/server_test.go
This PR holds the api changes to modify CephResources type  
Signed-off-by: kesavan kvellalo@redhat.com
=> storageconsumer: Added api changes to modify CephResources type  

controllers/storagecluster/cephobjectstores.go
=> rgw-kms: skip unsupported configs

controllers/storagecluster/provider_server.go, deploy/bundle/manifests/provider-role.yaml, rbac/provider-role.yaml, services/provider/server/consumer.go
list storageConsumerList and node ip within namespace
Closes: https://github.com/red-hat-storage/ocs-operator/issues/1514
=> ocs-to-ocs: list within namespace

controllers/storagecluster/storageclasses.go
4.10 epic covers vault SA based kms encryption only for cluster-wide encryption. 
After discussing with QE and PM, we are decided to skip this feature for now.
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>
=> Skip SC creation for vault SA based kms encryption

controllers/storageconsumer/storageconsumer_controller.go
fix nil map and subvolume group naming
closes : #1521 
=> storageconsumer: Fix nil map and subvolume group naming

controllers/storageconsumer/storageconsumer_controller.go
This is PR is to fix the empty update on the Kind field 
=> Controller: StorageConsumer fix to update kind field in cephResources status

services/provider/server/server.go, services/provider/server/server_test.go
=> prefix `client` before ceph username

deploy/bundle/manifests/provider-role.yaml, rbac/provider-role.yaml, services/provider/server/server.go, services/provider/server/server_test.go
fetching mgr pod hostIP instead of clusterIP.
=> ocs-to-ocs: get mgr pod hostIP

controllers/storagecluster/provider_server_test.go, controllers/storagecluster/uninstall_reconciler_test.go
=> unitTests: Add tests for ocs to ocs provider side code

must-gather/collection-scripts/gather_clusterscoped_resources
This commit collects output for
`oc describe volumereplicationclass` in must-gather
=> must-gather: add output for desc vrc

.gitignore, hack/ticketgen/ticketcheck.go, hack/ticketgen/ticketcheck.sh, hack/ticketgen/ticketgen.sh
=> hack: add tools for working with consumer onboarding tickets

controllers/storagecluster/external_ocs.go, controllers/storagecluster/reconcile.go, services/provider/server/consumer.go, services/provider/server/server.go
https://bugzilla.redhat.com/show_bug.cgi?id=2056634
=> ocs to ocs: fix onboarding acknowledegement

controllers/storagecluster/uninstall_reconciler.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2061550
=> Delete cephRBDMirror while deleting StorageCluster

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/routes.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
This PR add option to disable Route for cephobjectstore in `StorageCluster` Spec
=> add a option to disable route for cephobjectstore 

controllers/storagecluster/external_ocs.go, controllers/storagecluster/external_resources.go, controllers/storagecluster/uninstall_reconciler.go
=> ocs to ocs: create default storageclassclaims

services/provider/client/client.go
client API should not have the GRPC messages as the input for that reason introducing a new StorageType const so that setting the GRPC storageType can be done inside the FulfillStorageClassClaim client function.
/assign @nb-ohad
=> add StorageType as input param for FulfillStorageClassClaim

controllers/storagecluster/routes.go
This reverts commit 0bcab7b9f2c96fd5a22d958fe55e9a3d21fe0978.
=> Revert "add termination policy to TLS in cephobjectstore route"

hack/ticketgen/README.md, hack/ticketgen/ticketcheck.sh, hack/ticketgen/ticketgen.sh
This PR adds additional documentation and compatibility fixes to the ticketgen scripts.
=> hack: update ticketgen scripts

controllers/storagecluster/external_resources.go
use LabelSelector instead of Raw metav1.ListOptions which does not work
as intended.
=> controllers: Fix the list options

services/provider/server/server_test.go
Did some code cleanup and  added unit test case for FulfillStorageClassClaim, RevokeStorageClassClaim and GetStorageClassClaimConfig RPC.
=> Add unit test for storageclassclaim RPC

controllers/storagecluster/cephconfig.go, controllers/storagecluster/cephconfig_test.go
For a provider storage cluster extra rook ceph configs are required to solve a performance problem.
**[global]
osd_pool_default_pg_autoscale_mode = off
osd_pool_default_pg_num = 128
osd_pool_default_pgp_num = 128**
-  Added Unit tests
Signed-off-by: Kaustav Majumder <kmajumde@redhat.com>
=> [BZ: 2076468]Added extra rook configs for provider clusters

api/v1alpha1/storageclassclaim_types.go, config/rbac/role.yaml, controllers/storageclassclaim/storageclassclaim_controller.go, controllers/storageconsumer/storageconsumer_controller.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in, services/provider/server/server.go, services/provider/server/storageclaim.go
adding changes in storageClassClaim and storageConsumer controller
to provision required rook resources.
=> ocs-to-ocs: storageclassclaim cntrl provider change

controllers/storageconsumer/storageconsumer_controller.go
=> ocs-to-ocs: fix wrong error check

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/routes.go, deploy/bundle/manifests/storagecluster.crd.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml
(cherry picked from commit efbbea35ae7c670059032724562f880456fcf432)
=> Bug 2074591: [release 4.9] add a option to disable route for cephobjectstore 

api/v1alpha1/storageclassclaim_types.go, config/rbac/role.yaml, controllers/storageclassclaim/storageclassclaim_controller.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in
Consumer cluster users should be able to create a StorageClassClaim and get a
StorageClass.
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>
=> Implement StorageClassClaim creation for consumer cluster

controllers/ocsinitialization/sccs.go
Call the Rook api for SCCs. A rook api is available for generating the correct scc expected for rook components. Update to the new api so we don't have the ocs operator owning an outdated scc spec. The `rook-ceph-rgw` service account was missing in the scc, which is causing RGW to fail to start in 4.11 as seen in this issue: https://bugzilla.redhat.com/show_bug.cgi?id=2075581
=> Call the Rook API for SCC generation

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/mirroring.libsonnet
=> metrics: PV mirror status alerts

api/v1alpha1/storageclassclaim_types.go, controllers/storageclassclaim/storageclassclaim_controller.go
Consumer cluster users should be able to delete a StorageClassClaim.
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>
***
Please only consider the changes coming in from the last commit, everything else is being worked upon as per the reviews received on #1608.
=> Implement StorageClassClaim deletion part for consumer cluster

services/provider/server/server.go, services/provider/server/server_test.go
check the status.Phase for GetStorageClassClaimConfig based on the Phase return success or failure response.
/assign @umangachapagain 
/assign @nb-ohad
=> add status.Phase check for GetStorageClassClaimConfig

controllers/storageclassclaim/storageclassclaim_controller.go, controllers/storageconsumer/storageconsumer_controller.go, go.mod, services/provider/server/consumer.go, services/provider/server/storageclaim.go
adding changes for deletion of Ceph resources on
storageClassClaim on provider side.
=> ocs-to-ocs: delete ceph resources on SC claim provider

controllers/storageclassclaim/storageclassclaim_controller.go
adding missing namespace while creating sc
=> ocs-to-ocs: adding missing namespace while creating sc

controllers/storageclassclaim/storageclassclaim_controller.go
ocs-to-ocs: create subvolumegroup in consumer side
ocs-to-ocs: deletion subvolumegroup on consumer side
=> ocs-to-ocs: create/delete subvolumegroup in consumer side

controllers/storageclassclaim/storageclassclaim_controller.go
This PR includes fixes for bugs discovered on the consumer side while FF
testing, including:
* Don't filter out PVs based on `spec.storageClassName`, as the index is
not recognized.
* Move SCC checks under consumer mode.
* Remove finalizer on SCC.
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>
=> FF patches

controllers/storageclassclaim/storageclassclaim_controller.go
Instead of using hardcoded kind use  GVK to get the consumer Kind and use it for comparision.
/assign @nb-ohad
=> use GVK to get Kind of consumer obj

Makefile, hack/golangci_lint.sh, main.go
=> few tiny changes required for golang 1.18

controllers/storageclassclaim/storageclassclaim_controller.go, controllers/storagecluster/cephblockpools.go, controllers/storagecluster/cephconfig.go, controllers/storagecluster/cephconfig_test.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/generate.go, controllers/util/cephutil.go, controllers/util/cephutil_test.go
Signed-off-by: Kaustav Majumder <kmajumde@redhat.com>
=> Added Parameters to CephFilesystemSubVolumeGroup and CephBlockPool for Provider Clusters

controllers/storageclassclaim/storageclassclaim_controller.go
In case of upgrade, we are getting error `panic: assignment to entry in nil map`
because while blockpool creation in 4.10, it was created without labels
and in 4.11 we are trying to assign label which is empty.
This commit fix above issue.
=> odf-to-odf: initialize map when adding labels

must-gather/OWNERS
=> must-gather: add Yati as an approver for must-gather

must-gather/collection-scripts/gather_namespaced_resources
This commit collects output for get and describe
of storageclassclaim for all namespaces and also
collects the yaml file for it.
=> must-gather: collects output for storageclassclaim

controllers/storageconsumer/consumer_test.go, controllers/storageconsumer/storageconsumer_controller.go
apart form cephclient healther status remove
every other status from consumer cr status.
=> odf-to-odf: clean consumer cr status

controllers/storagecluster/external_resources.go
Signed-off-by: Dhruv Bindra <dbindra@redhat.com>
=> Initialize rookCephOperatorCM if data is nil

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Signed-off-by: Bipul Adhikari <badhikar@redhat.com>
=> Updates annotation to disable features in Console

OWNERS
=> Add user iamniting in approver list

controllers/storagecluster/clusterclaims.go
Signed-off-by: Vineet Badrinath <vineetbnath@gmail.com>
=> Return csv version instead of name

controllers/storagecluster/cephblockpools.go, controllers/storagecluster/storageclasses.go
Some corrections/changes to the Non-Resilient/Replica-1 cephblockpool  & the storageclass.
=> Some corrections in Non-Resilient cephblockpool & storageclass

metrics/internal/collectors/cluster-advance-feature-use.go
A single 'ocs-advanced-feature-usage' metric should be send per Openshift installation. The metric value will be set to '1' if any of the ceph-cluster in any namespace is using an advanced-feature (like PV/KMS encryption or external cluster mode etc)
=> Advanced feature metric should be send per ODF installation

controllers/storagecluster/generate.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/volumesnapshotterclasses.go, controllers/storagecluster/volumesnapshotterclasses_test.go
Refers- [RHSTOR-3435](https://issues.redhat.com/browse/RHSTOR-3435)
For the NFS Dev preview, we are enabling volume expansion for NFS storageclass & deploying a default NFS volume snapshot class.
=> NFS Dev Preview : Allow volume expansion for NFS & deploy a NFS volumesnapshot class

metrics/internal/collectors/cluster-advance-feature-use.go
Previously each advanced feature provider was using the same caching mechanism. This was causing crash while running the cluster. Now each provider has its own caching indexer.
=> Add separate 'SharedIndexInformer' to each feature providers

controllers/ocsinitialization/sccs.go, deploy/bundle/manifests/ceph-conf.yaml, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, metrics/deploy/ceph-conf.yaml, metrics/deploy/deployment.yaml, metrics/internal/cache/rbd-mirror.go, rbac/ceph-conf.yaml, tools/csv-merger/csv-merger.go
Fixes: [Bug 2124379](https://bugzilla.redhat.com/show_bug.cgi?id=2124379)
Depends on #1812
=> Remove privileged access from metrics-exporter

.github/workflows/ocs-operator-ci.yaml, controllers/storageclassclaim/storageclassclaim_controller.go, controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephcluster_test.go, controllers/storagecluster/external_resources_test.go, controllers/storagecluster/job_templates.go, controllers/storagecluster/provider_server_test.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/topology.go, controllers/storagecluster/volumesnapshotterclasses.go, controllers/storageconsumer/storageconsumer_controller.go, docs/design/metrics-exporter.md, docs/design/osd-topology-spread-constraints.md, docs/openshift-ci.md, hack/cluster-deploy.sh, hack/red-hat-storage-ocs-ci-tests.sh, main.go, must-gather/collection-scripts/gather_namespaced_resources, must-gather/collection-scripts/gather_noobaa_resources, pkg/deploy-manager/storagecluster.go, services/provider/server/server.go, tools/csv-merger/csv-merger.go
Fix a few typos, quotes, and spaces in the workflow.
Also, add 2 new workflows- code-spell & docker-build-and-push
=> Fix few mistakes in workflow & add code-spell workflow

main.go
Currently ocs-operator is relying on the default "AllNamespaces" cache
in controller-runtime, which works by syncing all the Kubernetes
resources in the cluster. This initial informer cache sync is so huge
that it causes a sudden massive spike in the memory usage of the
operator. This causes OOMKilled failures for the ocs-operator pods.
So ocs-operator will now set the leaderElectionNamespace & the Manager
cache to the namespace where the operator is deployed. This will
ensure that the initial cache sync will only sync the resources in the
namespace where the operator is deployed.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2126626
=> Limit OCS operator leaderElection & cache to operator namespace

deploy/bundle/manifests/exporter-role.yaml, metrics/deploy/rbac.yaml, rbac/exporter-role.yaml
Added permissions to list/get/watch CephRBDMirrors and StorageClasses
=> Fix permissions for newly added resources

metrics/mixin/Makefile, metrics/mixin/rules/rules.libsonnet
Fixed latency query and removed the previous (not-needed) fix.
=> Fix utilization values mismatch queries

.github/workflows/ocs-operator-ci.yaml, must-gather/collection-scripts/gather_namespaced_resources
This commit collects the following csiaddons object details in must-gather:
1. csiaddonsnode
2. reclaimspacejob
3. reclaimspacecronjob
4. networkfence
=> must-gather: collect csiaddons object

must-gather/collection-scripts/gather_ceph_resources
This commit collects the journal logs
in gzip format in ceph directory.
To unzip it run: `gunzip filename`
=> must-gather: collect journal logs

hack/install-noobaa-operator.sh
This PR is an extension of an earlier PR https://github.com/red-hat-storage/ocs-operator/pull/1861
=> hack: add logic to approve install plan

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml
Ran `make gen-latest-prometheus-rules-yamls` to sync the changes in libsonnet files to metrics/deploy
=> Sync all the libsonnet changes to metrics deploy files

must-gather/collection-scripts/gather_ceph_resources
This commit collects the journal and kernel logs
seperately according to the nodes.
=> must-gather: collect journal and kernel logs for all nodes

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml
Ran `make gen-latest-prometheus-rules-yamls` to sync the changes in libsonnet files to metrics/deploy
(cherry picked from commit 50f09cbeb565fa7ea88ae89a7de04fffa02254a7)
=> Bug 2124282: [release-4.9] Sync all libsonnet changes

hack/install-noobaa-operator.sh
=> hack: fix shell check errors

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
=> disable webhook for rook untill offically supported

controllers/storagecluster/reconcile.go
This adds a warning in the logs if both in-transit encryption and compression are enabled. This will help the user to understand the behaviour.
Combining encryption with compression reduces the level of security of messages between peers. In case both encryption and compression are enabled, compression setting will be ignored and message will not be compressed. 
Reference-
https://issues.redhat.com/browse/RHSTOR-2516
https://issues.redhat.com/browse/RHSTOR-3328
=> Warn in logs if both in-transit encryption & compression are enabled

deploy/csv-templates/fcs-operator.csv.yaml.in, deploy/fcs-operator/manifests/fcs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2165938
=> add annotation to the CSV for disconnected env

deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
=> Bug 2165960:[release-4.12] add annotation to the CSV for disconnected env

controllers/storagecluster/prometheus.go
=> do not use hardcoded ns for ocs-prometheus-rules

controllers/storagecluster/storageclasses.go
solves - https://issues.redhat.com/browse/RHSTOR-4213
=> feat: enabled kubernetes auth for SC and SS

deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
disable rook webhook untill we supporte it officially.
=> Bug 2154164:[release-4.11] disable rook webhook

.ci-operator.yaml, .github/workflows/ocs-operator-ci.yaml, Dockerfile, build/Dockerfile.build, go.mod, hack/golangci_lint.sh, metrics/Dockerfile
Update
1. go.mod
2. github actions
3. build Dockerfiles
4. build root image
=> Update to golang 1.19

controllers/storagecluster/routes.go, controllers/storagecluster/routes_test.go
=> expose seperate route for secure port in RGW

hack/operator-sdk-common.sh
**Description:**
Update formatting of the hack/operator-sdk-common.sh to support zsh
=> chore: Update formatting in shell script

config/rbac/exporter-role.yaml, controllers/storagecluster/cephcluster.go, deploy/csv-templates/ics-operator.csv.yaml.in, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/deploy/rbac.yaml, metrics/internal/collectors/ocs-client.go, metrics/internal/collectors/registry.go, metrics/internal/collectors/storage-cluster.go, metrics/mixin/alerts/alerts-external.libsonnet, metrics/mixin/alerts/alerts.libsonnet, metrics/mixin/alerts/encryption-external.libsonnet, metrics/mixin/alerts/encryption.libsonnet, metrics/mixin/alerts/obc.libsonnet, metrics/mixin/config.libsonnet
Added StorageCluster collector on OCS exporter to implement KMS connection lost alerts.
Credits to original PR: #1831
Co-authored-by: Pranshu Srivastava <rexagod@gmail.com>
=> Add KMS alert

controllers/ocsinitialization/ocsinitialization_controller.go, deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
=> Bug 2176356: [release-4.10] Moving the defaults for rookceph operator from configmap to csv

controllers/storagecluster/storagecluster_controller.go
If the CRD is not present, it can prevent the ocs-operator from
starting which can cause problems for MS. Since MS is not going
to install the noobaa CSV anymore, it is better to only watch the
noobaa CRs if the SKIP_NOOBAA_CRD_WATCH is set to false.
MS will set SKIP_NOOBAA_CRD_WATCH env in the sub which will be
populated to the ocs-operator via OLM.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2182041
=> do not watch noobaa CRs if SKIP_NOOBAA_CRD_WATCH is set to true

metrics/mixin/alerts/services.libsonnet
This commit makes minor changes to the description to help point the
user to correct subsystem
=> make the description for Cluster Object Store more specific

controllers/storagecluster/prometheus/localcephrules.yaml
This will allow the results to be grouped by namespace and not dependent on any particular one.
=> Added 'namespace' tag to queries

controllers/storagecluster/storagecluster_controller.go
Fix the issue where OCSInitialization adds its own name to the storage cluster request queue when there is a change in it. Modify the code to enqueue the storage cluster name instead.
(cherry picked from commit 9bb4ec3034227221959522b3777bf1c2b3b040ca)
Manual Backport of #1999
=> Bug 2185190:[release-4.12] Correct storage cluster request queuing in OCSInitialization

services/provider/server/storageclassrequest.go
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2188666
=> ms: fix label on storageclassrequest cr

metrics/internal/cache/ceph-blocklist.go, metrics/internal/cache/pv.go, metrics/internal/cache/rbd-mirror.go
Remove all the hardcoded namespace values and make the code general.
=> Make metric code namespace agnostic

metrics/internal/collectors/cluster-advance-feature-use.go
=> Bug 2188228: [release-4.12] Exporter fixes for StorageCluster and StorageClass metrics

services/provider/server/server.go
The GRPC server `server.go` will not have the storageClassRequest Name to log the storageClassRequest information. The server will have details only about the storageclassclaim, and it's still acting on the StorageClassClaim RPC, correcting the logging in the `server.go`
=> fix logging for the storageclassclaim in server

config/rbac/exporter-role.yaml, deploy/csv-templates/ics-operator.csv.yaml.in, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ics-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, go.mod, metrics/deploy/prometheus-ocs-rules.yaml, metrics/deploy/rbac.yaml, metrics/internal/cache/ceph-blocklist.go, metrics/internal/cache/pv.go, metrics/internal/collectors/ceph-blocklist.go, metrics/internal/collectors/registry.go, metrics/mixin/alerts/blocklist.libsonnet, services/provider/server/server.go
This commit restructures things to make the metric more reliable, it also keeps tracks of all the nodes.
=> fix changes overwriting of clients in the RBDClientMap

config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml, deploy/Dockerfile, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/metadata/annotations.yaml, hack/operator-sdk-common.sh
Also, make changes according to the version upgrade guide available here
https://sdk.operatorframework.io/docs/upgrading-sdk-version/
=> Update operator-sdk version to v1.25.4 from v1.20.0

Makefile, hack/install-noobaa.sh, hack/install-ocs.sh
Should be merged after https://github.com/red-hat-storage/ocs-operator/pull/2090
=> Fixes in make target for controller-gen, kustomize, install-ocs & install-noobaa

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/internal/collectors/ceph-object-store.go, metrics/internal/collectors/ceph-object-store_test.go, metrics/mixin/alerts/services-external.libsonnet, metrics/mixin/alerts/services.libsonnet
Include more conditions in RGW health status, and update the alerts based on the changes
=> update the metric for rgw_health_status

controllers/storagecluster/storageclasses.go, controllers/storagecluster/storageclasses_test.go
solves: https://issues.redhat.com/browse/RHSTOR-4530
=> feat: support ocs encrypted volume with cross-ns smart cloning in CNV

must-gather/collection-scripts/gather_ceph_resources
This commit is to resolve jq not found error.
=> Bug 2210475: [release-4.12] cleanup to resolve jq: command not found error

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/provider_server.go, controllers/storagecluster/provider_server_test.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml
Duplicate of #2103
Created to check the CI cluster
=> Toggle between OCS Provider Server Service Type

controllers/storagecluster/cephobjectstores.go
add topology mode annotation rgw for service
=> add topology mode annotation rgw service

controllers/storagecluster/job_templates.go
Resolves-https://bugzilla.redhat.com/show_bug.cgi?id=1970939
This eliminates the need to delete the older/existing job when
triggering the job for a second time.
=> Delete completed template job so no need to delete it when rerunning the job

controllers/storagecluster/cephtoolbox.go
Add an annotation to ceph toolbox when multus network provider is set.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1982721
=> Add multus related annotations to ceph toolbox

controllers/storagecluster/provider_server.go
When the ProviderAPIServer is of type NodePort, the ocs operator waits for LoadBalancer endpoint to be available, which should not be the case. add a condition so that when service is of type nodePort, this check is not done.
The PR also updates the StoragProviderEndpoint appropriately based on the type of the Service.
=> fix provAPIServer when NodePort svc is stuck waiting for lb endpoint

deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2232464
=> set priority class for csi pods

controllers/storagecluster/cephcluster.go
This reverts commit e810e0526272528c07f2baed5344d087ab08b28c.
=> Bug 2234735:[release-4.14] Revert "support osd migration in RDR customers

metrics/internal/collectors/registry.go
PR containing the latest commits from main branch
=> Syncing latest changes from main for ocs-operator

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/storageclasses.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml
Ref-https://issues.redhat.com/browse/RHSTOR-2452
=> Provide a flag to mark rbd storageclass as the default for the cluster

services/provider/server/server.go
- Differentiate b/n data set on a field and default value for the type
- If no value is set, use "N/A" as default string value
- For any failed validation, return an error
=> Bug 2247743: Validate client supplied data only when set

config/rbac/exporter-role.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/deploy/rbac.yaml, metrics/internal/collectors/object-bucket.go
Ran make command to update prometheus monitoring yaml files.
=> Ran pending make command and fix obc alerts issue

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/storagecluster/ocs_operator_config.go, controllers/util/k8sutil.go
This is an manual backport of https://github.com/red-hat-storage/ocs-operator/pull/2165
Wait for https://github.com/red-hat-storage/ocs-operator/pull/2196 before merging
=> Bug 2235571:[release-4.13] Fix upgrade issue when storagecluster is not present

controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephfilesystem_test.go
ocs operator should create the default csi svg CR
=> cephfs: add creation of csi default svg

controllers/storagecluster/prometheus/localcephrules.yaml
Added the runbook_url annotation for the files available in runbooks repo
Implements [RHSTOR-4979](https://issues.redhat.com//browse/RHSTOR-4979)
=> monitoring: Update alert annotation runbook_url

config/rbac/role.yaml, controllers/storagecluster/external_resources.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/storageclasses.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
We need to create rados namespace if JSON data contains it Process:
1) Create the rados-namespace CR
2) Update the storage class clusterID with rados clusterID
=> external: create rados namspace for external cluster

controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller.go, controllers/storagecluster/storagecluster_controller_test.go, main.go
=> ensure interal cluster is only allowed in the OperatorNamespace 

controllers/storagecluster/noobaa_system_reconciler.go
BZ : https://bugzilla.redhat.com/show_bug.cgi?id=2251741
Fixed condition where the endpoint was not being properly passed to Noobaa CR due to incorrect condition.
=> Fix the condition for noobaa reconcile 

controllers/storagecluster/reconcile.go, controllers/util/clusters.go
=> Consider all storage clusters status for operator upgradability

controllers/storagecluster/reconcile.go
Ref-https://issues.redhat.com/browse/RHSTOR-5015
=> Skip ensureRbdMirrorDebugLogging job in case of external storage cluster

controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller_test.go, controllers/util/clusters.go
=> Ignore storage clusters that meet specific criteria

controllers/storagecluster/prometheus/localcephrules.yaml, metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/mirroring.libsonnet, metrics/mixin/alerts/obc.libsonnet
this commit adds runbook_urls to further alerts in ceph and ODF
=> add runbooks_url to alerts

metrics/deploy/prometheus-ocs-rules-external.yaml, metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/blocklist.libsonnet, metrics/mixin/alerts/mirroring.libsonnet, metrics/mixin/alerts/obc.libsonnet
Added needed changes for alerts queries to support multicluster mode
=> Changed alerts queries to support multicluster mode

hack/install-noobaa-operator.sh
=> [release-4.12] update the catalog image to point to 4.12 catalog

controllers/storagecluster/reconcile.go, controllers/storagecluster/storagecluster_controller.go
=> [fusion-hci-4.14] Stop provider upgrade if client gets behind

go.mod, metrics/internal/handler/handler.go, metrics/internal/options/options.go, metrics/main.go
This is a manual cherry-pick of #2353
=> Bug 2256458: [release-4.14] Enhanced logger for ocs-metrics-exporter

go.mod, metrics/internal/handler/handler.go, metrics/internal/options/options.go, metrics/main.go
This is a manual cherry-pick of #2353
=> Bug 2256459: [release-4.13] Enhanced logger for ocs-metrics-exporter

CONTRIBUTING.md
=> make changes to the contribution guide

services/ux-backend/main.go
Common validation and default value handling for env vars configuration
=> UX Backend - Unified handling of env var based configuration

controllers/storagecluster/prometheus/localcephrules.yaml
Fixes: #2257634
https://bugzilla.redhat.com/show_bug.cgi?id=2257634
=> Fixed wrong runbook link for PersistentVolumeUsageNearFull alert

api/go.mod, api/go.sum, api/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go, api/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, api/vendor/modules.txt, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, go.mod, go.sum, hack/common.sh, metrics/go.mod, metrics/go.sum, metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go, metrics/vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, metrics/vendor/modules.txt, vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go, vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, vendor/modules.txt
update noobaa version that is compatible with rook 1.13.1
=> update noobaa version that is compatible with rook 1.13.1

PROJECT, config/manifests/ocs-operator/bases/ocs-operator.clusterserviceversion.yaml, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
=> update Project file

metrics/deploy/prometheus-ocs-rules.yaml, metrics/mixin/alerts/perf.libsonnet
https://github.com/openshift/runbooks/pull/162
=> add runbook url for MDSCpuUsageHigh alert.

controllers/storagecluster/cephobjectstores.go
Revert "add topology mode annotation rgw service" 
Bug 2255232
=> Revert "add topology mode annotation rgw service"

controllers/storagecluster/exporter.go
Refactor parts of metrics exporter deployment to simplfy code and keep it readable.
It also fixes bugs related to updating deployment artifacts.
=> refactor metrics exporter deployment

controllers/storagecluster/noobaa_system_reconciler.go
Currently, default placement is used if noobaa-standalone placement is not found. We want to use noobaa-core if noobaa-standalone placement is not provided or default otherwise.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2260550
=> Added a fix for noobaa-standalone placement configuration

metrics/deploy/prometheus-ocs-rules.yaml
this PR adds the links for OSDCPUHighLoad to the alert definition
=> add runbook_url for OSDCPUHighLoad alert

controllers/util/k8sutil.go, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Because I tend to do things slightly weird I found a few small bits of cleanup here and there, as well as one odd bug. I don't remember how I hit it, but I've been holding this in a working branch for a while, so here ya go. The change in the CSV is purely cosmetic, and shouldn't affect the downstream builds.
=> Various small fixes found during development

services/provider/server/server.go, services/provider/server/server_test.go
=> provider: check for RADOS namespace CephResource

controllers/storagecluster/generate.go, controllers/storagecluster/volumesnapshotterclasses.go
=> Bug 2271371:[release-4.15] Use operator namespace as a driver name

config/manager/manager.yaml, controllers/storagecluster/exporter.go, controllers/storagecluster/provider_server.go, controllers/storagecluster/provider_server_test.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2273387
=> bundle: add readOnlyRootFilesystem for ocs-operator

config/manager/manager.yaml, controllers/storagecluster/exporter.go, controllers/storagecluster/provider_server.go, controllers/storagecluster/provider_server_test.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
This is an manual cherry-pick of #2545
=> Bug 2274100:[release-4.15] bundle: add readOnlyRootFilesystem for ocs-operator

api/v1/storagecluster_types.go, controllers/storagecluster/cephtoolbox.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
This will allow the CephToolbox pod to get scheduled on specific node.
https://bugzilla.redhat.com/show_bug.cgi?id=2249640
=> Support specifying Node Affinity for CephToolbox pod

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Aligning validation rule with Rook validation.
=> Fix rbd daemon count validation

api/v1/storagecluster_types.go, config/crd/bases/ocs.openshift.io_storageclusters.yaml, controllers/storagecluster/noobaa_system_reconciler.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Noobaa PR: https://github.com/noobaa/noobaa-operator/pull/1318
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2283797
=> noobaa: provide denyHTTP option to NooBaa CR

controllers/storagecluster/exporter.go
When ocs-operator creates ocs-metrics-exporter ServiceAccount, some Secret references are injected into it. We should not reset these references.
This PR removes the CreateOrUpdate call which overrides everything and instead uses a granular check to verify the existence of the ServiceAccount and required labels and ownerreferences on it.
=> do not reset ocs-metrics-exporter ServiceAccount specs

Makefile, catalog/index.yaml, hack/common.sh, hack/install-ocs-operator.sh
=> install all operators within one script

api/v1alpha1/storageconsumer_types.go, config/crd/bases/ocs.openshift.io_storageconsumers.yaml, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml, deploy/ocs-operator/manifests/storageconsumer.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go
Changed the status fields for storageconsumers to optional
=> BUG 2292114: api: changed storageConsumer status fields to optional

config/rbac/role.yaml, controllers/storagecluster/reconcile.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
=> Add missing RBACs required for ocs-metrics-exporter

controllers/storagecluster/storageclasses.go
Set reclaimspace schedule to weekly for all RBD storageclasses
=> annotate RBD storageclasses for reclaimspace

services/provider/server/consumer.go, services/provider/server/consumer_test.go, services/provider/server/server.go, services/ux-backend/handlers/onboardingtokens/handler.go
- Code changes involve decoding/unmarshalling the token when the client is onboarding.
- Added the new test cases
- I have modified the test case to function with the current changes
=> Adding changes to decode/Unmarshal quota from token

build/Dockerfile
This change was left with the #2007
=> [release-4.13] remove status-reporter binary copy step

controllers/storagecluster/storageclasses.go
Annotate RBD storageclasses for keyrotation with default schedule as weekly.
=> Annotate RBD storageclasses for keyrotation

build/Dockerfile
This change was left with the #2009
=> [release-4.12] remove status-reporter binary copy step

services/provider/server/server.go, services/provider/server/server_test.go
- When clients request storage client config, Send encoded bytes of the cluster resource quota spec.
- Send the bytes only if storage quota is applicable for the client
- Testing results added https://github.com/red-hat-storage/ocs-client-operator/pull/182-
=> Sending encoded bytes for storage quota

controllers/defaults/placements.go, controllers/storagecluster/placement.go, controllers/storagecluster/placement_test.go
mds pod created from UI and default mds pod
can be created at same node
=> mds: fix mds placement

config/rbac/role.yaml, controllers/storageconsumer/consumer_test.go, controllers/storageconsumer/storageconsumer_controller.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, deploy/ocs-operator/manifests/provider-role.yaml, rbac/provider-role.yaml, services/provider/server/consumer.go, services/provider/server/consumer_test.go, services/provider/server/server.go, services/provider/server/server_test.go
This is a cherry-pick of https://github.com/red-hat-storage/ocs-operator/pull/2733
=> Bug 2309488:[release-4.17] Added support for ocs provider server to fetch noobaa client resources

api/v1alpha1/odfinfoconfig.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/odfinfoconfig.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
- This change re-adds the isDROptimized check feature as it's now required in 4.17 which will be using Ceph 7.
- Skipping the tests for this never before tested feature with a flag for now. Will be tested in follow up PR. 
Fix for [BZ-2311468](https://bugzilla.redhat.com/show_bug.cgi?id=2311468).
=> Bug 2311468: [release-4.17] Re-adds DR Optimized check feature

services/provider/server/server.go
Fix provider server panic while onboarding Consumers when the value of the storageQuota in the onboardingTicket is set to nil
Introduced with: https://github.com/red-hat-storage/ocs-operator/pull/2669
=> fix panic in provider server while onboarding

hack/install-ocs-operator.sh
Update the existing background patch process to run continuously, ensuring the ocs-client-operator-config ConfigMap remains patched. This prevents OLM from resetting the ConfigMap and causing deployment failures.
Expansion of https://github.com/red-hat-storage/ocs-operator/pull/2773/commits/b9ee4ba293d9967030f5b75ff4a18ae13cc35a82
=> hack: run continuous patch for ocs-client-operator-config

catalog/index.yaml, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, hack/common.sh
=> update rook and noobaa images

controllers/mirroring/mirroring_controller.go
1. Update the mirroring finalizer to the right name
2. fix radosnamespace mirroring
=> controllers: fix mirroring controller

services/provider/server/server.go
add missing namespace for storage-client-mapping configMap
Testing: Provided a build to QE for testing it and it works.
=> provider: provide namespace for storage-client-mapping config

controllers/ocsinitialization/ocsinitialization_controller.go, controllers/ocsinitialization/ocsinitialization_controller_test.go, controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go
Related PRs:
#2970
https://github.com/red-hat-storage/rook/pull/803
https://issues.redhat.com/browse/DFBUGS-1357
=> set ROOK_CSI_ENABLE_CEPHFS in the ocs-operator-config configmap

services/provider/server/server.go, services/provider/server/server_test.go
The PR does the following:
1. Add the missing required fields for VolumeGroupSnapshotClass 
2. Update the name to align with internal mode.
=> provider: add missing fields for vgsc

controllers/storagecluster/volumegroupsnapshotterclasses.go, controllers/storagecluster/volumesnapshotterclasses.go
adds disable field to CephBlockPool and CephFilesystem GroupSnapshotClassConfiguration.
=> adds disable field to *GroupSnapshotClassConfiguration

controllers/storagecluster/external_resources.go, controllers/storagecluster/reconcile.go
Bug: https://issues.redhat.com/browse/DFBUGS-1512
=> Fix issue with the ceph block pool rados namespace storage class

services/provider/server/server.go, services/provider/server/server_test.go
Until 4.18 Provider mode was using v1(6789) port as default, so v1 ports were present in the rook-ceph-mon-endpoints CM. Rook doesn’t update this CM to v2 3300 port until the mons are failed over, even after requireMsgr2 is set to true. Provider sends the mon endpoints from the same rook-ceph-mon-endpoints CM to the client, so the client uses the v1 (6789) port address it received in it’s ceph-csi-config CM.
But client receives the cephFS kernel mount option from provider as ‘prefer-crc’ as requireMsgr2 is true. When mounting new cephFS volume on client side it tries to use the v1 6789 port with the ‘prefer-crc’ kernel mount option. Which can't work,thus cephFS volumes fail to mount.
As since 4.18 we are using v2 port always, so the provider should send the v2 port address to the client …
=> Fix CephFS volumes failing to mount after upgrade to 4.18 in Provider Mode

controllers/storagecluster/prometheus/localcephrules.yaml
Jira: https://issues.redhat.com/browse/DFBUGS-1547
- Runbook will be added as part of different PR and different repo
- Test results are added as comment
=> added missing alert from upstream

deploy/ocs-operator/manifests/provider-role.yaml, rbac/provider-role.yaml
add missing role to list cephcluster for provider-server
=> provider: add missing permissions

docs/design/storage-auto-scale.md
added a design doc for auto storage scaling
=> autoscale: add a design doc for auto storage scaling

controllers/storagecluster/provider_server.go, controllers/storagecluster/provider_server_test.go
https://issues.redhat.com/browse/DFBUGS-931
=> DFBUGS-931:[release-4.18] disable provider when allowremotestorageconsumers is not set

controllers/storagecluster/cephfilesystem.go
disable the mds livenessProbe till rook finds an
rca and fixes it
=> mds: disable the mds livenessProbe

config/crd/kustomization.yaml, config/crd/patches/label_in_storageclusters.yaml, deploy/ocs-operator/manifests/storagecluster.crd.yaml, tools/csv-merger/csv-merger.go
Related PR: https://github.com/red-hat-storage/odf-operator/pull/555
=> add isStorageSystem label to the storagecluster 

api/v1/storagecluster_types.go, controllers/storagecluster/storageclasses.go, controllers/storagecluster/volumegroupsnapshotterclasses.go, controllers/storagecluster/volumesnapshotterclasses.go, deploy/single-node-storagecluster-provider.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Ref- https://issues.redhat.com/browse/RHSTOR-6916
Part of Internal Mode & Provider mode convergence effort
=> Deprecate DisableStorageClass & DisableSnapshotClass fields

api/v1alpha1/odfinfoconfig.go, controllers/storagecluster/external_resources_test.go, controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/odfinfoconfig.go, controllers/storagecluster/odfinfoconfig_test.go, controllers/storagecluster/storagecluster_controller_test.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go, pkg/deploy-manager/config.go, pkg/deploy-manager/storagecluster.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/odfinfoconfig.go
storagesystem is depricated
Bug: https://issues.redhat.com/browse/DFBUGS-1880
=> remove the storagesystem from the odfinfo configmap

services/provider/server/server.go
Get the radosnamespace for a consumer from the consumer configmap 
Review only the last commit
Depends On: https://github.com/red-hat-storage/ocs-operator/pull/3062
=> provider: get the radosnamespace name from consumer configmap

controllers/storagecluster/exporter.go, metrics/deploy/prometheus-ocs-rules.yaml, metrics/deploy/rbac.yaml, metrics/internal/collectors/ocs-client.go, metrics/internal/collectors/registry.go, metrics/internal/collectors/storage-auto-scaler.go
https://issues.redhat.com/browse/RHSTOR-6878
=> Adding metrics and alerts related to StorageAutoScaler CR

controllers/storageautoscaler/scraper.go
StorageautoScaler CR should be present to query prometheus, othrwise we can avoid calling to prometheus
It reduces the api calls if the cluster doesnt have auto scaling enabled
=> autoscale: avoid querying prometheus if autosclaer cr is not present

hack/install-ocs-operator.sh
disable ocp catsrc to get away with OCP intermittent issue
=> ci: disable ocp catsrc

controllers/storageconsumer/storageconsumer_controller.go
Add rbd and cephfs node and provisioner cephClients
=> controllers: add ceph clients for cephfs and rbd

controllers/storageconsumer/storageconsumer_controller.go, controllers/util/storageclasses.go, hack/common.sh, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go
fix small issues related to conergence
=> convergence: add small fixes

controllers/storageconsumer/storageconsumer_controller.go, controllers/util/storageconsumer.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go
calculate the default client profile name based on storageconsumer name and uid
=> consumer: update calculation of the default clientprofile name

controllers/util/k8sutil.go, controllers/util/snapshotclasses.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/snapshotclasses.go, services/provider/server/server.go
This PR implements the GetDesiredClientState that was introduced with https://github.com/red-hat-storage/ocs-operator/pull/3133
=> server: implement the GetDesiredClientState rpc

services/provider/server/server.go
When I try to get the gvk from the object using `kubeResource.GetObjectKind().GroupVersionKind()` it is empty, I need to pass in the scheme to get it from apiutil package to verify if GVK is empty or not.
Secret/Core resource doesn't have a Group we cannot fail for empty group.
ClientProfile Name was empty, adding the name before sending the resources
=> server: fix the new rpc call

controllers/storagecluster/volumegroupsnapshotterclasses.go, controllers/storagecluster/volumesnapshotterclasses.go
there was a regression from https://github.com/red-hat-storage/ocs-operator/pull/3087
which breaked the working on radonamesapce snap class
Added the logic back to make it working
=> external: fix external mode snapshot class

services/provider/server/server.go, services/provider/server/server_test.go
Write a shim layer for older clients on 4.18 which will be using the old rpc calls
=> server: write shim for GetStorageConfig 

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/storagequota.go
=> fix Error logs

config/manager/manager.yaml, controllers/storagecluster/cephcluster.go, controllers/storagecluster/exporter.go, controllers/storagecluster/provider_server.go, controllers/storagecluster/provider_server_test.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml, tools/csv-merger/csv-merger.go
Bug: https://issues.redhat.com/browse/DFBUGS-394
=> add priorityClassName under deployments

controllers/storageconsumer/storageconsumer_upgrade_controller.go
This commit fixes small issues with the upgrade controller and removesthe  ownerRef of the StorageRequest from the SVG CR
=> controllers: implement upgrade controller for provider mode

config/rbac/role.yaml, controllers/storageconsumer/storageconsumer_upgrade_controller.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
Fix the typo and update the rbac for consumer update contoller
=> controllers: fix rbac and typo for update controller

controllers/storagecluster/storageclient.go
Disable CSI controller plugin host network when the storage cluster is not on host network
=> controllers: disable csi ctrlPlugin hostNetwork for internal client

controllers/storageconsumer/storageconsumer_controller.go, controllers/storageconsumer/storageconsumer_upgrade_controller.go, controllers/util/groupsnapshotclasses.go, controllers/util/snapshotclasses.go, controllers/util/storageclasses.go, controllers/util/storageconsumer.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/groupsnapshotclasses.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/snapshotclasses.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageclasses.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/storageconsumer.go, services/provider/server/server.go
Replace the keys in the consumer configMap along with Getters/Setters and Replace 
Fixes: https://issues.redhat.com/browse/DFBUGS-2287
=> controllers: update the keys in the consumer configmap

api/v1alpha1/storageconsumer_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/ocs.openshift.io_storageconsumers.yaml, controllers/mirroring/mirroring_controller.go, controllers/storagecluster/odfinfoconfig.go, controllers/storagecluster/odfinfoconfig_test.go, controllers/storagecluster/reconcile.go, controllers/storageconsumer/consumer_test.go, controllers/storageconsumer/storageconsumer_controller.go, deploy/csv-templates/crds/ocs/ocs.openshift.io_storageconsumers.yaml, deploy/ocs-operator/manifests/storageconsumer.crd.yaml, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go, services/provider/server/consumer.go, services/provider/server/server.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/storageconsumer_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1alpha1/zz_generated.deepcopy.go
1. Update the client information under storage consumer status to be a pointer.
2. Add checks to see if the client is nil before checking client Information
fixes: https://issues.redhat.com/browse/DFBUGS-2269
=> controllers: make client information under consumer status a pointer 

controllers/storagecluster/clusterclaims.go
=> DFBUGS-2305:[release-4.16] check csvs in the operator ns instead of storagecluster ns

config/rbac/role.yaml, controllers/storageconsumer/storageconsumer_controller.go, controllers/storageconsumer/storageconsumer_upgrade_controller.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
1. fix permission for consumer controller
2. remove finalizer from storagerequest before deletion
Fixes: https://issues.redhat.com/browse/DFBUGS-2468
=> controller: fix permissions for consumer controller

controllers/storageautoscaler/storageautoscaler_controller.go
if we moved the cr to invalid state, there was
no way to make the phase back to no-started,
If the invalid state is not detected anymore
move the phase to not-started
=> storageautoscaler: fix the invalid state phase

services/provider/server/server.go
1. Add monips to the desired state hash for clients
2. Update the hash to include only the consumer spec since status changes every min
Fixes: https://issues.redhat.com/browse/DFBUGS-2359
=> server: add monips as a part of desired state hash

metrics/deploy/prometheus-ocs-rules.yaml, metrics/internal/collectors/storage-auto-scaler.go
https://issues.redhat.com/browse/DFBUGS-2048
=> Adding an alert to detect StorageAutoScaler CRs in invalid state

controllers/storagecluster/prometheus/localcephrules.yaml
BZ (for 4.16): https://issues.redhat.com/browse/DFBUGS-1190
PS: once merged (in main branch) need to backport to older releases
=> Add missing 'managedBy' to make the label combination unique

controllers/storageconsumer/consumer_test.go, controllers/storageconsumer/storageconsumer_controller.go, controllers/util/k8sutil.go, controllers/util/util.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/k8sutil.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/util.go, services/provider/server/server.go
The PR implements consumer deletion and force deletion.
For force Deletion, we add an annotation to the rook rns/svg so that they are also deleted.
Fixes: https://issues.redhat.com/browse/DFBUGS-2332
=> controllers: implement consumer deletion

controllers/storagecluster/storageclient.go
For a storage cluster using multus
For internal mode csi controller plugins were managed by rook in 4.18, but in upgraded version csi controller plugins are managed by ceph-csi-operator managed by ocs-client-operator.
The csi controller plugin pods are missing network spec required for connecting to multus network.
[DFBUGS-2636](https://issues.redhat.com//browse/DFBUGS-2636)
=> controllers: add nw annotation to stoarageclient when multus enabled

controllers/storageconsumer/storageconsumer_controller.go, services/provider/server/server.go
Disable noobaa on client clusters
[DFBUGS-2640](https://issues.redhat.com//browse/DFBUGS-2640)
=> disable noobaa on client clusters

services/ux-backend/handlers/expandstorage/handler.go
remove the hardcoded config from storageclass. These are added when we distribute the storageclass to clients
Fixes: https://issues.redhat.com/browse/DFBUGS-2922
=> ux-backend: remove hardcoded config from storageclass

Makefile, hack/common.sh
Remove unused variables, Combine unnecessary default variables and organize variables so similar variables are grouped together. Also added comments where necessary.
=> Organize & cleanup the common.sh file

metrics/internal/cache/pv.go, metrics/internal/cache/pv_test.go, metrics/internal/collectors/rbd-children-count.go, metrics/internal/collectors/registry.go, metrics/main.go
This commit exposes new metrics to count no of
clones for each image
=> metrics-exporter: add new metrics to count rbd children

OWNERS
jarrpa has moved to Fusion team, nbalacha has moved to the Ceph team & umangachapagain has left IBM.
=> Update Owners to exclude umangachapagain, jarrpa, and nbalacha

services/provider/server/consumer_test.go, services/provider/server/storageclusterpeer_test.go, services/provider/server/test_helpers.go
- Add tests for consumer
- Add tests for storageclusterpeer
=> add unit tests for server package

controllers/storageautoscaler/storageautoscaler_controller.go
currently autoscaler was moving phase to noStarted in case of external mode, but it should move to invalid phase as it is not supported
=> autoscaler: autoscaler should move to invalid in case of external mode

controllers/storagecluster/storageclient.go, controllers/storagecluster/storageconsumer.go
This PR makes sure to delete the storageclient and the storageconsumer internal configmap, so that deletion of storagecluster is not blocked
1. Get the storage client before removing the finalizer
2. Delete the local storage consumer configmap
Fixes: [DFBUGS-2674](https://issues.redhat.com/browse/DFBUGS-2674)
=> controller: fix deletion phase

controllers/storagecluster/cephcluster.go, controllers/storagecluster/cephfilesystem.go, controllers/storagecluster/cephnfs.go, controllers/storagecluster/cephobjectstores.go, controllers/storagecluster/external_resources.go
Bug: https://issues.redhat.com/browse/DFBUGS-394
=> promote all openshift-user-critical pods to system-cluster-critical

controllers/util/replicationclasses.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/v4/controllers/util/replicationclasses.go, services/provider/server/server.go
Add rename and alias capability to VRC
=> server: add rename and alias capability to vrc

controllers/storagecluster/initialization_reconciler_test.go, controllers/storagecluster/reconcile.go, controllers/storagecluster/rookoperatorhostnetwork.go, controllers/storagecluster/storagecluster_controller_test.go, deploy/csv-templates/ocs-operator.csv.yaml.in, deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
when using host network with specified public address range rook operator should run on host network to avoid connection issue between pod network and second host network
=> enable host network for rook operator

metrics/deploy/prometheus-ocs-rules.yaml
BZ: https://issues.redhat.com/browse/DFBUGS-3869
=> Correcting the alert firing timing for HighRBDCloneSnapshotCount

controllers/storagecluster/cephblockpools.go
The setDefaultDataPoolSpec is called on the actual poolSpec. In this the fields like failure domain, device class, etc are already set. So we end up not modifying them further even though they should now have a new values based on the storageCluster. To solve this we now start with an empty poolSpec in each reconcile. We preserve the existing mirroring spec as it's handled by the mirroring controller.
Ref-https://issues.redhat.com/browse/DFBUGS-4107
=> Fix blockPool spec fields like failure domain not getting updated

controllers/storageconsumer/storageconsumer_controller.go
The cephClients were created by the primary consumers, with the suffix of consumer uid. As a result for MDR scenarios, there were no ceph users created for the secondary client. As mdr follows an active-active approach we need ceph users with same permissions to be created for both consumers primary as well as secondary consumer.
Fixes: [DFBUGS-4204](https://issues.redhat.com/browse/DFBUGS-4204)
=> consumer: create cephclients for each consumer

api/v1/storagecluster_types.go, controllers/storagecluster/cephtoolbox.go, metrics/vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
Tools deployment should not be a part of api pkg. Moving it to storagecluster/cephtoolbox pkg
=> controllers: remove newToolsDeployment from api pkg
